// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dstsim

import (
	"fmt"
	"io"

	"github.com/multigres/multigres/go/tools/dstsim/sortedmaps"
)

// TraceBuffer is a circular buffer for storing TickTrace entries
// It automatically discards oldest entries when capacity is reached
type TraceBuffer[I any, R any, ID comparable] struct {
	buffer   []TickTrace[I, R, ID]
	capacity int  // Maximum number of ticks to retain (0 = unlimited)
	head     int  // Index of oldest entry (for circular buffer)
	size     int  // Current number of entries
	wrapped  bool // Whether we've wrapped around (buffer is full)
}

// NewTraceBuffer creates a new trace buffer with the given capacity
// capacity of 0 means unlimited (no old entries are discarded)
func NewTraceBuffer[I any, R any, ID comparable](capacity int) *TraceBuffer[I, R, ID] {
	if capacity <= 0 {
		capacity = 1000 // Default to 1000 if not specified
	}
	return &TraceBuffer[I, R, ID]{
		buffer:   make([]TickTrace[I, R, ID], 0, capacity),
		capacity: capacity,
		head:     0,
		size:     0,
		wrapped:  false,
	}
}

// Append adds a new trace entry, potentially evicting the oldest entry
func (tb *TraceBuffer[I, R, ID]) Append(trace TickTrace[I, R, ID]) {
	if tb.size < tb.capacity {
		// Still growing, just append
		tb.buffer = append(tb.buffer, trace)
		tb.size++
	} else {
		// Buffer is full, overwrite oldest entry
		tb.buffer[tb.head] = trace
		tb.head = (tb.head + 1) % tb.capacity
		tb.wrapped = true
	}
}

// All returns all trace entries in chronological order
func (tb *TraceBuffer[I, R, ID]) All() []TickTrace[I, R, ID] {
	if !tb.wrapped {
		// Haven't wrapped yet, return everything in order
		return tb.buffer[:tb.size]
	}

	// Wrapped: need to return entries starting from head (oldest)
	result := make([]TickTrace[I, R, ID], tb.size)
	for i := 0; i < tb.size; i++ {
		idx := (tb.head + i) % tb.capacity
		result[i] = tb.buffer[idx]
	}
	return result
}

// Recent returns the most recent N entries (or all if N > size)
func (tb *TraceBuffer[I, R, ID]) Recent(n int) []TickTrace[I, R, ID] {
	all := tb.All()
	if n <= 0 || n >= len(all) {
		return all
	}
	return all[len(all)-n:]
}

// Len returns the number of trace entries currently stored
func (tb *TraceBuffer[I, R, ID]) Len() int {
	return tb.size
}

// NodeStateSnapshot is an optional interface that nodes can implement to provide
// a human-readable summary of their current state for trace debugging. When
// implemented, the simulator captures a snapshot each tick and FormatTrace
// prints the cluster state at the beginning and end of the trace segment.
type NodeStateSnapshot interface {
	StateSnapshot() string
}

// TickTrace represents all activity in a single tick.
type TickTrace[I any, R any, ID comparable] struct {
	Tick                int64
	NodeSteps           map[ID]NodeStepTrace[I, R] // Activity for each node during this tick
	NodeSnapshots       map[ID]string              // Node state snapshots (for nodes implementing NodeStateSnapshot)
	DroppedIndicators   []DroppedIndicator[I, ID]  // Indicators dropped by policy or stopped-node check
	DelayedIndicators   []DelayedIndicator[I, ID]  // Indicators scheduled with delay > 1 tick (in-flight)
	PolicyTransitions   []string                   // Network events: partition start/end, group assignments
	AssertionViolations []string                   // Assertion violations that occurred this tick
	NodeChanges         []string                   // Node lifecycle changes (stopped, restarted, etc.)
}

// NodeStepTrace represents a single node's inputs and outputs for one tick.
type NodeStepTrace[I any, R any] struct {
	Indicators []I // Indicators delivered to this node in this tick
	Requests   []R // Requests generated by this node in this tick
}

// DroppedIndicator records an indicator that was not delivered.
type DroppedIndicator[I any, ID comparable] struct {
	FromNode   ID // Node that sent the indicator
	TargetNode ID // Node that would have received the indicator
	Indicator  I  // The indicator that was dropped
}

// DelayedIndicator records an indicator that was scheduled for delivery in a future
// tick (delay > 1). This makes in-flight messages visible in the trace so you can
// see why nodes are acting on stale information.
type DelayedIndicator[I any, ID comparable] struct {
	FromNode   ID
	TargetNode ID
	Indicator  I
	DeliverAt  int64 // absolute tick when this indicator will be delivered
}

// Trace returns the complete event trace organized by tick
// Note: Due to trace retention policy, this may not include all ticks from the start of simulation
func (s *Simulator[I, R, ID]) Trace() []TickTrace[I, R, ID] {
	return s.traceBuffer.All()
}

// FormatTrace writes the given trace entries to w in human-readable form.
// If traces is empty, writes "No trace available".
// This function can be called directly with hand-crafted traces for testing.
func FormatTrace[I any, R any, ID comparable](w io.Writer, traces []TickTrace[I, R, ID]) {
	if len(traces) == 0 {
		fmt.Fprintf(w, "No trace available\n")
		return
	}

	fmt.Fprintf(w, "\n=== Recent Trace (last %d ticks, %d-%d) ===\n",
		len(traces),
		traces[0].Tick,
		traces[len(traces)-1].Tick)

	// Print cluster state at the start of the trace window
	if len(traces[0].NodeSnapshots) > 0 {
		fmt.Fprintf(w, "\nCluster state at tick %d (start):\n", traces[0].Tick)
		for nodeID, snap := range sortedmaps.ByStr(traces[0].NodeSnapshots) {
			fmt.Fprintf(w, "  %v: %s\n", nodeID, snap)
		}
	}

	for i := range traces {
		tt := &traces[i]

		fmt.Fprintf(w, "\n--- Tick %d ---\n", tt.Tick)

		// Show assertion violations first (most important)
		if len(tt.AssertionViolations) > 0 {
			fmt.Fprintf(w, "⚠️  ASSERTION VIOLATIONS:\n")
			for _, violation := range tt.AssertionViolations {
				fmt.Fprintf(w, "    %s\n", violation)
			}
		}

		// Show network events (partition start/end, group assignments)
		if len(tt.PolicyTransitions) > 0 {
			fmt.Fprintf(w, "Network events:\n")
			for _, event := range tt.PolicyTransitions {
				fmt.Fprintf(w, "  %s\n", event)
			}
		}

		// Show node activity (sort by node ID string for deterministic output)
		if len(tt.NodeSteps) > 0 {
			fmt.Fprintf(w, "Node activity:\n")
			for nodeID, step := range sortedmaps.ByStr(tt.NodeSteps) {
				if len(step.Indicators) > 0 {
					fmt.Fprintf(w, "  %v received %d indicators\n", nodeID, len(step.Indicators))
					for _, ind := range step.Indicators {
						fmt.Fprintf(w, "    <- %T %+v\n", ind, ind)
					}
				}
				if len(step.Requests) > 0 {
					fmt.Fprintf(w, "  %v generated %d requests\n", nodeID, len(step.Requests))
					for _, req := range step.Requests {
						fmt.Fprintf(w, "    -> %T %+v\n", req, req)
					}
				}
			}
		}

		// Show dropped indicators
		if len(tt.DroppedIndicators) > 0 {
			fmt.Fprintf(w, "Dropped:\n")
			for _, dropped := range tt.DroppedIndicators {
				fmt.Fprintf(w, "  %v <- %T %+v (from %v)\n", dropped.TargetNode, dropped.Indicator, dropped.Indicator, dropped.FromNode)
			}
		}

		// Show in-flight indicators (delayed more than 1 tick)
		if len(tt.DelayedIndicators) > 0 {
			fmt.Fprintf(w, "In-flight:\n")
			for _, delayed := range tt.DelayedIndicators {
				delayTicks := delayed.DeliverAt - tt.Tick
				fmt.Fprintf(w, "  %v <- %T %+v (from %v, +%d ticks, arrives tick %d)\n",
					delayed.TargetNode, delayed.Indicator, delayed.Indicator, delayed.FromNode, delayTicks, delayed.DeliverAt)
			}
		}

		// Show node changes (additions/removals)
		if len(tt.NodeChanges) > 0 {
			fmt.Fprintf(w, "Node changes:\n")
			for _, change := range tt.NodeChanges {
				fmt.Fprintf(w, "  %s\n", change)
			}
		}
	}

	// Print cluster state at the end of the trace window
	last := traces[len(traces)-1]
	if len(last.NodeSnapshots) > 0 {
		fmt.Fprintf(w, "\nCluster state at tick %d (end):\n", last.Tick)
		for nodeID, snap := range sortedmaps.ByStr(last.NodeSnapshots) {
			fmt.Fprintf(w, "  %v: %s\n", nodeID, snap)
		}
	}

	fmt.Fprintf(w, "\n=== End of Trace ===\n")
}

// DumpRecentTrace writes the most recent N ticks from the trace to the given writer
// If numTicks is 0 or greater than available ticks, dumps all available trace
// This is useful for debugging test failures or understanding recent simulation behavior
func (s *Simulator[I, R, ID]) DumpRecentTrace(w io.Writer, numTicks int) {
	FormatTrace(w, s.traceBuffer.Recent(numTicks))
}
