// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dstsim

import (
	"fmt"
	"io"
)

// TraceBuffer is a circular buffer for storing TickTrace entries
// It automatically discards oldest entries when capacity is reached
type TraceBuffer[I any, R any, ID comparable] struct {
	buffer   []TickTrace[I, R, ID]
	capacity int  // Maximum number of ticks to retain (0 = unlimited)
	head     int  // Index of oldest entry (for circular buffer)
	size     int  // Current number of entries
	wrapped  bool // Whether we've wrapped around (buffer is full)
}

// NewTraceBuffer creates a new trace buffer with the given capacity
// capacity of 0 means unlimited (no old entries are discarded)
func NewTraceBuffer[I any, R any, ID comparable](capacity int) *TraceBuffer[I, R, ID] {
	if capacity <= 0 {
		capacity = 1000 // Default to 1000 if not specified
	}
	return &TraceBuffer[I, R, ID]{
		buffer:   make([]TickTrace[I, R, ID], 0, capacity),
		capacity: capacity,
		head:     0,
		size:     0,
		wrapped:  false,
	}
}

// Append adds a new trace entry, potentially evicting the oldest entry
func (tb *TraceBuffer[I, R, ID]) Append(trace TickTrace[I, R, ID]) {
	if tb.size < tb.capacity {
		// Still growing, just append
		tb.buffer = append(tb.buffer, trace)
		tb.size++
	} else {
		// Buffer is full, overwrite oldest entry
		tb.buffer[tb.head] = trace
		tb.head = (tb.head + 1) % tb.capacity
		tb.wrapped = true
	}
}

// All returns all trace entries in chronological order
func (tb *TraceBuffer[I, R, ID]) All() []TickTrace[I, R, ID] {
	if !tb.wrapped {
		// Haven't wrapped yet, return everything in order
		return tb.buffer[:tb.size]
	}

	// Wrapped: need to return entries starting from head (oldest)
	result := make([]TickTrace[I, R, ID], tb.size)
	for i := 0; i < tb.size; i++ {
		idx := (tb.head + i) % tb.capacity
		result[i] = tb.buffer[idx]
	}
	return result
}

// Recent returns the most recent N entries (or all if N > size)
func (tb *TraceBuffer[I, R, ID]) Recent(n int) []TickTrace[I, R, ID] {
	all := tb.All()
	if n <= 0 || n >= len(all) {
		return all
	}
	return all[len(all)-n:]
}

// Len returns the number of trace entries currently stored
func (tb *TraceBuffer[I, R, ID]) Len() int {
	return tb.size
}

// TickTrace represents all activity in a single tick
// TODO: Add PolicyTransitions []string to track when delivery policies change
// (e.g., "Network partition started", "Chaos mode ended") so trace dumps show
// network condition changes that affect the protocol behavior
type TickTrace[I any, R any, ID comparable] struct {
	Tick                int64
	NodeSteps           map[ID]NodeStepTrace[I, R] // Activity for each node during this tick
	DroppedIndicators   []DroppedIndicator[I, ID]  // Indicators that were dropped by delivery policy
	AssertionViolations []string                   // Assertion violations that occurred this tick
}

// NodeStepTrace represents a single node's inputs and outputs for one tick
// TODO: Add NodeState any field to capture node's internal state snapshot
// (via optional StateProvider interface) for better trace debugging. Would allow
// seeing "node became leader at term 5" in trace dumps instead of just indicators/requests.
type NodeStepTrace[I any, R any] struct {
	Indicators []I // Indicators delivered to this node in this tick
	Requests   []R // Requests generated by this node in this tick
}

// DroppedIndicator records an indicator that was dropped by the delivery policy
type DroppedIndicator[I any, ID comparable] struct {
	TargetNode ID // Node that would have received the indicator
	Indicator  I  // The indicator that was dropped
}

// Trace returns the complete event trace organized by tick
// Note: Due to trace retention policy, this may not include all ticks from the start of simulation
func (s *Simulator[I, R, ID]) Trace() []TickTrace[I, R, ID] {
	return s.traceBuffer.All()
}

// DumpRecentTrace writes the most recent N ticks from the trace to the given writer
// If numTicks is 0 or greater than available ticks, dumps all available trace
// This is useful for debugging test failures or understanding recent simulation behavior
func (s *Simulator[I, R, ID]) DumpRecentTrace(w io.Writer, numTicks int) {
	traces := s.traceBuffer.Recent(numTicks)

	if len(traces) == 0 {
		fmt.Fprintf(w, "No trace available\n")
		return
	}

	fmt.Fprintf(w, "\n=== Recent Trace (last %d ticks, %d-%d) ===\n",
		len(traces),
		traces[0].Tick,
		traces[len(traces)-1].Tick)

	for i := range traces {
		tickTrace := &traces[i]

		fmt.Fprintf(w, "\n--- Tick %d ---\n", tickTrace.Tick)

		// Show assertion violations first (most important)
		if len(tickTrace.AssertionViolations) > 0 {
			fmt.Fprintf(w, "⚠️  ASSERTION VIOLATIONS:\n")
			for _, violation := range tickTrace.AssertionViolations {
				fmt.Fprintf(w, "    %s\n", violation)
			}
		}

		// Show node activity
		if len(tickTrace.NodeSteps) > 0 {
			fmt.Fprintf(w, "Node activity:\n")
			for nodeID, step := range tickTrace.NodeSteps {
				if len(step.Indicators) > 0 {
					fmt.Fprintf(w, "  %v received %d indicators\n", nodeID, len(step.Indicators))
					for _, ind := range step.Indicators {
						fmt.Fprintf(w, "    <- %T %+v\n", ind, ind)
					}
				}
				if len(step.Requests) > 0 {
					fmt.Fprintf(w, "  %v generated %d requests\n", nodeID, len(step.Requests))
					for _, req := range step.Requests {
						fmt.Fprintf(w, "    -> %T %+v\n", req, req)
					}
				}
			}
		}

		// Show dropped indicators
		if len(tickTrace.DroppedIndicators) > 0 {
			fmt.Fprintf(w, "Dropped indicators:\n")
			for _, dropped := range tickTrace.DroppedIndicators {
				fmt.Fprintf(w, "  %v <- %T %+v [DROPPED]\n", dropped.TargetNode, dropped.Indicator, dropped.Indicator)
			}
		}
	}

	fmt.Fprintf(w, "\n=== End of Trace ===\n")
}
