// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: multiadmin/v1/multiadminservice.proto

package v1

import (
	v1 "github.com/multigres/multigres/go/pb/clustermetadata/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCellRequest specifies the cell to retrieve
type GetCellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the cell to retrieve
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellRequest) Reset() {
	*x = GetCellRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellRequest) ProtoMessage() {}

func (x *GetCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellRequest.ProtoReflect.Descriptor instead.
func (*GetCellRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetCellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetCellResponse contains the cell information
type GetCellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cell contains the Cell protobuf object
	Cell          *v1.Cell `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellResponse) Reset() {
	*x = GetCellResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellResponse) ProtoMessage() {}

func (x *GetCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellResponse.ProtoReflect.Descriptor instead.
func (*GetCellResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetCellResponse) GetCell() *v1.Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

// GetDatabaseRequest specifies the database to retrieve
type GetDatabaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the database to retrieve
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetDatabaseResponse contains the database information
type GetDatabaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database contains the Database protobuf object
	Database      *v1.Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetDatabaseResponse) GetDatabase() *v1.Database {
	if x != nil {
		return x.Database
	}
	return nil
}

// GetCellNamesRequest requests all cell names
type GetCellNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellNamesRequest) Reset() {
	*x = GetCellNamesRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellNamesRequest) ProtoMessage() {}

func (x *GetCellNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellNamesRequest.ProtoReflect.Descriptor instead.
func (*GetCellNamesRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{4}
}

// GetCellNamesResponse contains all cell names
type GetCellNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellNamesResponse) Reset() {
	*x = GetCellNamesResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellNamesResponse) ProtoMessage() {}

func (x *GetCellNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellNamesResponse.ProtoReflect.Descriptor instead.
func (*GetCellNamesResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{5}
}

func (x *GetCellNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// GetDatabaseNamesRequest requests all database names
type GetDatabaseNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseNamesRequest) Reset() {
	*x = GetDatabaseNamesRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseNamesRequest) ProtoMessage() {}

func (x *GetDatabaseNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseNamesRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseNamesRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{6}
}

// GetDatabaseNamesResponse contains all database names
type GetDatabaseNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseNamesResponse) Reset() {
	*x = GetDatabaseNamesResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseNamesResponse) ProtoMessage() {}

func (x *GetDatabaseNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseNamesResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseNamesResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatabaseNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// GetGatewaysRequest requests gateways with optional filtering
type GetGatewaysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cells is a comma-separated list of cell names to filter by (optional)
	Cells         []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewaysRequest) Reset() {
	*x = GetGatewaysRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaysRequest) ProtoMessage() {}

func (x *GetGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewaysRequest.ProtoReflect.Descriptor instead.
func (*GetGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetGatewaysRequest) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// GetGatewaysResponse contains the filtered gateways
type GetGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*v1.MultiGateway     `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewaysResponse) Reset() {
	*x = GetGatewaysResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaysResponse) ProtoMessage() {}

func (x *GetGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewaysResponse.ProtoReflect.Descriptor instead.
func (*GetGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetGatewaysResponse) GetGateways() []*v1.MultiGateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

// GetPoolersRequest requests poolers with optional filtering
type GetPoolersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cells is a comma-separated list of cell names to filter by (optional)
	Cells []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	// database name to filter by (optional)
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// shard name to filter by (optional)
	Shard         string `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolersRequest) Reset() {
	*x = GetPoolersRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolersRequest) ProtoMessage() {}

func (x *GetPoolersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolersRequest.ProtoReflect.Descriptor instead.
func (*GetPoolersRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{10}
}

func (x *GetPoolersRequest) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *GetPoolersRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetPoolersRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

// GetPoolersResponse contains the filtered poolers
type GetPoolersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Poolers       []*v1.MultiPooler      `protobuf:"bytes,1,rep,name=poolers,proto3" json:"poolers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolersResponse) Reset() {
	*x = GetPoolersResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolersResponse) ProtoMessage() {}

func (x *GetPoolersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolersResponse.ProtoReflect.Descriptor instead.
func (*GetPoolersResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{11}
}

func (x *GetPoolersResponse) GetPoolers() []*v1.MultiPooler {
	if x != nil {
		return x.Poolers
	}
	return nil
}

// GetOrchsRequest requests orchestrators with optional filtering
type GetOrchsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cells is a comma-separated list of cell names to filter by (optional)
	Cells         []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrchsRequest) Reset() {
	*x = GetOrchsRequest{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrchsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrchsRequest) ProtoMessage() {}

func (x *GetOrchsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrchsRequest.ProtoReflect.Descriptor instead.
func (*GetOrchsRequest) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrchsRequest) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// GetOrchsResponse contains the filtered orchestrators
type GetOrchsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
	Orchs         []*v1.MultiOrch `protobuf:"bytes,1,rep,name=orchs,proto3" json:"orchs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrchsResponse) Reset() {
	*x = GetOrchsResponse{}
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrchsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrchsResponse) ProtoMessage() {}

func (x *GetOrchsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadmin_v1_multiadminservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrchsResponse.ProtoReflect.Descriptor instead.
func (*GetOrchsResponse) Descriptor() ([]byte, []int) {
	return file_multiadmin_v1_multiadminservice_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrchsResponse) GetOrchs() []*v1.MultiOrch {
	if x != nil {
		return x.Orchs
	}
	return nil
}

var File_multiadmin_v1_multiadminservice_proto protoreflect.FileDescriptor

const file_multiadmin_v1_multiadminservice_proto_rawDesc = "" +
	"\n" +
	"%multiadmin/v1/multiadminservice.proto\x12\rmultiadmin.v1\x1a(clustermetadata/v1/clustermetadata.proto\"$\n" +
	"\x0eGetCellRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x0fGetCellResponse\x12,\n" +
	"\x04cell\x18\x01 \x01(\v2\x18.clustermetadata.v1.CellR\x04cell\"(\n" +
	"\x12GetDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\x13GetDatabaseResponse\x128\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1c.clustermetadata.v1.DatabaseR\bdatabase\"\x15\n" +
	"\x13GetCellNamesRequest\",\n" +
	"\x14GetCellNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x19\n" +
	"\x17GetDatabaseNamesRequest\"0\n" +
	"\x18GetDatabaseNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"*\n" +
	"\x12GetGatewaysRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"S\n" +
	"\x13GetGatewaysResponse\x12<\n" +
	"\bgateways\x18\x01 \x03(\v2 .clustermetadata.v1.MultiGatewayR\bgateways\"[\n" +
	"\x11GetPoolersRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\"O\n" +
	"\x12GetPoolersResponse\x129\n" +
	"\apoolers\x18\x01 \x03(\v2\x1f.clustermetadata.v1.MultiPoolerR\apoolers\"'\n" +
	"\x0fGetOrchsRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"G\n" +
	"\x10GetOrchsResponse\x123\n" +
	"\x05orchs\x18\x01 \x03(\v2\x1d.clustermetadata.v1.MultiOrchR\x05orchs2\xe7\x04\n" +
	"\x11MultiAdminService\x12H\n" +
	"\aGetCell\x12\x1d.multiadmin.v1.GetCellRequest\x1a\x1e.multiadmin.v1.GetCellResponse\x12T\n" +
	"\vGetDatabase\x12!.multiadmin.v1.GetDatabaseRequest\x1a\".multiadmin.v1.GetDatabaseResponse\x12W\n" +
	"\fGetCellNames\x12\".multiadmin.v1.GetCellNamesRequest\x1a#.multiadmin.v1.GetCellNamesResponse\x12c\n" +
	"\x10GetDatabaseNames\x12&.multiadmin.v1.GetDatabaseNamesRequest\x1a'.multiadmin.v1.GetDatabaseNamesResponse\x12T\n" +
	"\vGetGateways\x12!.multiadmin.v1.GetGatewaysRequest\x1a\".multiadmin.v1.GetGatewaysResponse\x12Q\n" +
	"\n" +
	"GetPoolers\x12 .multiadmin.v1.GetPoolersRequest\x1a!.multiadmin.v1.GetPoolersResponse\x12K\n" +
	"\bGetOrchs\x12\x1e.multiadmin.v1.GetOrchsRequest\x1a\x1f.multiadmin.v1.GetOrchsResponseB4Z2github.com/multigres/multigres/go/pb/multiadmin/v1b\x06proto3"

var (
	file_multiadmin_v1_multiadminservice_proto_rawDescOnce sync.Once
	file_multiadmin_v1_multiadminservice_proto_rawDescData []byte
)

func file_multiadmin_v1_multiadminservice_proto_rawDescGZIP() []byte {
	file_multiadmin_v1_multiadminservice_proto_rawDescOnce.Do(func() {
		file_multiadmin_v1_multiadminservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiadmin_v1_multiadminservice_proto_rawDesc), len(file_multiadmin_v1_multiadminservice_proto_rawDesc)))
	})
	return file_multiadmin_v1_multiadminservice_proto_rawDescData
}

var file_multiadmin_v1_multiadminservice_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_multiadmin_v1_multiadminservice_proto_goTypes = []any{
	(*GetCellRequest)(nil),           // 0: multiadmin.v1.GetCellRequest
	(*GetCellResponse)(nil),          // 1: multiadmin.v1.GetCellResponse
	(*GetDatabaseRequest)(nil),       // 2: multiadmin.v1.GetDatabaseRequest
	(*GetDatabaseResponse)(nil),      // 3: multiadmin.v1.GetDatabaseResponse
	(*GetCellNamesRequest)(nil),      // 4: multiadmin.v1.GetCellNamesRequest
	(*GetCellNamesResponse)(nil),     // 5: multiadmin.v1.GetCellNamesResponse
	(*GetDatabaseNamesRequest)(nil),  // 6: multiadmin.v1.GetDatabaseNamesRequest
	(*GetDatabaseNamesResponse)(nil), // 7: multiadmin.v1.GetDatabaseNamesResponse
	(*GetGatewaysRequest)(nil),       // 8: multiadmin.v1.GetGatewaysRequest
	(*GetGatewaysResponse)(nil),      // 9: multiadmin.v1.GetGatewaysResponse
	(*GetPoolersRequest)(nil),        // 10: multiadmin.v1.GetPoolersRequest
	(*GetPoolersResponse)(nil),       // 11: multiadmin.v1.GetPoolersResponse
	(*GetOrchsRequest)(nil),          // 12: multiadmin.v1.GetOrchsRequest
	(*GetOrchsResponse)(nil),         // 13: multiadmin.v1.GetOrchsResponse
	(*v1.Cell)(nil),                  // 14: clustermetadata.v1.Cell
	(*v1.Database)(nil),              // 15: clustermetadata.v1.Database
	(*v1.MultiGateway)(nil),          // 16: clustermetadata.v1.MultiGateway
	(*v1.MultiPooler)(nil),           // 17: clustermetadata.v1.MultiPooler
	(*v1.MultiOrch)(nil),             // 18: clustermetadata.v1.MultiOrch
}
var file_multiadmin_v1_multiadminservice_proto_depIdxs = []int32{
	14, // 0: multiadmin.v1.GetCellResponse.cell:type_name -> clustermetadata.v1.Cell
	15, // 1: multiadmin.v1.GetDatabaseResponse.database:type_name -> clustermetadata.v1.Database
	16, // 2: multiadmin.v1.GetGatewaysResponse.gateways:type_name -> clustermetadata.v1.MultiGateway
	17, // 3: multiadmin.v1.GetPoolersResponse.poolers:type_name -> clustermetadata.v1.MultiPooler
	18, // 4: multiadmin.v1.GetOrchsResponse.orchs:type_name -> clustermetadata.v1.MultiOrch
	0,  // 5: multiadmin.v1.MultiAdminService.GetCell:input_type -> multiadmin.v1.GetCellRequest
	2,  // 6: multiadmin.v1.MultiAdminService.GetDatabase:input_type -> multiadmin.v1.GetDatabaseRequest
	4,  // 7: multiadmin.v1.MultiAdminService.GetCellNames:input_type -> multiadmin.v1.GetCellNamesRequest
	6,  // 8: multiadmin.v1.MultiAdminService.GetDatabaseNames:input_type -> multiadmin.v1.GetDatabaseNamesRequest
	8,  // 9: multiadmin.v1.MultiAdminService.GetGateways:input_type -> multiadmin.v1.GetGatewaysRequest
	10, // 10: multiadmin.v1.MultiAdminService.GetPoolers:input_type -> multiadmin.v1.GetPoolersRequest
	12, // 11: multiadmin.v1.MultiAdminService.GetOrchs:input_type -> multiadmin.v1.GetOrchsRequest
	1,  // 12: multiadmin.v1.MultiAdminService.GetCell:output_type -> multiadmin.v1.GetCellResponse
	3,  // 13: multiadmin.v1.MultiAdminService.GetDatabase:output_type -> multiadmin.v1.GetDatabaseResponse
	5,  // 14: multiadmin.v1.MultiAdminService.GetCellNames:output_type -> multiadmin.v1.GetCellNamesResponse
	7,  // 15: multiadmin.v1.MultiAdminService.GetDatabaseNames:output_type -> multiadmin.v1.GetDatabaseNamesResponse
	9,  // 16: multiadmin.v1.MultiAdminService.GetGateways:output_type -> multiadmin.v1.GetGatewaysResponse
	11, // 17: multiadmin.v1.MultiAdminService.GetPoolers:output_type -> multiadmin.v1.GetPoolersResponse
	13, // 18: multiadmin.v1.MultiAdminService.GetOrchs:output_type -> multiadmin.v1.GetOrchsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_multiadmin_v1_multiadminservice_proto_init() }
func file_multiadmin_v1_multiadminservice_proto_init() {
	if File_multiadmin_v1_multiadminservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiadmin_v1_multiadminservice_proto_rawDesc), len(file_multiadmin_v1_multiadminservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiadmin_v1_multiadminservice_proto_goTypes,
		DependencyIndexes: file_multiadmin_v1_multiadminservice_proto_depIdxs,
		MessageInfos:      file_multiadmin_v1_multiadminservice_proto_msgTypes,
	}.Build()
	File_multiadmin_v1_multiadminservice_proto = out.File
	file_multiadmin_v1_multiadminservice_proto_goTypes = nil
	file_multiadmin_v1_multiadminservice_proto_depIdxs = nil
}
