// Copyright 2025 Supabase, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: pgctldservice/v1/pgctldservice.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PgCtldService_Start_FullMethodName        = "/pgctldservice.v1.PgCtldService/Start"
	PgCtldService_Stop_FullMethodName         = "/pgctldservice.v1.PgCtldService/Stop"
	PgCtldService_Restart_FullMethodName      = "/pgctldservice.v1.PgCtldService/Restart"
	PgCtldService_ReloadConfig_FullMethodName = "/pgctldservice.v1.PgCtldService/ReloadConfig"
	PgCtldService_Status_FullMethodName       = "/pgctldservice.v1.PgCtldService/Status"
	PgCtldService_Version_FullMethodName      = "/pgctldservice.v1.PgCtldService/Version"
	PgCtldService_InitDataDir_FullMethodName  = "/pgctldservice.v1.PgCtldService/InitDataDir"
)

// PgCtldServiceClient is the client API for PgCtldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PgCtldServiceClient interface {
	// Start PostgreSQL server
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Stop PostgreSQL server
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Restart PostgreSQL server
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	// Reload PostgreSQL configuration
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	// Get PostgreSQL server status
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Get server version information
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	// Initialize data directory
	InitDataDir(ctx context.Context, in *InitDataDirRequest, opts ...grpc.CallOption) (*InitDataDirResponse, error)
}

type pgCtldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPgCtldServiceClient(cc grpc.ClientConnInterface) PgCtldServiceClient {
	return &pgCtldServiceClient{cc}
}

func (c *pgCtldServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, PgCtldService_Start_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pgCtldServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, PgCtldService_Stop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pgCtldServiceClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, PgCtldService_Restart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pgCtldServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	out := new(ReloadConfigResponse)
	err := c.cc.Invoke(ctx, PgCtldService_ReloadConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pgCtldServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PgCtldService_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pgCtldServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, PgCtldService_Version_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pgCtldServiceClient) InitDataDir(ctx context.Context, in *InitDataDirRequest, opts ...grpc.CallOption) (*InitDataDirResponse, error) {
	out := new(InitDataDirResponse)
	err := c.cc.Invoke(ctx, PgCtldService_InitDataDir_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PgCtldServiceServer is the server API for PgCtldService service.
// All implementations must embed UnimplementedPgCtldServiceServer
// for forward compatibility
type PgCtldServiceServer interface {
	// Start PostgreSQL server
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Stop PostgreSQL server
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Restart PostgreSQL server
	Restart(context.Context, *RestartRequest) (*RestartResponse, error)
	// Reload PostgreSQL configuration
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error)
	// Get PostgreSQL server status
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Get server version information
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	// Initialize data directory
	InitDataDir(context.Context, *InitDataDirRequest) (*InitDataDirResponse, error)
	mustEmbedUnimplementedPgCtldServiceServer()
}

// UnimplementedPgCtldServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPgCtldServiceServer struct {
}

func (UnimplementedPgCtldServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPgCtldServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPgCtldServiceServer) Restart(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedPgCtldServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedPgCtldServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPgCtldServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedPgCtldServiceServer) InitDataDir(context.Context, *InitDataDirRequest) (*InitDataDirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDataDir not implemented")
}
func (UnimplementedPgCtldServiceServer) mustEmbedUnimplementedPgCtldServiceServer() {}

// UnsafePgCtldServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PgCtldServiceServer will
// result in compilation errors.
type UnsafePgCtldServiceServer interface {
	mustEmbedUnimplementedPgCtldServiceServer()
}

func RegisterPgCtldServiceServer(s grpc.ServiceRegistrar, srv PgCtldServiceServer) {
	s.RegisterService(&PgCtldService_ServiceDesc, srv)
}

func _PgCtldService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PgCtldService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PgCtldService_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PgCtldService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PgCtldService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PgCtldService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PgCtldService_InitDataDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PgCtldServiceServer).InitDataDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PgCtldService_InitDataDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PgCtldServiceServer).InitDataDir(ctx, req.(*InitDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PgCtldService_ServiceDesc is the grpc.ServiceDesc for PgCtldService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PgCtldService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pgctldservice.v1.PgCtldService",
	HandlerType: (*PgCtldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _PgCtldService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PgCtldService_Stop_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _PgCtldService_Restart_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _PgCtldService_ReloadConfig_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _PgCtldService_Status_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _PgCtldService_Version_Handler,
		},
		{
			MethodName: "InitDataDir",
			Handler:    _PgCtldService_InitDataDir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pgctldservice/v1/pgctldservice.proto",
}
