// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: multiadminservice.proto

package multiadmin

import (
	reflect "reflect"
	unsafe "unsafe"

	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobType indicates the type of async job
type JobType int32

const (
	JobType_JOB_TYPE_UNKNOWN JobType = 0
	JobType_JOB_TYPE_BACKUP  JobType = 1
	JobType_JOB_TYPE_RESTORE JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNKNOWN",
		1: "JOB_TYPE_BACKUP",
		2: "JOB_TYPE_RESTORE",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNKNOWN": 0,
		"JOB_TYPE_BACKUP":  1,
		"JOB_TYPE_RESTORE": 2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_multiadminservice_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_multiadminservice_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// JobStatus indicates the current state of an async job
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNKNOWN   JobStatus = 0
	JobStatus_JOB_STATUS_PENDING   JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 3
	JobStatus_JOB_STATUS_FAILED    JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNKNOWN",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNKNOWN":   0,
		"JOB_STATUS_PENDING":   1,
		"JOB_STATUS_RUNNING":   2,
		"JOB_STATUS_COMPLETED": 3,
		"JOB_STATUS_FAILED":    4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_multiadminservice_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_multiadminservice_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// BackupStatus indicates the state of a backup artifact
type BackupStatus int32

const (
	BackupStatus_BACKUP_STATUS_UNKNOWN    BackupStatus = 0
	BackupStatus_BACKUP_STATUS_INCOMPLETE BackupStatus = 1
	BackupStatus_BACKUP_STATUS_COMPLETE   BackupStatus = 2
	BackupStatus_BACKUP_STATUS_FAILED     BackupStatus = 3
)

// Enum value maps for BackupStatus.
var (
	BackupStatus_name = map[int32]string{
		0: "BACKUP_STATUS_UNKNOWN",
		1: "BACKUP_STATUS_INCOMPLETE",
		2: "BACKUP_STATUS_COMPLETE",
		3: "BACKUP_STATUS_FAILED",
	}
	BackupStatus_value = map[string]int32{
		"BACKUP_STATUS_UNKNOWN":    0,
		"BACKUP_STATUS_INCOMPLETE": 1,
		"BACKUP_STATUS_COMPLETE":   2,
		"BACKUP_STATUS_FAILED":     3,
	}
)

func (x BackupStatus) Enum() *BackupStatus {
	p := new(BackupStatus)
	*p = x
	return p
}

func (x BackupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_multiadminservice_proto_enumTypes[2].Descriptor()
}

func (BackupStatus) Type() protoreflect.EnumType {
	return &file_multiadminservice_proto_enumTypes[2]
}

func (x BackupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// GetCellRequest specifies the cell to retrieve
type GetCellRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCellRequest) Reset() {
	*x = GetCellRequest{}
	mi := &file_multiadminservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellRequest) ProtoMessage() {}

func (x *GetCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCellRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetCellRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetCellRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name is the name of the cell to retrieve
	Name string
}

func (b0 GetCellRequest_builder) Build() *GetCellRequest {
	m0 := &GetCellRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

// GetCellResponse contains the cell information
type GetCellResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cell *clustermetadata.Cell  `protobuf:"bytes,1,opt,name=cell,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCellResponse) Reset() {
	*x = GetCellResponse{}
	mi := &file_multiadminservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellResponse) ProtoMessage() {}

func (x *GetCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCellResponse) GetCell() *clustermetadata.Cell {
	if x != nil {
		return x.xxx_hidden_Cell
	}
	return nil
}

func (x *GetCellResponse) SetCell(v *clustermetadata.Cell) {
	x.xxx_hidden_Cell = v
}

func (x *GetCellResponse) HasCell() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cell != nil
}

func (x *GetCellResponse) ClearCell() {
	x.xxx_hidden_Cell = nil
}

type GetCellResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// cell contains the Cell protobuf object
	Cell *clustermetadata.Cell
}

func (b0 GetCellResponse_builder) Build() *GetCellResponse {
	m0 := &GetCellResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cell = b.Cell
	return m0
}

// GetDatabaseRequest specifies the database to retrieve
type GetDatabaseRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_multiadminservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDatabaseRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetDatabaseRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetDatabaseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name is the name of the database to retrieve
	Name string
}

func (b0 GetDatabaseRequest_builder) Build() *GetDatabaseRequest {
	m0 := &GetDatabaseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

// GetDatabaseResponse contains the database information
type GetDatabaseResponse struct {
	state               protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Database *clustermetadata.Database `protobuf:"bytes,1,opt,name=database,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_multiadminservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDatabaseResponse) GetDatabase() *clustermetadata.Database {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return nil
}

func (x *GetDatabaseResponse) SetDatabase(v *clustermetadata.Database) {
	x.xxx_hidden_Database = v
}

func (x *GetDatabaseResponse) HasDatabase() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Database != nil
}

func (x *GetDatabaseResponse) ClearDatabase() {
	x.xxx_hidden_Database = nil
}

type GetDatabaseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// database contains the Database protobuf object
	Database *clustermetadata.Database
}

func (b0 GetDatabaseResponse_builder) Build() *GetDatabaseResponse {
	m0 := &GetDatabaseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Database = b.Database
	return m0
}

// GetCellNamesRequest requests all cell names
type GetCellNamesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellNamesRequest) Reset() {
	*x = GetCellNamesRequest{}
	mi := &file_multiadminservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellNamesRequest) ProtoMessage() {}

func (x *GetCellNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetCellNamesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetCellNamesRequest_builder) Build() *GetCellNamesRequest {
	m0 := &GetCellNamesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// GetCellNamesResponse contains all cell names
type GetCellNamesResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCellNamesResponse) Reset() {
	*x = GetCellNamesResponse{}
	mi := &file_multiadminservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellNamesResponse) ProtoMessage() {}

func (x *GetCellNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCellNamesResponse) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *GetCellNamesResponse) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type GetCellNamesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 GetCellNamesResponse_builder) Build() *GetCellNamesResponse {
	m0 := &GetCellNamesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

// GetDatabaseNamesRequest requests all database names
type GetDatabaseNamesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseNamesRequest) Reset() {
	*x = GetDatabaseNamesRequest{}
	mi := &file_multiadminservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseNamesRequest) ProtoMessage() {}

func (x *GetDatabaseNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetDatabaseNamesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetDatabaseNamesRequest_builder) Build() *GetDatabaseNamesRequest {
	m0 := &GetDatabaseNamesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// GetDatabaseNamesResponse contains all database names
type GetDatabaseNamesResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Names []string               `protobuf:"bytes,1,rep,name=names,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDatabaseNamesResponse) Reset() {
	*x = GetDatabaseNamesResponse{}
	mi := &file_multiadminservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseNamesResponse) ProtoMessage() {}

func (x *GetDatabaseNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetDatabaseNamesResponse) GetNames() []string {
	if x != nil {
		return x.xxx_hidden_Names
	}
	return nil
}

func (x *GetDatabaseNamesResponse) SetNames(v []string) {
	x.xxx_hidden_Names = v
}

type GetDatabaseNamesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Names []string
}

func (b0 GetDatabaseNamesResponse_builder) Build() *GetDatabaseNamesResponse {
	m0 := &GetDatabaseNamesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Names = b.Names
	return m0
}

// GetGatewaysRequest requests gateways with optional filtering
type GetGatewaysRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cells []string               `protobuf:"bytes,1,rep,name=cells,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetGatewaysRequest) Reset() {
	*x = GetGatewaysRequest{}
	mi := &file_multiadminservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaysRequest) ProtoMessage() {}

func (x *GetGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGatewaysRequest) GetCells() []string {
	if x != nil {
		return x.xxx_hidden_Cells
	}
	return nil
}

func (x *GetGatewaysRequest) SetCells(v []string) {
	x.xxx_hidden_Cells = v
}

type GetGatewaysRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// cells is a comma-separated list of cell names to filter by (optional)
	Cells []string
}

func (b0 GetGatewaysRequest_builder) Build() *GetGatewaysRequest {
	m0 := &GetGatewaysRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cells = b.Cells
	return m0
}

// GetGatewaysResponse contains the filtered gateways
type GetGatewaysResponse struct {
	state               protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Gateways *[]*clustermetadata.MultiGateway `protobuf:"bytes,1,rep,name=gateways,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetGatewaysResponse) Reset() {
	*x = GetGatewaysResponse{}
	mi := &file_multiadminservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaysResponse) ProtoMessage() {}

func (x *GetGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetGatewaysResponse) GetGateways() []*clustermetadata.MultiGateway {
	if x != nil {
		if x.xxx_hidden_Gateways != nil {
			return *x.xxx_hidden_Gateways
		}
	}
	return nil
}

func (x *GetGatewaysResponse) SetGateways(v []*clustermetadata.MultiGateway) {
	x.xxx_hidden_Gateways = &v
}

type GetGatewaysResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Gateways []*clustermetadata.MultiGateway
}

func (b0 GetGatewaysResponse_builder) Build() *GetGatewaysResponse {
	m0 := &GetGatewaysResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Gateways = &b.Gateways
	return m0
}

// GetPoolersRequest requests poolers with optional filtering
type GetPoolersRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cells    []string               `protobuf:"bytes,1,rep,name=cells,proto3"`
	xxx_hidden_Database string                 `protobuf:"bytes,2,opt,name=database,proto3"`
	xxx_hidden_Shard    string                 `protobuf:"bytes,3,opt,name=shard,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetPoolersRequest) Reset() {
	*x = GetPoolersRequest{}
	mi := &file_multiadminservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolersRequest) ProtoMessage() {}

func (x *GetPoolersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPoolersRequest) GetCells() []string {
	if x != nil {
		return x.xxx_hidden_Cells
	}
	return nil
}

func (x *GetPoolersRequest) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *GetPoolersRequest) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *GetPoolersRequest) SetCells(v []string) {
	x.xxx_hidden_Cells = v
}

func (x *GetPoolersRequest) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *GetPoolersRequest) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

type GetPoolersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// cells is a comma-separated list of cell names to filter by (optional)
	Cells []string
	// database name to filter by (optional)
	Database string
	// shard name to filter by (optional)
	Shard string
}

func (b0 GetPoolersRequest_builder) Build() *GetPoolersRequest {
	m0 := &GetPoolersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cells = b.Cells
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_Shard = b.Shard
	return m0
}

// GetPoolersResponse contains the filtered poolers
type GetPoolersResponse struct {
	state              protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Poolers *[]*clustermetadata.MultiPooler `protobuf:"bytes,1,rep,name=poolers,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPoolersResponse) Reset() {
	*x = GetPoolersResponse{}
	mi := &file_multiadminservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolersResponse) ProtoMessage() {}

func (x *GetPoolersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPoolersResponse) GetPoolers() []*clustermetadata.MultiPooler {
	if x != nil {
		if x.xxx_hidden_Poolers != nil {
			return *x.xxx_hidden_Poolers
		}
	}
	return nil
}

func (x *GetPoolersResponse) SetPoolers(v []*clustermetadata.MultiPooler) {
	x.xxx_hidden_Poolers = &v
}

type GetPoolersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Poolers []*clustermetadata.MultiPooler
}

func (b0 GetPoolersResponse_builder) Build() *GetPoolersResponse {
	m0 := &GetPoolersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Poolers = &b.Poolers
	return m0
}

// GetOrchsRequest requests orchestrators with optional filtering
type GetOrchsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cells []string               `protobuf:"bytes,1,rep,name=cells,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrchsRequest) Reset() {
	*x = GetOrchsRequest{}
	mi := &file_multiadminservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrchsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrchsRequest) ProtoMessage() {}

func (x *GetOrchsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOrchsRequest) GetCells() []string {
	if x != nil {
		return x.xxx_hidden_Cells
	}
	return nil
}

func (x *GetOrchsRequest) SetCells(v []string) {
	x.xxx_hidden_Cells = v
}

type GetOrchsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// cells is a comma-separated list of cell names to filter by (optional)
	Cells []string
}

func (b0 GetOrchsRequest_builder) Build() *GetOrchsRequest {
	m0 := &GetOrchsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cells = b.Cells
	return m0
}

// GetOrchsResponse contains the filtered orchestrators
type GetOrchsResponse struct {
	state            protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Orchs *[]*clustermetadata.MultiOrch `protobuf:"bytes,1,rep,name=orchs,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrchsResponse) Reset() {
	*x = GetOrchsResponse{}
	mi := &file_multiadminservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrchsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrchsResponse) ProtoMessage() {}

func (x *GetOrchsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetOrchsResponse) GetOrchs() []*clustermetadata.MultiOrch {
	if x != nil {
		if x.xxx_hidden_Orchs != nil {
			return *x.xxx_hidden_Orchs
		}
	}
	return nil
}

func (x *GetOrchsResponse) SetOrchs(v []*clustermetadata.MultiOrch) {
	x.xxx_hidden_Orchs = &v
}

type GetOrchsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
	Orchs []*clustermetadata.MultiOrch
}

func (b0 GetOrchsResponse_builder) Build() *GetOrchsResponse {
	m0 := &GetOrchsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Orchs = &b.Orchs
	return m0
}

// BackupRequest requests an async backup of a specific shard
type BackupRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Database     string                 `protobuf:"bytes,1,opt,name=database,proto3"`
	xxx_hidden_TableGroup   string                 `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3"`
	xxx_hidden_Shard        string                 `protobuf:"bytes,3,opt,name=shard,proto3"`
	xxx_hidden_Type         string                 `protobuf:"bytes,4,opt,name=type,proto3"`
	xxx_hidden_ForcePrimary bool                   `protobuf:"varint,5,opt,name=force_primary,json=forcePrimary,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_multiadminservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BackupRequest) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *BackupRequest) GetTableGroup() string {
	if x != nil {
		return x.xxx_hidden_TableGroup
	}
	return ""
}

func (x *BackupRequest) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *BackupRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *BackupRequest) GetForcePrimary() bool {
	if x != nil {
		return x.xxx_hidden_ForcePrimary
	}
	return false
}

func (x *BackupRequest) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *BackupRequest) SetTableGroup(v string) {
	x.xxx_hidden_TableGroup = v
}

func (x *BackupRequest) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

func (x *BackupRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *BackupRequest) SetForcePrimary(v bool) {
	x.xxx_hidden_ForcePrimary = v
}

type BackupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// database name (required)
	Database string
	// table_group name (required)
	TableGroup string
	// shard name (required)
	Shard string
	// type of backup: "full", "differential", or "incremental" (required)
	Type string
	// force_primary indicates whether to backup from primary (optional, default false)
	ForcePrimary bool
}

func (b0 BackupRequest_builder) Build() *BackupRequest {
	m0 := &BackupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_TableGroup = b.TableGroup
	x.xxx_hidden_Shard = b.Shard
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_ForcePrimary = b.ForcePrimary
	return m0
}

// BackupResponse contains the job ID for tracking the async backup
type BackupResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_multiadminservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BackupResponse) GetJobId() string {
	if x != nil {
		return x.xxx_hidden_JobId
	}
	return ""
}

func (x *BackupResponse) SetJobId(v string) {
	x.xxx_hidden_JobId = v
}

type BackupResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// job_id is the unique identifier for tracking this backup job
	JobId string
}

func (b0 BackupResponse_builder) Build() *BackupResponse {
	m0 := &BackupResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobId = b.JobId
	return m0
}

// RestoreFromBackupRequest requests an async restore of a specific shard
type RestoreFromBackupRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Database   string                 `protobuf:"bytes,1,opt,name=database,proto3"`
	xxx_hidden_TableGroup string                 `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3"`
	xxx_hidden_Shard      string                 `protobuf:"bytes,3,opt,name=shard,proto3"`
	xxx_hidden_BackupId   string                 `protobuf:"bytes,4,opt,name=backup_id,json=backupId,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RestoreFromBackupRequest) Reset() {
	*x = RestoreFromBackupRequest{}
	mi := &file_multiadminservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromBackupRequest) ProtoMessage() {}

func (x *RestoreFromBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestoreFromBackupRequest) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetTableGroup() string {
	if x != nil {
		return x.xxx_hidden_TableGroup
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetBackupId() string {
	if x != nil {
		return x.xxx_hidden_BackupId
	}
	return ""
}

func (x *RestoreFromBackupRequest) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *RestoreFromBackupRequest) SetTableGroup(v string) {
	x.xxx_hidden_TableGroup = v
}

func (x *RestoreFromBackupRequest) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

func (x *RestoreFromBackupRequest) SetBackupId(v string) {
	x.xxx_hidden_BackupId = v
}

type RestoreFromBackupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// database name (required)
	Database string
	// table_group name (required)
	TableGroup string
	// shard name (required)
	Shard string
	// backup_id to restore from (optional, empty means "latest backup")
	BackupId string
}

func (b0 RestoreFromBackupRequest_builder) Build() *RestoreFromBackupRequest {
	m0 := &RestoreFromBackupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_TableGroup = b.TableGroup
	x.xxx_hidden_Shard = b.Shard
	x.xxx_hidden_BackupId = b.BackupId
	return m0
}

// RestoreFromBackupResponse contains the job ID for tracking the async restore
type RestoreFromBackupResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreFromBackupResponse) Reset() {
	*x = RestoreFromBackupResponse{}
	mi := &file_multiadminservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromBackupResponse) ProtoMessage() {}

func (x *RestoreFromBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestoreFromBackupResponse) GetJobId() string {
	if x != nil {
		return x.xxx_hidden_JobId
	}
	return ""
}

func (x *RestoreFromBackupResponse) SetJobId(v string) {
	x.xxx_hidden_JobId = v
}

type RestoreFromBackupResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// job_id is the unique identifier for tracking this restore job
	JobId string
}

func (b0 RestoreFromBackupResponse_builder) Build() *RestoreFromBackupResponse {
	m0 := &RestoreFromBackupResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobId = b.JobId
	return m0
}

// GetBackupJobStatusRequest requests the status of a backup or restore job
type GetBackupJobStatusRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBackupJobStatusRequest) Reset() {
	*x = GetBackupJobStatusRequest{}
	mi := &file_multiadminservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupJobStatusRequest) ProtoMessage() {}

func (x *GetBackupJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBackupJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.xxx_hidden_JobId
	}
	return ""
}

func (x *GetBackupJobStatusRequest) SetJobId(v string) {
	x.xxx_hidden_JobId = v
}

type GetBackupJobStatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// job_id to query (required)
	JobId string
}

func (b0 GetBackupJobStatusRequest_builder) Build() *GetBackupJobStatusRequest {
	m0 := &GetBackupJobStatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobId = b.JobId
	return m0
}

// GetBackupJobStatusResponse contains the current status of a backup or restore job
type GetBackupJobStatusResponse struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3"`
	xxx_hidden_JobType           JobType                `protobuf:"varint,2,opt,name=job_type,json=jobType,proto3,enum=multiadmin.JobType"`
	xxx_hidden_Status            JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=multiadmin.JobStatus"`
	xxx_hidden_ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3"`
	xxx_hidden_Database          string                 `protobuf:"bytes,5,opt,name=database,proto3"`
	xxx_hidden_TableGroup        string                 `protobuf:"bytes,6,opt,name=table_group,json=tableGroup,proto3"`
	xxx_hidden_Shard             string                 `protobuf:"bytes,7,opt,name=shard,proto3"`
	xxx_hidden_BackupType        string                 `protobuf:"bytes,8,opt,name=backup_type,json=backupType,proto3"`
	xxx_hidden_ForcePrimary      bool                   `protobuf:"varint,9,opt,name=force_primary,json=forcePrimary,proto3"`
	xxx_hidden_RequestedBackupId string                 `protobuf:"bytes,10,opt,name=requested_backup_id,json=requestedBackupId,proto3"`
	xxx_hidden_BackupId          string                 `protobuf:"bytes,11,opt,name=backup_id,json=backupId,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *GetBackupJobStatusResponse) Reset() {
	*x = GetBackupJobStatusResponse{}
	mi := &file_multiadminservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupJobStatusResponse) ProtoMessage() {}

func (x *GetBackupJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBackupJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.xxx_hidden_JobId
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetJobType() JobType {
	if x != nil {
		return x.xxx_hidden_JobType
	}
	return JobType_JOB_TYPE_UNKNOWN
}

func (x *GetBackupJobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return JobStatus_JOB_STATUS_UNKNOWN
}

func (x *GetBackupJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.xxx_hidden_ErrorMessage
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetTableGroup() string {
	if x != nil {
		return x.xxx_hidden_TableGroup
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetBackupType() string {
	if x != nil {
		return x.xxx_hidden_BackupType
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetForcePrimary() bool {
	if x != nil {
		return x.xxx_hidden_ForcePrimary
	}
	return false
}

func (x *GetBackupJobStatusResponse) GetRequestedBackupId() string {
	if x != nil {
		return x.xxx_hidden_RequestedBackupId
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetBackupId() string {
	if x != nil {
		return x.xxx_hidden_BackupId
	}
	return ""
}

func (x *GetBackupJobStatusResponse) SetJobId(v string) {
	x.xxx_hidden_JobId = v
}

func (x *GetBackupJobStatusResponse) SetJobType(v JobType) {
	x.xxx_hidden_JobType = v
}

func (x *GetBackupJobStatusResponse) SetStatus(v JobStatus) {
	x.xxx_hidden_Status = v
}

func (x *GetBackupJobStatusResponse) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = v
}

func (x *GetBackupJobStatusResponse) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *GetBackupJobStatusResponse) SetTableGroup(v string) {
	x.xxx_hidden_TableGroup = v
}

func (x *GetBackupJobStatusResponse) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

func (x *GetBackupJobStatusResponse) SetBackupType(v string) {
	x.xxx_hidden_BackupType = v
}

func (x *GetBackupJobStatusResponse) SetForcePrimary(v bool) {
	x.xxx_hidden_ForcePrimary = v
}

func (x *GetBackupJobStatusResponse) SetRequestedBackupId(v string) {
	x.xxx_hidden_RequestedBackupId = v
}

func (x *GetBackupJobStatusResponse) SetBackupId(v string) {
	x.xxx_hidden_BackupId = v
}

type GetBackupJobStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// job_id is the unique identifier for this job
	JobId string
	// job_type indicates whether this is a backup or restore job
	JobType JobType
	// status indicates the current state of the job
	Status JobStatus
	// error_message contains the error if status is FAILED
	ErrorMessage string
	// Original request context
	Database   string
	TableGroup string
	Shard      string
	// For backup jobs
	BackupType   string
	ForcePrimary bool
	// For restore jobs
	RequestedBackupId string
	// Results (set when status = COMPLETED)
	// For backup: created backup_id
	// For restore: backup_id that was restored
	BackupId string
}

func (b0 GetBackupJobStatusResponse_builder) Build() *GetBackupJobStatusResponse {
	m0 := &GetBackupJobStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobId = b.JobId
	x.xxx_hidden_JobType = b.JobType
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_ErrorMessage = b.ErrorMessage
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_TableGroup = b.TableGroup
	x.xxx_hidden_Shard = b.Shard
	x.xxx_hidden_BackupType = b.BackupType
	x.xxx_hidden_ForcePrimary = b.ForcePrimary
	x.xxx_hidden_RequestedBackupId = b.RequestedBackupId
	x.xxx_hidden_BackupId = b.BackupId
	return m0
}

// GetBackupsRequest requests a list of backup artifacts with optional filtering
type GetBackupsRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Database   string                 `protobuf:"bytes,1,opt,name=database,proto3"`
	xxx_hidden_TableGroup string                 `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3"`
	xxx_hidden_Shard      string                 `protobuf:"bytes,3,opt,name=shard,proto3"`
	xxx_hidden_Limit      uint32                 `protobuf:"varint,4,opt,name=limit,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetBackupsRequest) Reset() {
	*x = GetBackupsRequest{}
	mi := &file_multiadminservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupsRequest) ProtoMessage() {}

func (x *GetBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBackupsRequest) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *GetBackupsRequest) GetTableGroup() string {
	if x != nil {
		return x.xxx_hidden_TableGroup
	}
	return ""
}

func (x *GetBackupsRequest) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *GetBackupsRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetBackupsRequest) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *GetBackupsRequest) SetTableGroup(v string) {
	x.xxx_hidden_TableGroup = v
}

func (x *GetBackupsRequest) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

func (x *GetBackupsRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
}

type GetBackupsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// database name to filter by (optional, empty means all databases)
	Database string
	// table_group name to filter by (optional, empty means all table groups)
	TableGroup string
	// shard name to filter by (optional, empty means all shards)
	Shard string
	// limit on number of results (optional, 0 means no limit)
	Limit uint32
}

func (b0 GetBackupsRequest_builder) Build() *GetBackupsRequest {
	m0 := &GetBackupsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_TableGroup = b.TableGroup
	x.xxx_hidden_Shard = b.Shard
	x.xxx_hidden_Limit = b.Limit
	return m0
}

// GetBackupsResponse contains the list of backup artifacts
type GetBackupsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Backups *[]*BackupInfo         `protobuf:"bytes,1,rep,name=backups,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetBackupsResponse) Reset() {
	*x = GetBackupsResponse{}
	mi := &file_multiadminservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupsResponse) ProtoMessage() {}

func (x *GetBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBackupsResponse) GetBackups() []*BackupInfo {
	if x != nil {
		if x.xxx_hidden_Backups != nil {
			return *x.xxx_hidden_Backups
		}
	}
	return nil
}

func (x *GetBackupsResponse) SetBackups(v []*BackupInfo) {
	x.xxx_hidden_Backups = &v
}

type GetBackupsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// backups is the list of backup information
	Backups []*BackupInfo
}

func (b0 GetBackupsResponse_builder) Build() *GetBackupsResponse {
	m0 := &GetBackupsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Backups = &b.Backups
	return m0
}

// BackupInfo contains information about a single backup artifact
type BackupInfo struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BackupId        string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3"`
	xxx_hidden_Database        string                 `protobuf:"bytes,2,opt,name=database,proto3"`
	xxx_hidden_TableGroup      string                 `protobuf:"bytes,3,opt,name=table_group,json=tableGroup,proto3"`
	xxx_hidden_Shard           string                 `protobuf:"bytes,4,opt,name=shard,proto3"`
	xxx_hidden_Type            string                 `protobuf:"bytes,5,opt,name=type,proto3"`
	xxx_hidden_Status          BackupStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=multiadmin.BackupStatus"`
	xxx_hidden_BackupTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=backup_time,json=backupTime,proto3"`
	xxx_hidden_BackupSizeBytes uint64                 `protobuf:"varint,8,opt,name=backup_size_bytes,json=backupSizeBytes,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BackupInfo) Reset() {
	*x = BackupInfo{}
	mi := &file_multiadminservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupInfo) ProtoMessage() {}

func (x *BackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BackupInfo) GetBackupId() string {
	if x != nil {
		return x.xxx_hidden_BackupId
	}
	return ""
}

func (x *BackupInfo) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *BackupInfo) GetTableGroup() string {
	if x != nil {
		return x.xxx_hidden_TableGroup
	}
	return ""
}

func (x *BackupInfo) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *BackupInfo) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *BackupInfo) GetStatus() BackupStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return BackupStatus_BACKUP_STATUS_UNKNOWN
}

func (x *BackupInfo) GetBackupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_BackupTime
	}
	return nil
}

func (x *BackupInfo) GetBackupSizeBytes() uint64 {
	if x != nil {
		return x.xxx_hidden_BackupSizeBytes
	}
	return 0
}

func (x *BackupInfo) SetBackupId(v string) {
	x.xxx_hidden_BackupId = v
}

func (x *BackupInfo) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *BackupInfo) SetTableGroup(v string) {
	x.xxx_hidden_TableGroup = v
}

func (x *BackupInfo) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

func (x *BackupInfo) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *BackupInfo) SetStatus(v BackupStatus) {
	x.xxx_hidden_Status = v
}

func (x *BackupInfo) SetBackupTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_BackupTime = v
}

func (x *BackupInfo) SetBackupSizeBytes(v uint64) {
	x.xxx_hidden_BackupSizeBytes = v
}

func (x *BackupInfo) HasBackupTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BackupTime != nil
}

func (x *BackupInfo) ClearBackupTime() {
	x.xxx_hidden_BackupTime = nil
}

type BackupInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// backup_id uniquely identifies this backup (e.g., "20250117-123456F")
	BackupId string
	// database name
	Database string
	// table_group name
	TableGroup string
	// shard name
	Shard string
	// type of backup: "full", "differential", or "incremental"
	Type string
	// status of the backup
	Status BackupStatus
	// backup_time is when the backup was created
	BackupTime *timestamppb.Timestamp
	// backup_size_bytes is the size of the backup in bytes
	BackupSizeBytes uint64
}

func (b0 BackupInfo_builder) Build() *BackupInfo {
	m0 := &BackupInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BackupId = b.BackupId
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_TableGroup = b.TableGroup
	x.xxx_hidden_Shard = b.Shard
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_BackupTime = b.BackupTime
	x.xxx_hidden_BackupSizeBytes = b.BackupSizeBytes
	return m0
}

var File_multiadminservice_proto protoreflect.FileDescriptor

const file_multiadminservice_proto_rawDesc = "" +
	"\n" +
	"\x17multiadminservice.proto\x12\n" +
	"multiadmin\x1a\x15clustermetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x0eGetCellRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x0fGetCellResponse\x12)\n" +
	"\x04cell\x18\x01 \x01(\v2\x15.clustermetadata.CellR\x04cell\"(\n" +
	"\x12GetDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x13GetDatabaseResponse\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.clustermetadata.DatabaseR\bdatabase\"\x15\n" +
	"\x13GetCellNamesRequest\",\n" +
	"\x14GetCellNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x19\n" +
	"\x17GetDatabaseNamesRequest\"0\n" +
	"\x18GetDatabaseNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"*\n" +
	"\x12GetGatewaysRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"P\n" +
	"\x13GetGatewaysResponse\x129\n" +
	"\bgateways\x18\x01 \x03(\v2\x1d.clustermetadata.MultiGatewayR\bgateways\"[\n" +
	"\x11GetPoolersRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\"L\n" +
	"\x12GetPoolersResponse\x126\n" +
	"\apoolers\x18\x01 \x03(\v2\x1c.clustermetadata.MultiPoolerR\apoolers\"'\n" +
	"\x0fGetOrchsRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"D\n" +
	"\x10GetOrchsResponse\x120\n" +
	"\x05orchs\x18\x01 \x03(\v2\x1a.clustermetadata.MultiOrchR\x05orchs\"\x9b\x01\n" +
	"\rBackupRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rforce_primary\x18\x05 \x01(\bR\fforcePrimary\"'\n" +
	"\x0eBackupResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8a\x01\n" +
	"\x18RestoreFromBackupRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x1b\n" +
	"\tbackup_id\x18\x04 \x01(\tR\bbackupId\"2\n" +
	"\x19RestoreFromBackupResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"2\n" +
	"\x19GetBackupJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9d\x03\n" +
	"\x1aGetBackupJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12.\n" +
	"\bjob_type\x18\x02 \x01(\x0e2\x13.multiadmin.JobTypeR\ajobType\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.multiadmin.JobStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x06 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\a \x01(\tR\x05shard\x12\x1f\n" +
	"\vbackup_type\x18\b \x01(\tR\n" +
	"backupType\x12#\n" +
	"\rforce_primary\x18\t \x01(\bR\fforcePrimary\x12.\n" +
	"\x13requested_backup_id\x18\n" +
	" \x01(\tR\x11requestedBackupId\x12\x1b\n" +
	"\tbackup_id\x18\v \x01(\tR\bbackupId\"|\n" +
	"\x11GetBackupsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"F\n" +
	"\x12GetBackupsResponse\x120\n" +
	"\abackups\x18\x01 \x03(\v2\x16.multiadmin.BackupInfoR\abackups\"\xab\x02\n" +
	"\n" +
	"BackupInfo\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x03 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x04 \x01(\tR\x05shard\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.multiadmin.BackupStatusR\x06status\x12;\n" +
	"\vbackup_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"backupTime\x12*\n" +
	"\x11backup_size_bytes\x18\b \x01(\x04R\x0fbackupSizeBytes*J\n" +
	"\aJobType\x12\x14\n" +
	"\x10JOB_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fJOB_TYPE_BACKUP\x10\x01\x12\x14\n" +
	"\x10JOB_TYPE_RESTORE\x10\x02*\x84\x01\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04*}\n" +
	"\fBackupStatus\x12\x19\n" +
	"\x15BACKUP_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18BACKUP_STATUS_INCOMPLETE\x10\x01\x12\x1a\n" +
	"\x16BACKUP_STATUS_COMPLETE\x10\x02\x12\x18\n" +
	"\x14BACKUP_STATUS_FAILED\x10\x032\x92\a\n" +
	"\x11MultiAdminService\x12B\n" +
	"\aGetCell\x12\x1a.multiadmin.GetCellRequest\x1a\x1b.multiadmin.GetCellResponse\x12N\n" +
	"\vGetDatabase\x12\x1e.multiadmin.GetDatabaseRequest\x1a\x1f.multiadmin.GetDatabaseResponse\x12Q\n" +
	"\fGetCellNames\x12\x1f.multiadmin.GetCellNamesRequest\x1a .multiadmin.GetCellNamesResponse\x12]\n" +
	"\x10GetDatabaseNames\x12#.multiadmin.GetDatabaseNamesRequest\x1a$.multiadmin.GetDatabaseNamesResponse\x12N\n" +
	"\vGetGateways\x12\x1e.multiadmin.GetGatewaysRequest\x1a\x1f.multiadmin.GetGatewaysResponse\x12K\n" +
	"\n" +
	"GetPoolers\x12\x1d.multiadmin.GetPoolersRequest\x1a\x1e.multiadmin.GetPoolersResponse\x12E\n" +
	"\bGetOrchs\x12\x1b.multiadmin.GetOrchsRequest\x1a\x1c.multiadmin.GetOrchsResponse\x12?\n" +
	"\x06Backup\x12\x19.multiadmin.BackupRequest\x1a\x1a.multiadmin.BackupResponse\x12`\n" +
	"\x11RestoreFromBackup\x12$.multiadmin.RestoreFromBackupRequest\x1a%.multiadmin.RestoreFromBackupResponse\x12c\n" +
	"\x12GetBackupJobStatus\x12%.multiadmin.GetBackupJobStatusRequest\x1a&.multiadmin.GetBackupJobStatusResponse\x12K\n" +
	"\n" +
	"GetBackups\x12\x1d.multiadmin.GetBackupsRequest\x1a\x1e.multiadmin.GetBackupsResponseB1Z/github.com/multigres/multigres/go/pb/multiadminb\x06proto3"

var file_multiadminservice_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_multiadminservice_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_multiadminservice_proto_goTypes = []any{
	(JobType)(0),                         // 0: multiadmin.JobType
	(JobStatus)(0),                       // 1: multiadmin.JobStatus
	(BackupStatus)(0),                    // 2: multiadmin.BackupStatus
	(*GetCellRequest)(nil),               // 3: multiadmin.GetCellRequest
	(*GetCellResponse)(nil),              // 4: multiadmin.GetCellResponse
	(*GetDatabaseRequest)(nil),           // 5: multiadmin.GetDatabaseRequest
	(*GetDatabaseResponse)(nil),          // 6: multiadmin.GetDatabaseResponse
	(*GetCellNamesRequest)(nil),          // 7: multiadmin.GetCellNamesRequest
	(*GetCellNamesResponse)(nil),         // 8: multiadmin.GetCellNamesResponse
	(*GetDatabaseNamesRequest)(nil),      // 9: multiadmin.GetDatabaseNamesRequest
	(*GetDatabaseNamesResponse)(nil),     // 10: multiadmin.GetDatabaseNamesResponse
	(*GetGatewaysRequest)(nil),           // 11: multiadmin.GetGatewaysRequest
	(*GetGatewaysResponse)(nil),          // 12: multiadmin.GetGatewaysResponse
	(*GetPoolersRequest)(nil),            // 13: multiadmin.GetPoolersRequest
	(*GetPoolersResponse)(nil),           // 14: multiadmin.GetPoolersResponse
	(*GetOrchsRequest)(nil),              // 15: multiadmin.GetOrchsRequest
	(*GetOrchsResponse)(nil),             // 16: multiadmin.GetOrchsResponse
	(*BackupRequest)(nil),                // 17: multiadmin.BackupRequest
	(*BackupResponse)(nil),               // 18: multiadmin.BackupResponse
	(*RestoreFromBackupRequest)(nil),     // 19: multiadmin.RestoreFromBackupRequest
	(*RestoreFromBackupResponse)(nil),    // 20: multiadmin.RestoreFromBackupResponse
	(*GetBackupJobStatusRequest)(nil),    // 21: multiadmin.GetBackupJobStatusRequest
	(*GetBackupJobStatusResponse)(nil),   // 22: multiadmin.GetBackupJobStatusResponse
	(*GetBackupsRequest)(nil),            // 23: multiadmin.GetBackupsRequest
	(*GetBackupsResponse)(nil),           // 24: multiadmin.GetBackupsResponse
	(*BackupInfo)(nil),                   // 25: multiadmin.BackupInfo
	(*clustermetadata.Cell)(nil),         // 26: clustermetadata.Cell
	(*clustermetadata.Database)(nil),     // 27: clustermetadata.Database
	(*clustermetadata.MultiGateway)(nil), // 28: clustermetadata.MultiGateway
	(*clustermetadata.MultiPooler)(nil),  // 29: clustermetadata.MultiPooler
	(*clustermetadata.MultiOrch)(nil),    // 30: clustermetadata.MultiOrch
	(*timestamppb.Timestamp)(nil),        // 31: google.protobuf.Timestamp
}
var file_multiadminservice_proto_depIdxs = []int32{
	26, // 0: multiadmin.GetCellResponse.cell:type_name -> clustermetadata.Cell
	27, // 1: multiadmin.GetDatabaseResponse.database:type_name -> clustermetadata.Database
	28, // 2: multiadmin.GetGatewaysResponse.gateways:type_name -> clustermetadata.MultiGateway
	29, // 3: multiadmin.GetPoolersResponse.poolers:type_name -> clustermetadata.MultiPooler
	30, // 4: multiadmin.GetOrchsResponse.orchs:type_name -> clustermetadata.MultiOrch
	0,  // 5: multiadmin.GetBackupJobStatusResponse.job_type:type_name -> multiadmin.JobType
	1,  // 6: multiadmin.GetBackupJobStatusResponse.status:type_name -> multiadmin.JobStatus
	25, // 7: multiadmin.GetBackupsResponse.backups:type_name -> multiadmin.BackupInfo
	2,  // 8: multiadmin.BackupInfo.status:type_name -> multiadmin.BackupStatus
	31, // 9: multiadmin.BackupInfo.backup_time:type_name -> google.protobuf.Timestamp
	3,  // 10: multiadmin.MultiAdminService.GetCell:input_type -> multiadmin.GetCellRequest
	5,  // 11: multiadmin.MultiAdminService.GetDatabase:input_type -> multiadmin.GetDatabaseRequest
	7,  // 12: multiadmin.MultiAdminService.GetCellNames:input_type -> multiadmin.GetCellNamesRequest
	9,  // 13: multiadmin.MultiAdminService.GetDatabaseNames:input_type -> multiadmin.GetDatabaseNamesRequest
	11, // 14: multiadmin.MultiAdminService.GetGateways:input_type -> multiadmin.GetGatewaysRequest
	13, // 15: multiadmin.MultiAdminService.GetPoolers:input_type -> multiadmin.GetPoolersRequest
	15, // 16: multiadmin.MultiAdminService.GetOrchs:input_type -> multiadmin.GetOrchsRequest
	17, // 17: multiadmin.MultiAdminService.Backup:input_type -> multiadmin.BackupRequest
	19, // 18: multiadmin.MultiAdminService.RestoreFromBackup:input_type -> multiadmin.RestoreFromBackupRequest
	21, // 19: multiadmin.MultiAdminService.GetBackupJobStatus:input_type -> multiadmin.GetBackupJobStatusRequest
	23, // 20: multiadmin.MultiAdminService.GetBackups:input_type -> multiadmin.GetBackupsRequest
	4,  // 21: multiadmin.MultiAdminService.GetCell:output_type -> multiadmin.GetCellResponse
	6,  // 22: multiadmin.MultiAdminService.GetDatabase:output_type -> multiadmin.GetDatabaseResponse
	8,  // 23: multiadmin.MultiAdminService.GetCellNames:output_type -> multiadmin.GetCellNamesResponse
	10, // 24: multiadmin.MultiAdminService.GetDatabaseNames:output_type -> multiadmin.GetDatabaseNamesResponse
	12, // 25: multiadmin.MultiAdminService.GetGateways:output_type -> multiadmin.GetGatewaysResponse
	14, // 26: multiadmin.MultiAdminService.GetPoolers:output_type -> multiadmin.GetPoolersResponse
	16, // 27: multiadmin.MultiAdminService.GetOrchs:output_type -> multiadmin.GetOrchsResponse
	18, // 28: multiadmin.MultiAdminService.Backup:output_type -> multiadmin.BackupResponse
	20, // 29: multiadmin.MultiAdminService.RestoreFromBackup:output_type -> multiadmin.RestoreFromBackupResponse
	22, // 30: multiadmin.MultiAdminService.GetBackupJobStatus:output_type -> multiadmin.GetBackupJobStatusResponse
	24, // 31: multiadmin.MultiAdminService.GetBackups:output_type -> multiadmin.GetBackupsResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_multiadminservice_proto_init() }
func file_multiadminservice_proto_init() {
	if File_multiadminservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiadminservice_proto_rawDesc), len(file_multiadminservice_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiadminservice_proto_goTypes,
		DependencyIndexes: file_multiadminservice_proto_depIdxs,
		EnumInfos:         file_multiadminservice_proto_enumTypes,
		MessageInfos:      file_multiadminservice_proto_msgTypes,
	}.Build()
	File_multiadminservice_proto = out.File
	file_multiadminservice_proto_goTypes = nil
	file_multiadminservice_proto_depIdxs = nil
}
