//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains data structures for query results in Multigres.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: query.proto

//go:build protoopaque

package query

import (
	reflect "reflect"
	unsafe "unsafe"

	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryResult represents the result of executing a query
type QueryResult struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fields       *[]*Field              `protobuf:"bytes,1,rep,name=fields,proto3"`
	xxx_hidden_RowsAffected uint64                 `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3"`
	xxx_hidden_Rows         *[]*Row                `protobuf:"bytes,3,rep,name=rows,proto3"`
	xxx_hidden_CommandTag   string                 `protobuf:"bytes,4,opt,name=command_tag,json=commandTag,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryResult) GetFields() []*Field {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *QueryResult) GetRowsAffected() uint64 {
	if x != nil {
		return x.xxx_hidden_RowsAffected
	}
	return 0
}

func (x *QueryResult) GetRows() []*Row {
	if x != nil {
		if x.xxx_hidden_Rows != nil {
			return *x.xxx_hidden_Rows
		}
	}
	return nil
}

func (x *QueryResult) GetCommandTag() string {
	if x != nil {
		return x.xxx_hidden_CommandTag
	}
	return ""
}

func (x *QueryResult) SetFields(v []*Field) {
	x.xxx_hidden_Fields = &v
}

func (x *QueryResult) SetRowsAffected(v uint64) {
	x.xxx_hidden_RowsAffected = v
}

func (x *QueryResult) SetRows(v []*Row) {
	x.xxx_hidden_Rows = &v
}

func (x *QueryResult) SetCommandTag(v string) {
	x.xxx_hidden_CommandTag = v
}

type QueryResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// fields describes the columns in the result set (nil if no rows returned)
	Fields []*Field
	// rows_affected is the number of rows affected (INSERT, UPDATE, DELETE, etc.)
	RowsAffected uint64
	// rows contains the actual data rows
	Rows []*Row
	// command_tag is the PostgreSQL command tag for this result set.
	// When streaming results, this should only be set on the final packet of a result set.
	// When set, the protocol layer will send CommandComplete and reset state for the next result set.
	// Examples: "SELECT 42", "INSERT 0 5", "UPDATE 10", "DELETE 3", "CREATE TABLE"
	CommandTag string
}

func (b0 QueryResult_builder) Build() *QueryResult {
	m0 := &QueryResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Fields = &b.Fields
	x.xxx_hidden_RowsAffected = b.RowsAffected
	x.xxx_hidden_Rows = &b.Rows
	x.xxx_hidden_CommandTag = b.CommandTag
	return m0
}

// Field represents metadata about a column in the result set.
// This includes all PostgreSQL wire protocol metadata needed for RowDescription messages.
type Field struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3"`
	xxx_hidden_TableOid             uint32                 `protobuf:"varint,3,opt,name=table_oid,json=tableOid,proto3"`
	xxx_hidden_TableAttributeNumber int32                  `protobuf:"varint,4,opt,name=table_attribute_number,json=tableAttributeNumber,proto3"`
	xxx_hidden_DataTypeOid          uint32                 `protobuf:"varint,5,opt,name=data_type_oid,json=dataTypeOid,proto3"`
	xxx_hidden_DataTypeSize         int32                  `protobuf:"varint,6,opt,name=data_type_size,json=dataTypeSize,proto3"`
	xxx_hidden_TypeModifier         int32                  `protobuf:"varint,7,opt,name=type_modifier,json=typeModifier,proto3"`
	xxx_hidden_Format               int32                  `protobuf:"varint,8,opt,name=format,proto3"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Field) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *Field) GetTableOid() uint32 {
	if x != nil {
		return x.xxx_hidden_TableOid
	}
	return 0
}

func (x *Field) GetTableAttributeNumber() int32 {
	if x != nil {
		return x.xxx_hidden_TableAttributeNumber
	}
	return 0
}

func (x *Field) GetDataTypeOid() uint32 {
	if x != nil {
		return x.xxx_hidden_DataTypeOid
	}
	return 0
}

func (x *Field) GetDataTypeSize() int32 {
	if x != nil {
		return x.xxx_hidden_DataTypeSize
	}
	return 0
}

func (x *Field) GetTypeModifier() int32 {
	if x != nil {
		return x.xxx_hidden_TypeModifier
	}
	return 0
}

func (x *Field) GetFormat() int32 {
	if x != nil {
		return x.xxx_hidden_Format
	}
	return 0
}

func (x *Field) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Field) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *Field) SetTableOid(v uint32) {
	x.xxx_hidden_TableOid = v
}

func (x *Field) SetTableAttributeNumber(v int32) {
	x.xxx_hidden_TableAttributeNumber = v
}

func (x *Field) SetDataTypeOid(v uint32) {
	x.xxx_hidden_DataTypeOid = v
}

func (x *Field) SetDataTypeSize(v int32) {
	x.xxx_hidden_DataTypeSize = v
}

func (x *Field) SetTypeModifier(v int32) {
	x.xxx_hidden_TypeModifier = v
}

func (x *Field) SetFormat(v int32) {
	x.xxx_hidden_Format = v
}

type Field_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name is the column name
	Name string
	// type is a human-readable type name (for logging/debugging)
	Type string
	// table_oid is the object ID of the table (0 if not a table column)
	TableOid uint32
	// table_attribute_number is the column number in the table (0 if not a table column)
	TableAttributeNumber int32
	// data_type_oid is the object ID of the data type
	DataTypeOid uint32
	// data_type_size is the size of the data type (-1 for variable length)
	DataTypeSize int32
	// type_modifier is the type modifier (-1 for no modifier)
	TypeModifier int32
	// format is the format code (0=text, 1=binary)
	Format int32
}

func (b0 Field_builder) Build() *Field {
	m0 := &Field{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_TableOid = b.TableOid
	x.xxx_hidden_TableAttributeNumber = b.TableAttributeNumber
	x.xxx_hidden_DataTypeOid = b.DataTypeOid
	x.xxx_hidden_DataTypeSize = b.DataTypeSize
	x.xxx_hidden_TypeModifier = b.TypeModifier
	x.xxx_hidden_Format = b.Format
	return m0
}

// Row represents a single row of data in the result set.
// Each value is represented as bytes (can be NULL).
type Row struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values [][]byte               `protobuf:"bytes,1,rep,name=values,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Row) GetValues() [][]byte {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *Row) SetValues(v [][]byte) {
	x.xxx_hidden_Values = v
}

type Row_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// values contains the column values (nil entry for NULL)
	Values [][]byte
}

func (b0 Row_builder) Build() *Row {
	m0 := &Row{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

// StatementDescription describes a prepared statement or portal.
// Used for the Describe message ('D') response in the extended query protocol.
type StatementDescription struct {
	state                 protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Parameters *[]*ParameterDescription `protobuf:"bytes,1,rep,name=parameters,proto3"`
	xxx_hidden_Fields     *[]*Field                `protobuf:"bytes,2,rep,name=fields,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatementDescription) Reset() {
	*x = StatementDescription{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatementDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementDescription) ProtoMessage() {}

func (x *StatementDescription) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatementDescription) GetParameters() []*ParameterDescription {
	if x != nil {
		if x.xxx_hidden_Parameters != nil {
			return *x.xxx_hidden_Parameters
		}
	}
	return nil
}

func (x *StatementDescription) GetFields() []*Field {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *StatementDescription) SetParameters(v []*ParameterDescription) {
	x.xxx_hidden_Parameters = &v
}

func (x *StatementDescription) SetFields(v []*Field) {
	x.xxx_hidden_Fields = &v
}

type StatementDescription_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// parameters describes the parameters of the statement (for statement describe)
	// Nil for portal describe.
	Parameters []*ParameterDescription
	// fields describes the result columns
	// Nil if the statement doesn't return rows.
	Fields []*Field
}

func (b0 StatementDescription_builder) Build() *StatementDescription {
	m0 := &StatementDescription{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Parameters = &b.Parameters
	x.xxx_hidden_Fields = &b.Fields
	return m0
}

// ParameterDescription describes a parameter in a prepared statement.
type ParameterDescription struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DataTypeOid uint32                 `protobuf:"varint,1,opt,name=data_type_oid,json=dataTypeOid,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ParameterDescription) Reset() {
	*x = ParameterDescription{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDescription) ProtoMessage() {}

func (x *ParameterDescription) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ParameterDescription) GetDataTypeOid() uint32 {
	if x != nil {
		return x.xxx_hidden_DataTypeOid
	}
	return 0
}

func (x *ParameterDescription) SetDataTypeOid(v uint32) {
	x.xxx_hidden_DataTypeOid = v
}

type ParameterDescription_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// data_type_oid is the OID of the parameter's data type
	DataTypeOid uint32
}

func (b0 ParameterDescription_builder) Build() *ParameterDescription {
	m0 := &ParameterDescription{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DataTypeOid = b.DataTypeOid
	return m0
}

// Target identifies the target for query execution.
// It specifies which tablegroup, shard, and pooler type to route the query to.
// - Route to PRIMARY for writes
// - Route to REPLICA for reads
// - Route to specific shards (future)
type Target struct {
	state                 protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_TableGroup string                     `protobuf:"bytes,1,opt,name=table_group,json=tableGroup,proto3"`
	xxx_hidden_Shard      string                     `protobuf:"bytes,2,opt,name=shard,proto3"`
	xxx_hidden_PoolerType clustermetadata.PoolerType `protobuf:"varint,3,opt,name=pooler_type,json=poolerType,proto3,enum=clustermetadata.PoolerType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Target) GetTableGroup() string {
	if x != nil {
		return x.xxx_hidden_TableGroup
	}
	return ""
}

func (x *Target) GetShard() string {
	if x != nil {
		return x.xxx_hidden_Shard
	}
	return ""
}

func (x *Target) GetPoolerType() clustermetadata.PoolerType {
	if x != nil {
		return x.xxx_hidden_PoolerType
	}
	return clustermetadata.PoolerType(0)
}

func (x *Target) SetTableGroup(v string) {
	x.xxx_hidden_TableGroup = v
}

func (x *Target) SetShard(v string) {
	x.xxx_hidden_Shard = v
}

func (x *Target) SetPoolerType(v clustermetadata.PoolerType) {
	x.xxx_hidden_PoolerType = v
}

type Target_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// table_group is the target tablegroup name
	TableGroup string
	// shard is the target shard name (empty for unsharded or to route to any shard)
	Shard string
	// pooler_type is the type of pooler to route to (PRIMARY, REPLICA)
	// If not specified (UNKNOWN), defaults to PRIMARY
	PoolerType clustermetadata.PoolerType
}

func (b0 Target_builder) Build() *Target {
	m0 := &Target{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TableGroup = b.TableGroup
	x.xxx_hidden_Shard = b.Shard
	x.xxx_hidden_PoolerType = b.PoolerType
	return m0
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x05query\x1a\x15clustermetadata.proto\"\x99\x01\n" +
	"\vQueryResult\x12$\n" +
	"\x06fields\x18\x01 \x03(\v2\f.query.FieldR\x06fields\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x04R\frowsAffected\x12\x1e\n" +
	"\x04rows\x18\x03 \x03(\v2\n" +
	".query.RowR\x04rows\x12\x1f\n" +
	"\vcommand_tag\x18\x04 \x01(\tR\n" +
	"commandTag\"\x89\x02\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttable_oid\x18\x03 \x01(\rR\btableOid\x124\n" +
	"\x16table_attribute_number\x18\x04 \x01(\x05R\x14tableAttributeNumber\x12\"\n" +
	"\rdata_type_oid\x18\x05 \x01(\rR\vdataTypeOid\x12$\n" +
	"\x0edata_type_size\x18\x06 \x01(\x05R\fdataTypeSize\x12#\n" +
	"\rtype_modifier\x18\a \x01(\x05R\ftypeModifier\x12\x16\n" +
	"\x06format\x18\b \x01(\x05R\x06format\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"y\n" +
	"\x14StatementDescription\x12;\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1b.query.ParameterDescriptionR\n" +
	"parameters\x12$\n" +
	"\x06fields\x18\x02 \x03(\v2\f.query.FieldR\x06fields\":\n" +
	"\x14ParameterDescription\x12\"\n" +
	"\rdata_type_oid\x18\x01 \x01(\rR\vdataTypeOid\"}\n" +
	"\x06Target\x12\x1f\n" +
	"\vtable_group\x18\x01 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\tR\x05shard\x12<\n" +
	"\vpooler_type\x18\x03 \x01(\x0e2\x1b.clustermetadata.PoolerTypeR\n" +
	"poolerTypeB,Z*github.com/multigres/multigres/go/pb/queryb\x06proto3"

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_query_proto_goTypes = []any{
	(*QueryResult)(nil),             // 0: query.QueryResult
	(*Field)(nil),                   // 1: query.Field
	(*Row)(nil),                     // 2: query.Row
	(*StatementDescription)(nil),    // 3: query.StatementDescription
	(*ParameterDescription)(nil),    // 4: query.ParameterDescription
	(*Target)(nil),                  // 5: query.Target
	(clustermetadata.PoolerType)(0), // 6: clustermetadata.PoolerType
}
var file_query_proto_depIdxs = []int32{
	1, // 0: query.QueryResult.fields:type_name -> query.Field
	2, // 1: query.QueryResult.rows:type_name -> query.Row
	4, // 2: query.StatementDescription.parameters:type_name -> query.ParameterDescription
	1, // 3: query.StatementDescription.fields:type_name -> query.Field
	6, // 4: query.Target.pooler_type:type_name -> clustermetadata.PoolerType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
