// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusservice.proto

package consensus

import (
	consensusdata "github.com/multigres/multigres/go/pb/consensusdata"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_consensusservice_proto protoreflect.FileDescriptor

const file_consensusservice_proto_rawDesc = "" +
	"\n" +
	"\x16consensusservice.proto\x12\tconsensus\x1a\x13consensusdata.proto\x1a\x1cmultipoolermanagerdata.proto2\xbf\x04\n" +
	"\x14MultiPoolerConsensus\x12H\n" +
	"\aRecruit\x12\x1d.consensusdata.RecruitRequest\x1a\x1e.consensusdata.RecruitResponse\x12H\n" +
	"\aPropose\x12\x1d.consensusdata.ProposeRequest\x1a\x1e.consensusdata.ProposeResponse\x12E\n" +
	"\x06Inform\x12\x1c.consensusdata.InformRequest\x1a\x1d.consensusdata.InformResponse\x12E\n" +
	"\x06Status\x12\x1c.consensusdata.StatusRequest\x1a\x1d.consensusdata.StatusResponse\x12r\n" +
	"\x0fEmergencyDemote\x12..multipoolermanagerdata.EmergencyDemoteRequest\x1a/.multipoolermanagerdata.EmergencyDemoteResponse\x12\x90\x01\n" +
	"\x13UpdateConsensusRule\x12;.multipoolermanagerdata.UpdateSynchronousStandbyListRequest\x1a<.multipoolermanagerdata.UpdateSynchronousStandbyListResponseB0Z.github.com/multigres/multigres/go/pb/consensusb\x06proto3"

var file_consensusservice_proto_goTypes = []any{
	(*consensusdata.RecruitRequest)(nil),                                // 0: consensusdata.RecruitRequest
	(*consensusdata.ProposeRequest)(nil),                                // 1: consensusdata.ProposeRequest
	(*consensusdata.InformRequest)(nil),                                 // 2: consensusdata.InformRequest
	(*consensusdata.StatusRequest)(nil),                                 // 3: consensusdata.StatusRequest
	(*multipoolermanagerdata.EmergencyDemoteRequest)(nil),               // 4: multipoolermanagerdata.EmergencyDemoteRequest
	(*multipoolermanagerdata.UpdateSynchronousStandbyListRequest)(nil),  // 5: multipoolermanagerdata.UpdateSynchronousStandbyListRequest
	(*consensusdata.RecruitResponse)(nil),                               // 6: consensusdata.RecruitResponse
	(*consensusdata.ProposeResponse)(nil),                               // 7: consensusdata.ProposeResponse
	(*consensusdata.InformResponse)(nil),                                // 8: consensusdata.InformResponse
	(*consensusdata.StatusResponse)(nil),                                // 9: consensusdata.StatusResponse
	(*multipoolermanagerdata.EmergencyDemoteResponse)(nil),              // 10: multipoolermanagerdata.EmergencyDemoteResponse
	(*multipoolermanagerdata.UpdateSynchronousStandbyListResponse)(nil), // 11: multipoolermanagerdata.UpdateSynchronousStandbyListResponse
}
var file_consensusservice_proto_depIdxs = []int32{
	0,  // 0: consensus.MultiPoolerConsensus.Recruit:input_type -> consensusdata.RecruitRequest
	1,  // 1: consensus.MultiPoolerConsensus.Propose:input_type -> consensusdata.ProposeRequest
	2,  // 2: consensus.MultiPoolerConsensus.Inform:input_type -> consensusdata.InformRequest
	3,  // 3: consensus.MultiPoolerConsensus.Status:input_type -> consensusdata.StatusRequest
	4,  // 4: consensus.MultiPoolerConsensus.EmergencyDemote:input_type -> multipoolermanagerdata.EmergencyDemoteRequest
	5,  // 5: consensus.MultiPoolerConsensus.UpdateConsensusRule:input_type -> multipoolermanagerdata.UpdateSynchronousStandbyListRequest
	6,  // 6: consensus.MultiPoolerConsensus.Recruit:output_type -> consensusdata.RecruitResponse
	7,  // 7: consensus.MultiPoolerConsensus.Propose:output_type -> consensusdata.ProposeResponse
	8,  // 8: consensus.MultiPoolerConsensus.Inform:output_type -> consensusdata.InformResponse
	9,  // 9: consensus.MultiPoolerConsensus.Status:output_type -> consensusdata.StatusResponse
	10, // 10: consensus.MultiPoolerConsensus.EmergencyDemote:output_type -> multipoolermanagerdata.EmergencyDemoteResponse
	11, // 11: consensus.MultiPoolerConsensus.UpdateConsensusRule:output_type -> multipoolermanagerdata.UpdateSynchronousStandbyListResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_consensusservice_proto_init() }
func file_consensusservice_proto_init() {
	if File_consensusservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusservice_proto_rawDesc), len(file_consensusservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensusservice_proto_goTypes,
		DependencyIndexes: file_consensusservice_proto_depIdxs,
	}.Build()
	File_consensusservice_proto = out.File
	file_consensusservice_proto_goTypes = nil
	file_consensusservice_proto_depIdxs = nil
}
