// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: consensusservice.proto

package consensus

import (
	context "context"
	consensusdata "github.com/multigres/multigres/go/pb/consensusdata"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiPoolerConsensus_Recruit_FullMethodName             = "/consensus.MultiPoolerConsensus/Recruit"
	MultiPoolerConsensus_Propose_FullMethodName             = "/consensus.MultiPoolerConsensus/Propose"
	MultiPoolerConsensus_Inform_FullMethodName              = "/consensus.MultiPoolerConsensus/Inform"
	MultiPoolerConsensus_Status_FullMethodName              = "/consensus.MultiPoolerConsensus/Status"
	MultiPoolerConsensus_EmergencyDemote_FullMethodName     = "/consensus.MultiPoolerConsensus/EmergencyDemote"
	MultiPoolerConsensus_UpdateConsensusRule_FullMethodName = "/consensus.MultiPoolerConsensus/UpdateConsensusRule"
)

// MultiPoolerConsensusClient is the client API for MultiPoolerConsensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiPoolerConsensus provides consensus APIs for leader election and HA operations.
type MultiPoolerConsensusClient interface {
	// Recruit initiates a new leadership term by asking poolers to revoke
	// participation in all prior terms. The pooler accepts the TermRevocation
	// if its revoked_below_term is >= its current, then freezes WAL positions
	// (demotes primary or pauses standby replication). The coordinator collects
	// responses to identify the most-progressed candidate.
	Recruit(ctx context.Context, in *consensusdata.RecruitRequest, opts ...grpc.CallOption) (*consensusdata.RecruitResponse, error)
	// Propose is sent to all poolers after sufficient recruitment to establish
	// a new primary. Each pooler self-identifies via proposal.proposal_leader_id:
	//   - The proposal leader promotes to primary, configures sync replication,
	//     and writes rule history.
	//   - All other poolers set primary_conninfo to the proposal leader and
	//     resume replication.
	Propose(ctx context.Context, in *consensusdata.ProposeRequest, opts ...grpc.CallOption) (*consensusdata.ProposeResponse, error)
	// Inform notifies all poolers of a committed shard rule decision. No authority
	// proof is required. Sets highest_known_decision in each pooler's ConsensusStatus.
	Inform(ctx context.Context, in *consensusdata.InformRequest, opts ...grpc.CallOption) (*consensusdata.InformResponse, error)
	// Status provides the current status of the consensus service, including
	// the pooler's term revocation, WAL position, and role. Used by MultiOrch
	// to monitor the cluster and detect failover conditions.
	Status(ctx context.Context, in *consensusdata.StatusRequest, opts ...grpc.CallOption) (*consensusdata.StatusResponse, error)
	// EmergencyDemote self-demotes a primary that has detected it should no
	// longer be serving writes. Not a consensus operation: the pooler restarts
	// as a standby and signals the coordinator via AvailabilityStatus that it
	// has resigned. The coordinator then drives recovery via Recruit/Propose/Inform.
	EmergencyDemote(ctx context.Context, in *multipoolermanagerdata.EmergencyDemoteRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.EmergencyDemoteResponse, error)
	// UpdateConsensusRule updates the synchronous standby list (quorum membership).
	UpdateConsensusRule(ctx context.Context, in *multipoolermanagerdata.UpdateSynchronousStandbyListRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.UpdateSynchronousStandbyListResponse, error)
}

type multiPoolerConsensusClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiPoolerConsensusClient(cc grpc.ClientConnInterface) MultiPoolerConsensusClient {
	return &multiPoolerConsensusClient{cc}
}

func (c *multiPoolerConsensusClient) Recruit(ctx context.Context, in *consensusdata.RecruitRequest, opts ...grpc.CallOption) (*consensusdata.RecruitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.RecruitResponse)
	err := c.cc.Invoke(ctx, MultiPoolerConsensus_Recruit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerConsensusClient) Propose(ctx context.Context, in *consensusdata.ProposeRequest, opts ...grpc.CallOption) (*consensusdata.ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.ProposeResponse)
	err := c.cc.Invoke(ctx, MultiPoolerConsensus_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerConsensusClient) Inform(ctx context.Context, in *consensusdata.InformRequest, opts ...grpc.CallOption) (*consensusdata.InformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.InformResponse)
	err := c.cc.Invoke(ctx, MultiPoolerConsensus_Inform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerConsensusClient) Status(ctx context.Context, in *consensusdata.StatusRequest, opts ...grpc.CallOption) (*consensusdata.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(consensusdata.StatusResponse)
	err := c.cc.Invoke(ctx, MultiPoolerConsensus_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerConsensusClient) EmergencyDemote(ctx context.Context, in *multipoolermanagerdata.EmergencyDemoteRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.EmergencyDemoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.EmergencyDemoteResponse)
	err := c.cc.Invoke(ctx, MultiPoolerConsensus_EmergencyDemote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerConsensusClient) UpdateConsensusRule(ctx context.Context, in *multipoolermanagerdata.UpdateSynchronousStandbyListRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.UpdateSynchronousStandbyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(multipoolermanagerdata.UpdateSynchronousStandbyListResponse)
	err := c.cc.Invoke(ctx, MultiPoolerConsensus_UpdateConsensusRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiPoolerConsensusServer is the server API for MultiPoolerConsensus service.
// All implementations must embed UnimplementedMultiPoolerConsensusServer
// for forward compatibility.
//
// MultiPoolerConsensus provides consensus APIs for leader election and HA operations.
type MultiPoolerConsensusServer interface {
	// Recruit initiates a new leadership term by asking poolers to revoke
	// participation in all prior terms. The pooler accepts the TermRevocation
	// if its revoked_below_term is >= its current, then freezes WAL positions
	// (demotes primary or pauses standby replication). The coordinator collects
	// responses to identify the most-progressed candidate.
	Recruit(context.Context, *consensusdata.RecruitRequest) (*consensusdata.RecruitResponse, error)
	// Propose is sent to all poolers after sufficient recruitment to establish
	// a new primary. Each pooler self-identifies via proposal.proposal_leader_id:
	//   - The proposal leader promotes to primary, configures sync replication,
	//     and writes rule history.
	//   - All other poolers set primary_conninfo to the proposal leader and
	//     resume replication.
	Propose(context.Context, *consensusdata.ProposeRequest) (*consensusdata.ProposeResponse, error)
	// Inform notifies all poolers of a committed shard rule decision. No authority
	// proof is required. Sets highest_known_decision in each pooler's ConsensusStatus.
	Inform(context.Context, *consensusdata.InformRequest) (*consensusdata.InformResponse, error)
	// Status provides the current status of the consensus service, including
	// the pooler's term revocation, WAL position, and role. Used by MultiOrch
	// to monitor the cluster and detect failover conditions.
	Status(context.Context, *consensusdata.StatusRequest) (*consensusdata.StatusResponse, error)
	// EmergencyDemote self-demotes a primary that has detected it should no
	// longer be serving writes. Not a consensus operation: the pooler restarts
	// as a standby and signals the coordinator via AvailabilityStatus that it
	// has resigned. The coordinator then drives recovery via Recruit/Propose/Inform.
	EmergencyDemote(context.Context, *multipoolermanagerdata.EmergencyDemoteRequest) (*multipoolermanagerdata.EmergencyDemoteResponse, error)
	// UpdateConsensusRule updates the synchronous standby list (quorum membership).
	UpdateConsensusRule(context.Context, *multipoolermanagerdata.UpdateSynchronousStandbyListRequest) (*multipoolermanagerdata.UpdateSynchronousStandbyListResponse, error)
	mustEmbedUnimplementedMultiPoolerConsensusServer()
}

// UnimplementedMultiPoolerConsensusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiPoolerConsensusServer struct{}

func (UnimplementedMultiPoolerConsensusServer) Recruit(context.Context, *consensusdata.RecruitRequest) (*consensusdata.RecruitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recruit not implemented")
}
func (UnimplementedMultiPoolerConsensusServer) Propose(context.Context, *consensusdata.ProposeRequest) (*consensusdata.ProposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedMultiPoolerConsensusServer) Inform(context.Context, *consensusdata.InformRequest) (*consensusdata.InformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inform not implemented")
}
func (UnimplementedMultiPoolerConsensusServer) Status(context.Context, *consensusdata.StatusRequest) (*consensusdata.StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMultiPoolerConsensusServer) EmergencyDemote(context.Context, *multipoolermanagerdata.EmergencyDemoteRequest) (*multipoolermanagerdata.EmergencyDemoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyDemote not implemented")
}
func (UnimplementedMultiPoolerConsensusServer) UpdateConsensusRule(context.Context, *multipoolermanagerdata.UpdateSynchronousStandbyListRequest) (*multipoolermanagerdata.UpdateSynchronousStandbyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConsensusRule not implemented")
}
func (UnimplementedMultiPoolerConsensusServer) mustEmbedUnimplementedMultiPoolerConsensusServer() {}
func (UnimplementedMultiPoolerConsensusServer) testEmbeddedByValue()                              {}

// UnsafeMultiPoolerConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiPoolerConsensusServer will
// result in compilation errors.
type UnsafeMultiPoolerConsensusServer interface {
	mustEmbedUnimplementedMultiPoolerConsensusServer()
}

func RegisterMultiPoolerConsensusServer(s grpc.ServiceRegistrar, srv MultiPoolerConsensusServer) {
	// If the following call pancis, it indicates UnimplementedMultiPoolerConsensusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiPoolerConsensus_ServiceDesc, srv)
}

func _MultiPoolerConsensus_Recruit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.RecruitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerConsensusServer).Recruit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerConsensus_Recruit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerConsensusServer).Recruit(ctx, req.(*consensusdata.RecruitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerConsensus_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerConsensusServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerConsensus_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerConsensusServer).Propose(ctx, req.(*consensusdata.ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerConsensus_Inform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.InformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerConsensusServer).Inform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerConsensus_Inform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerConsensusServer).Inform(ctx, req.(*consensusdata.InformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerConsensus_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(consensusdata.StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerConsensusServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerConsensus_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerConsensusServer).Status(ctx, req.(*consensusdata.StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerConsensus_EmergencyDemote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.EmergencyDemoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerConsensusServer).EmergencyDemote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerConsensus_EmergencyDemote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerConsensusServer).EmergencyDemote(ctx, req.(*multipoolermanagerdata.EmergencyDemoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerConsensus_UpdateConsensusRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(multipoolermanagerdata.UpdateSynchronousStandbyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerConsensusServer).UpdateConsensusRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerConsensus_UpdateConsensusRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerConsensusServer).UpdateConsensusRule(ctx, req.(*multipoolermanagerdata.UpdateSynchronousStandbyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiPoolerConsensus_ServiceDesc is the grpc.ServiceDesc for MultiPoolerConsensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiPoolerConsensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consensus.MultiPoolerConsensus",
	HandlerType: (*MultiPoolerConsensusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recruit",
			Handler:    _MultiPoolerConsensus_Recruit_Handler,
		},
		{
			MethodName: "Propose",
			Handler:    _MultiPoolerConsensus_Propose_Handler,
		},
		{
			MethodName: "Inform",
			Handler:    _MultiPoolerConsensus_Inform_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MultiPoolerConsensus_Status_Handler,
		},
		{
			MethodName: "EmergencyDemote",
			Handler:    _MultiPoolerConsensus_EmergencyDemote_Handler,
		},
		{
			MethodName: "UpdateConsensusRule",
			Handler:    _MultiPoolerConsensus_UpdateConsensusRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consensusservice.proto",
}
