// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: grpcfaultproxyservice.proto

package grpcfaultproxyservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FaultRule defines a single fault injection rule.
type FaultRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                         // Service name or "*" for all
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`                         // Target service or "*" for all
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                         // gRPC method pattern or "*" for all
	FaultType     string                 `protobuf:"bytes,5,opt,name=fault_type,json=faultType,proto3" json:"fault_type,omitempty"`  // "latency", "error", "drop"
	Probability   float64                `protobuf:"fixed64,6,opt,name=probability,proto3" json:"probability,omitempty"`             // 0.0 to 1.0
	LatencyMs     int32                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // For latency faults
	ErrorCode     int32                  `protobuf:"varint,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // gRPC status code for error faults
	ErrorMsg      string                 `protobuf:"bytes,9,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // Error message for error faults
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultRule) Reset() {
	*x = FaultRule{}
	mi := &file_grpcfaultproxyservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultRule) ProtoMessage() {}

func (x *FaultRule) ProtoReflect() protoreflect.Message {
	mi := &file_grpcfaultproxyservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultRule.ProtoReflect.Descriptor instead.
func (*FaultRule) Descriptor() ([]byte, []int) {
	return file_grpcfaultproxyservice_proto_rawDescGZIP(), []int{0}
}

func (x *FaultRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FaultRule) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FaultRule) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FaultRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FaultRule) GetFaultType() string {
	if x != nil {
		return x.FaultType
	}
	return ""
}

func (x *FaultRule) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *FaultRule) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *FaultRule) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *FaultRule) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type SetRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*FaultRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRulesRequest) Reset() {
	*x = SetRulesRequest{}
	mi := &file_grpcfaultproxyservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRulesRequest) ProtoMessage() {}

func (x *SetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcfaultproxyservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRulesRequest.ProtoReflect.Descriptor instead.
func (*SetRulesRequest) Descriptor() ([]byte, []int) {
	return file_grpcfaultproxyservice_proto_rawDescGZIP(), []int{1}
}

func (x *SetRulesRequest) GetRules() []*FaultRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SetRulesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of rules successfully installed
	RulesCount    int32 `protobuf:"varint,1,opt,name=rules_count,json=rulesCount,proto3" json:"rules_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRulesResponse) Reset() {
	*x = SetRulesResponse{}
	mi := &file_grpcfaultproxyservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRulesResponse) ProtoMessage() {}

func (x *SetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcfaultproxyservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRulesResponse.ProtoReflect.Descriptor instead.
func (*SetRulesResponse) Descriptor() ([]byte, []int) {
	return file_grpcfaultproxyservice_proto_rawDescGZIP(), []int{2}
}

func (x *SetRulesResponse) GetRulesCount() int32 {
	if x != nil {
		return x.RulesCount
	}
	return 0
}

type GetRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesRequest) Reset() {
	*x = GetRulesRequest{}
	mi := &file_grpcfaultproxyservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRequest) ProtoMessage() {}

func (x *GetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcfaultproxyservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRequest.ProtoReflect.Descriptor instead.
func (*GetRulesRequest) Descriptor() ([]byte, []int) {
	return file_grpcfaultproxyservice_proto_rawDescGZIP(), []int{3}
}

type GetRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*FaultRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesResponse) Reset() {
	*x = GetRulesResponse{}
	mi := &file_grpcfaultproxyservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesResponse) ProtoMessage() {}

func (x *GetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcfaultproxyservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesResponse.ProtoReflect.Descriptor instead.
func (*GetRulesResponse) Descriptor() ([]byte, []int) {
	return file_grpcfaultproxyservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetRulesResponse) GetRules() []*FaultRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_grpcfaultproxyservice_proto protoreflect.FileDescriptor

const file_grpcfaultproxyservice_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpcfaultproxyservice.proto\x12\x15grpcfaultproxyservice\"\x83\x02\n" +
	"\tFaultRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"fault_type\x18\x05 \x01(\tR\tfaultType\x12 \n" +
	"\vprobability\x18\x06 \x01(\x01R\vprobability\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\x05R\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\t \x01(\tR\berrorMsg\"I\n" +
	"\x0fSetRulesRequest\x126\n" +
	"\x05rules\x18\x01 \x03(\v2 .grpcfaultproxyservice.FaultRuleR\x05rules\"3\n" +
	"\x10SetRulesResponse\x12\x1f\n" +
	"\vrules_count\x18\x01 \x01(\x05R\n" +
	"rulesCount\"\x11\n" +
	"\x0fGetRulesRequest\"J\n" +
	"\x10GetRulesResponse\x126\n" +
	"\x05rules\x18\x01 \x03(\v2 .grpcfaultproxyservice.FaultRuleR\x05rules2\xd1\x01\n" +
	"\x15GrpcFaultProxyService\x12[\n" +
	"\bSetRules\x12&.grpcfaultproxyservice.SetRulesRequest\x1a'.grpcfaultproxyservice.SetRulesResponse\x12[\n" +
	"\bGetRules\x12&.grpcfaultproxyservice.GetRulesRequest\x1a'.grpcfaultproxyservice.GetRulesResponseB<Z:github.com/multigres/multigres/go/pb/grpcfaultproxyserviceb\x06proto3"

var (
	file_grpcfaultproxyservice_proto_rawDescOnce sync.Once
	file_grpcfaultproxyservice_proto_rawDescData []byte
)

func file_grpcfaultproxyservice_proto_rawDescGZIP() []byte {
	file_grpcfaultproxyservice_proto_rawDescOnce.Do(func() {
		file_grpcfaultproxyservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcfaultproxyservice_proto_rawDesc), len(file_grpcfaultproxyservice_proto_rawDesc)))
	})
	return file_grpcfaultproxyservice_proto_rawDescData
}

var file_grpcfaultproxyservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpcfaultproxyservice_proto_goTypes = []any{
	(*FaultRule)(nil),        // 0: grpcfaultproxyservice.FaultRule
	(*SetRulesRequest)(nil),  // 1: grpcfaultproxyservice.SetRulesRequest
	(*SetRulesResponse)(nil), // 2: grpcfaultproxyservice.SetRulesResponse
	(*GetRulesRequest)(nil),  // 3: grpcfaultproxyservice.GetRulesRequest
	(*GetRulesResponse)(nil), // 4: grpcfaultproxyservice.GetRulesResponse
}
var file_grpcfaultproxyservice_proto_depIdxs = []int32{
	0, // 0: grpcfaultproxyservice.SetRulesRequest.rules:type_name -> grpcfaultproxyservice.FaultRule
	0, // 1: grpcfaultproxyservice.GetRulesResponse.rules:type_name -> grpcfaultproxyservice.FaultRule
	1, // 2: grpcfaultproxyservice.GrpcFaultProxyService.SetRules:input_type -> grpcfaultproxyservice.SetRulesRequest
	3, // 3: grpcfaultproxyservice.GrpcFaultProxyService.GetRules:input_type -> grpcfaultproxyservice.GetRulesRequest
	2, // 4: grpcfaultproxyservice.GrpcFaultProxyService.SetRules:output_type -> grpcfaultproxyservice.SetRulesResponse
	4, // 5: grpcfaultproxyservice.GrpcFaultProxyService.GetRules:output_type -> grpcfaultproxyservice.GetRulesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpcfaultproxyservice_proto_init() }
func file_grpcfaultproxyservice_proto_init() {
	if File_grpcfaultproxyservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcfaultproxyservice_proto_rawDesc), len(file_grpcfaultproxyservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcfaultproxyservice_proto_goTypes,
		DependencyIndexes: file_grpcfaultproxyservice_proto_depIdxs,
		MessageInfos:      file_grpcfaultproxyservice_proto_msgTypes,
	}.Build()
	File_grpcfaultproxyservice_proto = out.File
	file_grpcfaultproxyservice_proto_goTypes = nil
	file_grpcfaultproxyservice_proto_depIdxs = nil
}
