// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: grpcfaultproxyservice.proto

package grpcfaultproxyservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcFaultProxyService_SetRules_FullMethodName = "/grpcfaultproxyservice.GrpcFaultProxyService/SetRules"
	GrpcFaultProxyService_GetRules_FullMethodName = "/grpcfaultproxyservice.GrpcFaultProxyService/GetRules"
)

// GrpcFaultProxyServiceClient is the client API for GrpcFaultProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GrpcFaultProxyService provides control over fault injection for testing.
// This service is only used in tests and should never be exposed in production.
type GrpcFaultProxyServiceClient interface {
	// SetRules replaces all fault injection rules with the provided rules.
	// Use an empty rules list to disable all fault injection.
	SetRules(ctx context.Context, in *SetRulesRequest, opts ...grpc.CallOption) (*SetRulesResponse, error)
	// GetRules returns the currently active fault injection rules.
	GetRules(ctx context.Context, in *GetRulesRequest, opts ...grpc.CallOption) (*GetRulesResponse, error)
}

type grpcFaultProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcFaultProxyServiceClient(cc grpc.ClientConnInterface) GrpcFaultProxyServiceClient {
	return &grpcFaultProxyServiceClient{cc}
}

func (c *grpcFaultProxyServiceClient) SetRules(ctx context.Context, in *SetRulesRequest, opts ...grpc.CallOption) (*SetRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRulesResponse)
	err := c.cc.Invoke(ctx, GrpcFaultProxyService_SetRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcFaultProxyServiceClient) GetRules(ctx context.Context, in *GetRulesRequest, opts ...grpc.CallOption) (*GetRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRulesResponse)
	err := c.cc.Invoke(ctx, GrpcFaultProxyService_GetRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcFaultProxyServiceServer is the server API for GrpcFaultProxyService service.
// All implementations must embed UnimplementedGrpcFaultProxyServiceServer
// for forward compatibility.
//
// GrpcFaultProxyService provides control over fault injection for testing.
// This service is only used in tests and should never be exposed in production.
type GrpcFaultProxyServiceServer interface {
	// SetRules replaces all fault injection rules with the provided rules.
	// Use an empty rules list to disable all fault injection.
	SetRules(context.Context, *SetRulesRequest) (*SetRulesResponse, error)
	// GetRules returns the currently active fault injection rules.
	GetRules(context.Context, *GetRulesRequest) (*GetRulesResponse, error)
	mustEmbedUnimplementedGrpcFaultProxyServiceServer()
}

// UnimplementedGrpcFaultProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcFaultProxyServiceServer struct{}

func (UnimplementedGrpcFaultProxyServiceServer) SetRules(context.Context, *SetRulesRequest) (*SetRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRules not implemented")
}
func (UnimplementedGrpcFaultProxyServiceServer) GetRules(context.Context, *GetRulesRequest) (*GetRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRules not implemented")
}
func (UnimplementedGrpcFaultProxyServiceServer) mustEmbedUnimplementedGrpcFaultProxyServiceServer() {}
func (UnimplementedGrpcFaultProxyServiceServer) testEmbeddedByValue()                               {}

// UnsafeGrpcFaultProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcFaultProxyServiceServer will
// result in compilation errors.
type UnsafeGrpcFaultProxyServiceServer interface {
	mustEmbedUnimplementedGrpcFaultProxyServiceServer()
}

func RegisterGrpcFaultProxyServiceServer(s grpc.ServiceRegistrar, srv GrpcFaultProxyServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrpcFaultProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcFaultProxyService_ServiceDesc, srv)
}

func _GrpcFaultProxyService_SetRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcFaultProxyServiceServer).SetRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcFaultProxyService_SetRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcFaultProxyServiceServer).SetRules(ctx, req.(*SetRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcFaultProxyService_GetRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcFaultProxyServiceServer).GetRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcFaultProxyService_GetRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcFaultProxyServiceServer).GetRules(ctx, req.(*GetRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcFaultProxyService_ServiceDesc is the grpc.ServiceDesc for GrpcFaultProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcFaultProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcfaultproxyservice.GrpcFaultProxyService",
	HandlerType: (*GrpcFaultProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRules",
			Handler:    _GrpcFaultProxyService_SetRules_Handler,
		},
		{
			MethodName: "GetRules",
			Handler:    _GrpcFaultProxyService_GetRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcfaultproxyservice.proto",
}
