//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multipooler.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: multipoolerservice.proto

package multipoolerservice

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	mtrpc "github.com/multigres/multigres/go/pb/mtrpc"
	query "github.com/multigres/multigres/go/pb/query"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteQueryRequest represents a request to execute a SQL query
type ExecuteQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target  *query.Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MaxRows uint64        `protobuf:"varint,3,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	// caller_id identifies the caller. This is the effective caller ID,
	// set by the application to further identify the caller.
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including session state needed for query execution.
	Options       *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ExecuteQueryRequest) GetMaxRows() uint64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *ExecuteQueryRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *ExecuteQueryRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ExecuteQueryResponse represents the response from executing a SQL query
type ExecuteQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *query.QueryResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteQueryResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// StreamExecuteRequest represents a request to execute a SQL query with streaming results
type StreamExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query is the SQL query to execute
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// caller_id identifies the caller. This is the effective caller ID,
	// set by the application to further identify the caller.
	CallerId *mtrpc.CallerID `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including session state needed for query execution.
	Options       *query.ExecuteOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecuteRequest) Reset() {
	*x = StreamExecuteRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteRequest) ProtoMessage() {}

func (x *StreamExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecuteRequest.ProtoReflect.Descriptor instead.
func (*StreamExecuteRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{2}
}

func (x *StreamExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *StreamExecuteRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamExecuteRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *StreamExecuteRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// StreamExecuteResponse represents a single response in the stream of query results
type StreamExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result contains the query result data (rows, fields, etc.)
	Result        *query.QueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecuteResponse) Reset() {
	*x = StreamExecuteResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteResponse) ProtoMessage() {}

func (x *StreamExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecuteResponse.ProtoReflect.Descriptor instead.
func (*StreamExecuteResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{3}
}

func (x *StreamExecuteResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// PortalStreamExecuteRequest represents a request to execute a portal with streaming results
type PortalStreamExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// prepared_statement contains the prepared statement to execute
	PreparedStatement *query.PreparedStatement `protobuf:"bytes,2,opt,name=prepared_statement,json=preparedStatement,proto3" json:"prepared_statement,omitempty"`
	// portal contains the portal with bound parameters
	Portal *query.Portal `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including max rows and reserved connection ID
	Options       *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalStreamExecuteRequest) Reset() {
	*x = PortalStreamExecuteRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalStreamExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalStreamExecuteRequest) ProtoMessage() {}

func (x *PortalStreamExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalStreamExecuteRequest.ProtoReflect.Descriptor instead.
func (*PortalStreamExecuteRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{4}
}

func (x *PortalStreamExecuteRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetPreparedStatement() *query.PreparedStatement {
	if x != nil {
		return x.PreparedStatement
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetPortal() *query.Portal {
	if x != nil {
		return x.Portal
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// PortalStreamExecuteResponse represents a response in the portal execution stream
type PortalStreamExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result contains the query result data (rows, fields, etc.)
	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// reserved_connection_id is the ID of the reserved connection
	// This is returned in the first response and should be used for subsequent queries
	ReservedConnectionId uint64 `protobuf:"varint,2,opt,name=reserved_connection_id,json=reservedConnectionId,proto3" json:"reserved_connection_id,omitempty"`
	// pooler_id identifies which multipooler instance owns the reserved connection
	PoolerId      *clustermetadata.ID `protobuf:"bytes,3,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalStreamExecuteResponse) Reset() {
	*x = PortalStreamExecuteResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalStreamExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalStreamExecuteResponse) ProtoMessage() {}

func (x *PortalStreamExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalStreamExecuteResponse.ProtoReflect.Descriptor instead.
func (*PortalStreamExecuteResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{5}
}

func (x *PortalStreamExecuteResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PortalStreamExecuteResponse) GetReservedConnectionId() uint64 {
	if x != nil {
		return x.ReservedConnectionId
	}
	return 0
}

func (x *PortalStreamExecuteResponse) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

// DescribeRequest represents a request to describe a prepared statement or portal
type DescribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// prepared_statement is the prepared statement to describe (nil if describing a portal)
	PreparedStatement *query.PreparedStatement `protobuf:"bytes,2,opt,name=prepared_statement,json=preparedStatement,proto3" json:"prepared_statement,omitempty"`
	// portal is the portal to describe (nil if describing a prepared statement)
	Portal *query.Portal `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including reserved connection ID
	Options       *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DescribeRequest) GetPreparedStatement() *query.PreparedStatement {
	if x != nil {
		return x.PreparedStatement
	}
	return nil
}

func (x *DescribeRequest) GetPortal() *query.Portal {
	if x != nil {
		return x.Portal
	}
	return nil
}

func (x *DescribeRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *DescribeRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// DescribeResponse represents the response from describing a statement or portal
type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// description contains the statement metadata (fields, parameter types, etc.)
	Description   *query.StatementDescription `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeResponse) GetDescription() *query.StatementDescription {
	if x != nil {
		return x.Description
	}
	return nil
}

// GetAuthCredentialsRequest represents a request to get authentication credentials for a user.
type GetAuthCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the database the user is connecting to.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// username is the PostgreSQL username to authenticate.
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthCredentialsRequest) Reset() {
	*x = GetAuthCredentialsRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthCredentialsRequest) ProtoMessage() {}

func (x *GetAuthCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetAuthCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetAuthCredentialsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetAuthCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// GetAuthCredentialsResponse represents the response containing authentication credentials.
// Returns codes.NotFound if the user does not exist.
type GetAuthCredentialsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scram_hash is the stored SCRAM-SHA-256 password hash from pg_authid.
	// Format: SCRAM-SHA-256$<iterations>:<salt>$<stored_key>:<server_key>
	// Empty if user exists but has no password set.
	ScramHash     string `protobuf:"bytes,1,opt,name=scram_hash,json=scramHash,proto3" json:"scram_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthCredentialsResponse) Reset() {
	*x = GetAuthCredentialsResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthCredentialsResponse) ProtoMessage() {}

func (x *GetAuthCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetAuthCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuthCredentialsResponse) GetScramHash() string {
	if x != nil {
		return x.ScramHash
	}
	return ""
}

// StreamPoolerHealthRequest initiates a health stream from the multipooler.
// Currently empty; future versions may add fields for client-requested intervals.
type StreamPoolerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPoolerHealthRequest) Reset() {
	*x = StreamPoolerHealthRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPoolerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPoolerHealthRequest) ProtoMessage() {}

func (x *StreamPoolerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPoolerHealthRequest.ProtoReflect.Descriptor instead.
func (*StreamPoolerHealthRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{10}
}

// StreamPoolerHealthResponse contains the current health state of the multipooler.
// Sent immediately on connection, on state changes, and periodically as heartbeats.
type StreamPoolerHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target identifies the tablegroup, shard, and pooler type this pooler serves.
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// pooler_id identifies this multipooler instance.
	PoolerId *clustermetadata.ID `protobuf:"bytes,2,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// serving_status is the current serving state of the pooler.
	ServingStatus clustermetadata.PoolerServingStatus `protobuf:"varint,3,opt,name=serving_status,json=servingStatus,proto3,enum=clustermetadata.PoolerServingStatus" json:"serving_status,omitempty"`
	// primary_observation contains this pooler's view of who the primary is.
	// Used by clients to identify the true primary when multiple poolers exist.
	PrimaryObservation *PrimaryObservation `protobuf:"bytes,4,opt,name=primary_observation,json=primaryObservation,proto3" json:"primary_observation,omitempty"`
	// recommended_staleness_timeout is the duration clients should use
	// to detect a stale/dead health stream. If no message is received within
	// this duration, clients should mark the pooler as unhealthy.
	RecommendedStalenessTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=recommended_staleness_timeout,json=recommendedStalenessTimeout,proto3" json:"recommended_staleness_timeout,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StreamPoolerHealthResponse) Reset() {
	*x = StreamPoolerHealthResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPoolerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPoolerHealthResponse) ProtoMessage() {}

func (x *StreamPoolerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPoolerHealthResponse.ProtoReflect.Descriptor instead.
func (*StreamPoolerHealthResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{11}
}

func (x *StreamPoolerHealthResponse) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetServingStatus() clustermetadata.PoolerServingStatus {
	if x != nil {
		return x.ServingStatus
	}
	return clustermetadata.PoolerServingStatus(0)
}

func (x *StreamPoolerHealthResponse) GetPrimaryObservation() *PrimaryObservation {
	if x != nil {
		return x.PrimaryObservation
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetRecommendedStalenessTimeout() *durationpb.Duration {
	if x != nil {
		return x.RecommendedStalenessTimeout
	}
	return nil
}

// PrimaryObservation represents a pooler's view of who the primary is.
type PrimaryObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary_id is the ID of the pooler this node believes is the primary.
	// May be this pooler's own ID if it believes itself to be primary.
	PrimaryId *clustermetadata.ID `protobuf:"bytes,1,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	// term is the consensus term at which this observation was made.
	// Higher terms indicate more recent observations.
	Term          int64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryObservation) Reset() {
	*x = PrimaryObservation{}
	mi := &file_multipoolerservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryObservation) ProtoMessage() {}

func (x *PrimaryObservation) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryObservation.ProtoReflect.Descriptor instead.
func (*PrimaryObservation) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{12}
}

func (x *PrimaryObservation) GetPrimaryId() *clustermetadata.ID {
	if x != nil {
		return x.PrimaryId
	}
	return nil
}

func (x *PrimaryObservation) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_multipoolerservice_proto protoreflect.FileDescriptor

const file_multipoolerservice_proto_rawDesc = "" +
	"\n" +
	"\x18multipoolerservice.proto\x12\x12multipoolerservice\x1a\x15clustermetadata.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\vmtrpc.proto\x1a\vquery.proto\"\xcc\x01\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.query.TargetR\x06target\x12\x19\n" +
	"\bmax_rows\x18\x03 \x01(\x04R\amaxRows\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"B\n" +
	"\x14ExecuteQueryResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\"\xb2\x01\n" +
	"\x14StreamExecuteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x03 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x04 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"C\n" +
	"\x15StreamExecuteResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\"\x92\x02\n" +
	"\x1aPortalStreamExecuteRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12G\n" +
	"\x12prepared_statement\x18\x02 \x01(\v2\x18.query.PreparedStatementR\x11preparedStatement\x12%\n" +
	"\x06portal\x18\x03 \x01(\v2\r.query.PortalR\x06portal\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"\xb1\x01\n" +
	"\x1bPortalStreamExecuteResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\x124\n" +
	"\x16reserved_connection_id\x18\x02 \x01(\x04R\x14reservedConnectionId\x120\n" +
	"\tpooler_id\x18\x03 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\"\x87\x02\n" +
	"\x0fDescribeRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12G\n" +
	"\x12prepared_statement\x18\x02 \x01(\v2\x18.query.PreparedStatementR\x11preparedStatement\x12%\n" +
	"\x06portal\x18\x03 \x01(\v2\r.query.PortalR\x06portal\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"Q\n" +
	"\x10DescribeResponse\x12=\n" +
	"\vdescription\x18\x01 \x01(\v2\x1b.query.StatementDescriptionR\vdescription\"S\n" +
	"\x19GetAuthCredentialsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\";\n" +
	"\x1aGetAuthCredentialsResponse\x12\x1d\n" +
	"\n" +
	"scram_hash\x18\x01 \x01(\tR\tscramHash\"\x1b\n" +
	"\x19StreamPoolerHealthRequest\"\xfa\x02\n" +
	"\x1aStreamPoolerHealthResponse\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x120\n" +
	"\tpooler_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\x12K\n" +
	"\x0eserving_status\x18\x03 \x01(\x0e2$.clustermetadata.PoolerServingStatusR\rservingStatus\x12W\n" +
	"\x13primary_observation\x18\x04 \x01(\v2&.multipoolerservice.PrimaryObservationR\x12primaryObservation\x12]\n" +
	"\x1drecommended_staleness_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x1brecommendedStalenessTimeout\"\\\n" +
	"\x12PrimaryObservation\x122\n" +
	"\n" +
	"primary_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\tprimaryId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term2\x9c\x05\n" +
	"\x12MultiPoolerService\x12a\n" +
	"\fExecuteQuery\x12'.multipoolerservice.ExecuteQueryRequest\x1a(.multipoolerservice.ExecuteQueryResponse\x12f\n" +
	"\rStreamExecute\x12(.multipoolerservice.StreamExecuteRequest\x1a).multipoolerservice.StreamExecuteResponse0\x01\x12x\n" +
	"\x13PortalStreamExecute\x12..multipoolerservice.PortalStreamExecuteRequest\x1a/.multipoolerservice.PortalStreamExecuteResponse0\x01\x12U\n" +
	"\bDescribe\x12#.multipoolerservice.DescribeRequest\x1a$.multipoolerservice.DescribeResponse\x12s\n" +
	"\x12GetAuthCredentials\x12-.multipoolerservice.GetAuthCredentialsRequest\x1a..multipoolerservice.GetAuthCredentialsResponse\x12u\n" +
	"\x12StreamPoolerHealth\x12-.multipoolerservice.StreamPoolerHealthRequest\x1a..multipoolerservice.StreamPoolerHealthResponse0\x01B9Z7github.com/multigres/multigres/go/pb/multipoolerserviceb\x06proto3"

var (
	file_multipoolerservice_proto_rawDescOnce sync.Once
	file_multipoolerservice_proto_rawDescData []byte
)

func file_multipoolerservice_proto_rawDescGZIP() []byte {
	file_multipoolerservice_proto_rawDescOnce.Do(func() {
		file_multipoolerservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipoolerservice_proto_rawDesc), len(file_multipoolerservice_proto_rawDesc)))
	})
	return file_multipoolerservice_proto_rawDescData
}

var file_multipoolerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_multipoolerservice_proto_goTypes = []any{
	(*ExecuteQueryRequest)(nil),              // 0: multipoolerservice.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil),             // 1: multipoolerservice.ExecuteQueryResponse
	(*StreamExecuteRequest)(nil),             // 2: multipoolerservice.StreamExecuteRequest
	(*StreamExecuteResponse)(nil),            // 3: multipoolerservice.StreamExecuteResponse
	(*PortalStreamExecuteRequest)(nil),       // 4: multipoolerservice.PortalStreamExecuteRequest
	(*PortalStreamExecuteResponse)(nil),      // 5: multipoolerservice.PortalStreamExecuteResponse
	(*DescribeRequest)(nil),                  // 6: multipoolerservice.DescribeRequest
	(*DescribeResponse)(nil),                 // 7: multipoolerservice.DescribeResponse
	(*GetAuthCredentialsRequest)(nil),        // 8: multipoolerservice.GetAuthCredentialsRequest
	(*GetAuthCredentialsResponse)(nil),       // 9: multipoolerservice.GetAuthCredentialsResponse
	(*StreamPoolerHealthRequest)(nil),        // 10: multipoolerservice.StreamPoolerHealthRequest
	(*StreamPoolerHealthResponse)(nil),       // 11: multipoolerservice.StreamPoolerHealthResponse
	(*PrimaryObservation)(nil),               // 12: multipoolerservice.PrimaryObservation
	(*query.Target)(nil),                     // 13: query.Target
	(*mtrpc.CallerID)(nil),                   // 14: mtrpc.CallerID
	(*query.ExecuteOptions)(nil),             // 15: query.ExecuteOptions
	(*query.QueryResult)(nil),                // 16: query.QueryResult
	(*query.PreparedStatement)(nil),          // 17: query.PreparedStatement
	(*query.Portal)(nil),                     // 18: query.Portal
	(*clustermetadata.ID)(nil),               // 19: clustermetadata.ID
	(*query.StatementDescription)(nil),       // 20: query.StatementDescription
	(clustermetadata.PoolerServingStatus)(0), // 21: clustermetadata.PoolerServingStatus
	(*durationpb.Duration)(nil),              // 22: google.protobuf.Duration
}
var file_multipoolerservice_proto_depIdxs = []int32{
	13, // 0: multipoolerservice.ExecuteQueryRequest.target:type_name -> query.Target
	14, // 1: multipoolerservice.ExecuteQueryRequest.caller_id:type_name -> mtrpc.CallerID
	15, // 2: multipoolerservice.ExecuteQueryRequest.options:type_name -> query.ExecuteOptions
	16, // 3: multipoolerservice.ExecuteQueryResponse.result:type_name -> query.QueryResult
	13, // 4: multipoolerservice.StreamExecuteRequest.target:type_name -> query.Target
	14, // 5: multipoolerservice.StreamExecuteRequest.caller_id:type_name -> mtrpc.CallerID
	15, // 6: multipoolerservice.StreamExecuteRequest.options:type_name -> query.ExecuteOptions
	16, // 7: multipoolerservice.StreamExecuteResponse.result:type_name -> query.QueryResult
	13, // 8: multipoolerservice.PortalStreamExecuteRequest.target:type_name -> query.Target
	17, // 9: multipoolerservice.PortalStreamExecuteRequest.prepared_statement:type_name -> query.PreparedStatement
	18, // 10: multipoolerservice.PortalStreamExecuteRequest.portal:type_name -> query.Portal
	14, // 11: multipoolerservice.PortalStreamExecuteRequest.caller_id:type_name -> mtrpc.CallerID
	15, // 12: multipoolerservice.PortalStreamExecuteRequest.options:type_name -> query.ExecuteOptions
	16, // 13: multipoolerservice.PortalStreamExecuteResponse.result:type_name -> query.QueryResult
	19, // 14: multipoolerservice.PortalStreamExecuteResponse.pooler_id:type_name -> clustermetadata.ID
	13, // 15: multipoolerservice.DescribeRequest.target:type_name -> query.Target
	17, // 16: multipoolerservice.DescribeRequest.prepared_statement:type_name -> query.PreparedStatement
	18, // 17: multipoolerservice.DescribeRequest.portal:type_name -> query.Portal
	14, // 18: multipoolerservice.DescribeRequest.caller_id:type_name -> mtrpc.CallerID
	15, // 19: multipoolerservice.DescribeRequest.options:type_name -> query.ExecuteOptions
	20, // 20: multipoolerservice.DescribeResponse.description:type_name -> query.StatementDescription
	13, // 21: multipoolerservice.StreamPoolerHealthResponse.target:type_name -> query.Target
	19, // 22: multipoolerservice.StreamPoolerHealthResponse.pooler_id:type_name -> clustermetadata.ID
	21, // 23: multipoolerservice.StreamPoolerHealthResponse.serving_status:type_name -> clustermetadata.PoolerServingStatus
	12, // 24: multipoolerservice.StreamPoolerHealthResponse.primary_observation:type_name -> multipoolerservice.PrimaryObservation
	22, // 25: multipoolerservice.StreamPoolerHealthResponse.recommended_staleness_timeout:type_name -> google.protobuf.Duration
	19, // 26: multipoolerservice.PrimaryObservation.primary_id:type_name -> clustermetadata.ID
	0,  // 27: multipoolerservice.MultiPoolerService.ExecuteQuery:input_type -> multipoolerservice.ExecuteQueryRequest
	2,  // 28: multipoolerservice.MultiPoolerService.StreamExecute:input_type -> multipoolerservice.StreamExecuteRequest
	4,  // 29: multipoolerservice.MultiPoolerService.PortalStreamExecute:input_type -> multipoolerservice.PortalStreamExecuteRequest
	6,  // 30: multipoolerservice.MultiPoolerService.Describe:input_type -> multipoolerservice.DescribeRequest
	8,  // 31: multipoolerservice.MultiPoolerService.GetAuthCredentials:input_type -> multipoolerservice.GetAuthCredentialsRequest
	10, // 32: multipoolerservice.MultiPoolerService.StreamPoolerHealth:input_type -> multipoolerservice.StreamPoolerHealthRequest
	1,  // 33: multipoolerservice.MultiPoolerService.ExecuteQuery:output_type -> multipoolerservice.ExecuteQueryResponse
	3,  // 34: multipoolerservice.MultiPoolerService.StreamExecute:output_type -> multipoolerservice.StreamExecuteResponse
	5,  // 35: multipoolerservice.MultiPoolerService.PortalStreamExecute:output_type -> multipoolerservice.PortalStreamExecuteResponse
	7,  // 36: multipoolerservice.MultiPoolerService.Describe:output_type -> multipoolerservice.DescribeResponse
	9,  // 37: multipoolerservice.MultiPoolerService.GetAuthCredentials:output_type -> multipoolerservice.GetAuthCredentialsResponse
	11, // 38: multipoolerservice.MultiPoolerService.StreamPoolerHealth:output_type -> multipoolerservice.StreamPoolerHealthResponse
	33, // [33:39] is the sub-list for method output_type
	27, // [27:33] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_multipoolerservice_proto_init() }
func file_multipoolerservice_proto_init() {
	if File_multipoolerservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipoolerservice_proto_rawDesc), len(file_multipoolerservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multipoolerservice_proto_goTypes,
		DependencyIndexes: file_multipoolerservice_proto_depIdxs,
		MessageInfos:      file_multipoolerservice_proto_msgTypes,
	}.Build()
	File_multipoolerservice_proto = out.File
	file_multipoolerservice_proto_goTypes = nil
	file_multipoolerservice_proto_depIdxs = nil
}
