//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multipooler.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: multipoolerservice.proto

//go:build protoopaque

package multipoolerservice

import (
	reflect "reflect"
	unsafe "unsafe"

	mtrpc "github.com/multigres/multigres/go/pb/mtrpc"
	query "github.com/multigres/multigres/go/pb/query"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteQueryRequest represents a request to execute a SQL query
type ExecuteQueryRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Query    string                 `protobuf:"bytes,1,opt,name=query,proto3"`
	xxx_hidden_Target   *query.Target          `protobuf:"bytes,2,opt,name=target,proto3"`
	xxx_hidden_MaxRows  uint64                 `protobuf:"varint,3,opt,name=max_rows,json=maxRows,proto3"`
	xxx_hidden_CallerId *mtrpc.CallerID        `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetTarget() *query.Target {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *ExecuteQueryRequest) GetMaxRows() uint64 {
	if x != nil {
		return x.xxx_hidden_MaxRows
	}
	return 0
}

func (x *ExecuteQueryRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.xxx_hidden_CallerId
	}
	return nil
}

func (x *ExecuteQueryRequest) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *ExecuteQueryRequest) SetTarget(v *query.Target) {
	x.xxx_hidden_Target = v
}

func (x *ExecuteQueryRequest) SetMaxRows(v uint64) {
	x.xxx_hidden_MaxRows = v
}

func (x *ExecuteQueryRequest) SetCallerId(v *mtrpc.CallerID) {
	x.xxx_hidden_CallerId = v
}

func (x *ExecuteQueryRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *ExecuteQueryRequest) HasCallerId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CallerId != nil
}

func (x *ExecuteQueryRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *ExecuteQueryRequest) ClearCallerId() {
	x.xxx_hidden_CallerId = nil
}

type ExecuteQueryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Query string
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target  *query.Target
	MaxRows uint64
	// caller_id identifies the caller. This is the effective caller ID,
	// set by the application to further identify the caller.
	CallerId *mtrpc.CallerID
}

func (b0 ExecuteQueryRequest_builder) Build() *ExecuteQueryRequest {
	m0 := &ExecuteQueryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_MaxRows = b.MaxRows
	x.xxx_hidden_CallerId = b.CallerId
	return m0
}

// ExecuteQueryResponse represents the response from executing a SQL query
type ExecuteQueryResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result *query.QueryResult     `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecuteQueryResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *ExecuteQueryResponse) SetResult(v *query.QueryResult) {
	x.xxx_hidden_Result = v
}

func (x *ExecuteQueryResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *ExecuteQueryResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

type ExecuteQueryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result *query.QueryResult
}

func (b0 ExecuteQueryResponse_builder) Build() *ExecuteQueryResponse {
	m0 := &ExecuteQueryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

// StreamExecuteRequest represents a request to execute a SQL query with streaming results
type StreamExecuteRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Query    string                 `protobuf:"bytes,1,opt,name=query,proto3"`
	xxx_hidden_Target   *query.Target          `protobuf:"bytes,2,opt,name=target,proto3"`
	xxx_hidden_CallerId *mtrpc.CallerID        `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamExecuteRequest) Reset() {
	*x = StreamExecuteRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteRequest) ProtoMessage() {}

func (x *StreamExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamExecuteRequest) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *StreamExecuteRequest) GetTarget() *query.Target {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *StreamExecuteRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.xxx_hidden_CallerId
	}
	return nil
}

func (x *StreamExecuteRequest) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *StreamExecuteRequest) SetTarget(v *query.Target) {
	x.xxx_hidden_Target = v
}

func (x *StreamExecuteRequest) SetCallerId(v *mtrpc.CallerID) {
	x.xxx_hidden_CallerId = v
}

func (x *StreamExecuteRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *StreamExecuteRequest) HasCallerId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CallerId != nil
}

func (x *StreamExecuteRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *StreamExecuteRequest) ClearCallerId() {
	x.xxx_hidden_CallerId = nil
}

type StreamExecuteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// query is the SQL query to execute
	Query string
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target
	// caller_id identifies the caller. This is the effective caller ID,
	// set by the application to further identify the caller.
	CallerId *mtrpc.CallerID
}

func (b0 StreamExecuteRequest_builder) Build() *StreamExecuteRequest {
	m0 := &StreamExecuteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_CallerId = b.CallerId
	return m0
}

// StreamExecuteResponse represents a single response in the stream of query results
type StreamExecuteResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Result *query.QueryResult     `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamExecuteResponse) Reset() {
	*x = StreamExecuteResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteResponse) ProtoMessage() {}

func (x *StreamExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamExecuteResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *StreamExecuteResponse) SetResult(v *query.QueryResult) {
	x.xxx_hidden_Result = v
}

func (x *StreamExecuteResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *StreamExecuteResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

type StreamExecuteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// result contains the query result data (rows, fields, etc.)
	Result *query.QueryResult
}

func (b0 StreamExecuteResponse_builder) Build() *StreamExecuteResponse {
	m0 := &StreamExecuteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Result = b.Result
	return m0
}

var File_multipoolerservice_proto protoreflect.FileDescriptor

const file_multipoolerservice_proto_rawDesc = "" +
	"\n" +
	"\x18multipoolerservice.proto\x12\x12multipoolerservice\x1a\vmtrpc.proto\x1a\vquery.proto\"\x9b\x01\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.query.TargetR\x06target\x12\x19\n" +
	"\bmax_rows\x18\x03 \x01(\x04R\amaxRows\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\"B\n" +
	"\x14ExecuteQueryResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\"\x81\x01\n" +
	"\x14StreamExecuteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x03 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\"C\n" +
	"\x15StreamExecuteResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result2\xdf\x01\n" +
	"\x12MultiPoolerService\x12a\n" +
	"\fExecuteQuery\x12'.multipoolerservice.ExecuteQueryRequest\x1a(.multipoolerservice.ExecuteQueryResponse\x12f\n" +
	"\rStreamExecute\x12(.multipoolerservice.StreamExecuteRequest\x1a).multipoolerservice.StreamExecuteResponse0\x01B9Z7github.com/multigres/multigres/go/pb/multipoolerserviceb\x06proto3"

var file_multipoolerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_multipoolerservice_proto_goTypes = []any{
	(*ExecuteQueryRequest)(nil),   // 0: multipoolerservice.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil),  // 1: multipoolerservice.ExecuteQueryResponse
	(*StreamExecuteRequest)(nil),  // 2: multipoolerservice.StreamExecuteRequest
	(*StreamExecuteResponse)(nil), // 3: multipoolerservice.StreamExecuteResponse
	(*query.Target)(nil),          // 4: query.Target
	(*mtrpc.CallerID)(nil),        // 5: mtrpc.CallerID
	(*query.QueryResult)(nil),     // 6: query.QueryResult
}
var file_multipoolerservice_proto_depIdxs = []int32{
	4, // 0: multipoolerservice.ExecuteQueryRequest.target:type_name -> query.Target
	5, // 1: multipoolerservice.ExecuteQueryRequest.caller_id:type_name -> mtrpc.CallerID
	6, // 2: multipoolerservice.ExecuteQueryResponse.result:type_name -> query.QueryResult
	4, // 3: multipoolerservice.StreamExecuteRequest.target:type_name -> query.Target
	5, // 4: multipoolerservice.StreamExecuteRequest.caller_id:type_name -> mtrpc.CallerID
	6, // 5: multipoolerservice.StreamExecuteResponse.result:type_name -> query.QueryResult
	0, // 6: multipoolerservice.MultiPoolerService.ExecuteQuery:input_type -> multipoolerservice.ExecuteQueryRequest
	2, // 7: multipoolerservice.MultiPoolerService.StreamExecute:input_type -> multipoolerservice.StreamExecuteRequest
	1, // 8: multipoolerservice.MultiPoolerService.ExecuteQuery:output_type -> multipoolerservice.ExecuteQueryResponse
	3, // 9: multipoolerservice.MultiPoolerService.StreamExecute:output_type -> multipoolerservice.StreamExecuteResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_multipoolerservice_proto_init() }
func file_multipoolerservice_proto_init() {
	if File_multipoolerservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipoolerservice_proto_rawDesc), len(file_multipoolerservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multipoolerservice_proto_goTypes,
		DependencyIndexes: file_multipoolerservice_proto_depIdxs,
		MessageInfos:      file_multipoolerservice_proto_msgTypes,
	}.Build()
	File_multipoolerservice_proto = out.File
	file_multipoolerservice_proto_goTypes = nil
	file_multipoolerservice_proto_depIdxs = nil
}
