// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multiorchservice.proto

package multiorch

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisableRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRecoveryRequest) Reset() {
	*x = DisableRecoveryRequest{}
	mi := &file_multiorchservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRecoveryRequest) ProtoMessage() {}

func (x *DisableRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRecoveryRequest.ProtoReflect.Descriptor instead.
func (*DisableRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{0}
}

type DisableRecoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether recovery was disabled
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableRecoveryResponse) Reset() {
	*x = DisableRecoveryResponse{}
	mi := &file_multiorchservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRecoveryResponse) ProtoMessage() {}

func (x *DisableRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRecoveryResponse.ProtoReflect.Descriptor instead.
func (*DisableRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{1}
}

func (x *DisableRecoveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisableRecoveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnableRecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRecoveryRequest) Reset() {
	*x = EnableRecoveryRequest{}
	mi := &file_multiorchservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRecoveryRequest) ProtoMessage() {}

func (x *EnableRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRecoveryRequest.ProtoReflect.Descriptor instead.
func (*EnableRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{2}
}

type EnableRecoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether recovery was enabled
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRecoveryResponse) Reset() {
	*x = EnableRecoveryResponse{}
	mi := &file_multiorchservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRecoveryResponse) ProtoMessage() {}

func (x *EnableRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRecoveryResponse.ProtoReflect.Descriptor instead.
func (*EnableRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{3}
}

func (x *EnableRecoveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnableRecoveryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRecoveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryStatusRequest) Reset() {
	*x = GetRecoveryStatusRequest{}
	mi := &file_multiorchservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryStatusRequest) ProtoMessage() {}

func (x *GetRecoveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRecoveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{4}
}

type GetRecoveryStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled indicates whether recovery is currently active
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryStatusResponse) Reset() {
	*x = GetRecoveryStatusResponse{}
	mi := &file_multiorchservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryStatusResponse) ProtoMessage() {}

func (x *GetRecoveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRecoveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecoveryStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type TriggerRecoveryNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRecoveryNowRequest) Reset() {
	*x = TriggerRecoveryNowRequest{}
	mi := &file_multiorchservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRecoveryNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRecoveryNowRequest) ProtoMessage() {}

func (x *TriggerRecoveryNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRecoveryNowRequest.ProtoReflect.Descriptor instead.
func (*TriggerRecoveryNowRequest) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{6}
}

type TriggerRecoveryNowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// remaining_problem_codes lists problem codes still detected (e.g., "REPLICA_NOT_REPLICATING")
	RemainingProblemCodes []string `protobuf:"bytes,4,rep,name=remaining_problem_codes,json=remainingProblemCodes,proto3" json:"remaining_problem_codes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TriggerRecoveryNowResponse) Reset() {
	*x = TriggerRecoveryNowResponse{}
	mi := &file_multiorchservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRecoveryNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRecoveryNowResponse) ProtoMessage() {}

func (x *TriggerRecoveryNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiorchservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRecoveryNowResponse.ProtoReflect.Descriptor instead.
func (*TriggerRecoveryNowResponse) Descriptor() ([]byte, []int) {
	return file_multiorchservice_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerRecoveryNowResponse) GetRemainingProblemCodes() []string {
	if x != nil {
		return x.RemainingProblemCodes
	}
	return nil
}

var File_multiorchservice_proto protoreflect.FileDescriptor

const file_multiorchservice_proto_rawDesc = "" +
	"\n" +
	"\x16multiorchservice.proto\x12\tmultiorch\x1a\x1cgoogle/api/annotations.proto\"\x18\n" +
	"\x16DisableRecoveryRequest\"M\n" +
	"\x17DisableRecoveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15EnableRecoveryRequest\"L\n" +
	"\x16EnableRecoveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18GetRecoveryStatusRequest\"5\n" +
	"\x19GetRecoveryStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x1b\n" +
	"\x19TriggerRecoveryNowRequest\"T\n" +
	"\x1aTriggerRecoveryNowResponse\x126\n" +
	"\x17remaining_problem_codes\x18\x04 \x03(\tR\x15remainingProblemCodes2\x96\x04\n" +
	"\x10MultiOrchService\x12}\n" +
	"\x0fDisableRecovery\x12!.multiorch.DisableRecoveryRequest\x1a\".multiorch.DisableRecoveryResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/recovery/disable\x12y\n" +
	"\x0eEnableRecovery\x12 .multiorch.EnableRecoveryRequest\x1a!.multiorch.EnableRecoveryResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/recovery/enable\x12\x7f\n" +
	"\x11GetRecoveryStatus\x12#.multiorch.GetRecoveryStatusRequest\x1a$.multiorch.GetRecoveryStatusResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/recovery/status\x12\x86\x01\n" +
	"\x12TriggerRecoveryNow\x12$.multiorch.TriggerRecoveryNowRequest\x1a%.multiorch.TriggerRecoveryNowResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/recovery/triggerB0Z.github.com/multigres/multigres/go/pb/multiorchb\x06proto3"

var (
	file_multiorchservice_proto_rawDescOnce sync.Once
	file_multiorchservice_proto_rawDescData []byte
)

func file_multiorchservice_proto_rawDescGZIP() []byte {
	file_multiorchservice_proto_rawDescOnce.Do(func() {
		file_multiorchservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiorchservice_proto_rawDesc), len(file_multiorchservice_proto_rawDesc)))
	})
	return file_multiorchservice_proto_rawDescData
}

var file_multiorchservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_multiorchservice_proto_goTypes = []any{
	(*DisableRecoveryRequest)(nil),     // 0: multiorch.DisableRecoveryRequest
	(*DisableRecoveryResponse)(nil),    // 1: multiorch.DisableRecoveryResponse
	(*EnableRecoveryRequest)(nil),      // 2: multiorch.EnableRecoveryRequest
	(*EnableRecoveryResponse)(nil),     // 3: multiorch.EnableRecoveryResponse
	(*GetRecoveryStatusRequest)(nil),   // 4: multiorch.GetRecoveryStatusRequest
	(*GetRecoveryStatusResponse)(nil),  // 5: multiorch.GetRecoveryStatusResponse
	(*TriggerRecoveryNowRequest)(nil),  // 6: multiorch.TriggerRecoveryNowRequest
	(*TriggerRecoveryNowResponse)(nil), // 7: multiorch.TriggerRecoveryNowResponse
}
var file_multiorchservice_proto_depIdxs = []int32{
	0, // 0: multiorch.MultiOrchService.DisableRecovery:input_type -> multiorch.DisableRecoveryRequest
	2, // 1: multiorch.MultiOrchService.EnableRecovery:input_type -> multiorch.EnableRecoveryRequest
	4, // 2: multiorch.MultiOrchService.GetRecoveryStatus:input_type -> multiorch.GetRecoveryStatusRequest
	6, // 3: multiorch.MultiOrchService.TriggerRecoveryNow:input_type -> multiorch.TriggerRecoveryNowRequest
	1, // 4: multiorch.MultiOrchService.DisableRecovery:output_type -> multiorch.DisableRecoveryResponse
	3, // 5: multiorch.MultiOrchService.EnableRecovery:output_type -> multiorch.EnableRecoveryResponse
	5, // 6: multiorch.MultiOrchService.GetRecoveryStatus:output_type -> multiorch.GetRecoveryStatusResponse
	7, // 7: multiorch.MultiOrchService.TriggerRecoveryNow:output_type -> multiorch.TriggerRecoveryNowResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiorchservice_proto_init() }
func file_multiorchservice_proto_init() {
	if File_multiorchservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiorchservice_proto_rawDesc), len(file_multiorchservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiorchservice_proto_goTypes,
		DependencyIndexes: file_multiorchservice_proto_depIdxs,
		MessageInfos:      file_multiorchservice_proto_msgTypes,
	}.Build()
	File_multiorchservice_proto = out.File
	file_multiorchservice_proto_goTypes = nil
	file_multiorchservice_proto_depIdxs = nil
}
