// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: pgctldservice.proto

//go:build protoopaque

package pgctldservice

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server status enumeration
type ServerStatus int32

const (
	ServerStatus_UNKNOWN         ServerStatus = 0
	ServerStatus_STOPPED         ServerStatus = 1
	ServerStatus_STARTING        ServerStatus = 2
	ServerStatus_RUNNING         ServerStatus = 3
	ServerStatus_STOPPING        ServerStatus = 4
	ServerStatus_NOT_INITIALIZED ServerStatus = 5
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "STOPPED",
		2: "STARTING",
		3: "RUNNING",
		4: "STOPPING",
		5: "NOT_INITIALIZED",
	}
	ServerStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"STOPPED":         1,
		"STARTING":        2,
		"RUNNING":         3,
		"STOPPING":        4,
		"NOT_INITIALIZED": 5,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pgctldservice_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_pgctldservice_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Start PostgreSQL server
type StartRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Port      int32                  `protobuf:"varint,1,opt,name=port,proto3"`
	xxx_hidden_ExtraArgs []string               `protobuf:"bytes,2,rep,name=extra_args,json=extraArgs,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_pgctldservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartRequest) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *StartRequest) GetExtraArgs() []string {
	if x != nil {
		return x.xxx_hidden_ExtraArgs
	}
	return nil
}

func (x *StartRequest) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

func (x *StartRequest) SetExtraArgs(v []string) {
	x.xxx_hidden_ExtraArgs = v
}

type StartRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Override the default port
	Port int32
	// Additional postgres command line arguments
	ExtraArgs []string
}

func (b0 StartRequest_builder) Build() *StartRequest {
	m0 := &StartRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_ExtraArgs = b.ExtraArgs
	return m0
}

type StartResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pid     int32                  `protobuf:"varint,1,opt,name=pid,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_pgctldservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartResponse) GetPid() int32 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *StartResponse) SetPid(v int32) {
	x.xxx_hidden_Pid = v
}

func (x *StartResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type StartResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Process ID of started PostgreSQL server
	Pid int32
	// Status message
	Message string
}

func (b0 StartResponse_builder) Build() *StartResponse {
	m0 := &StartResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pid = b.Pid
	x.xxx_hidden_Message = b.Message
	return m0
}

// Stop PostgreSQL server
type StopRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mode    string                 `protobuf:"bytes,1,opt,name=mode,proto3"`
	xxx_hidden_Timeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_pgctldservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopRequest) GetMode() string {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return ""
}

func (x *StopRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return nil
}

func (x *StopRequest) SetMode(v string) {
	x.xxx_hidden_Mode = v
}

func (x *StopRequest) SetTimeout(v *durationpb.Duration) {
	x.xxx_hidden_Timeout = v
}

func (x *StopRequest) HasTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timeout != nil
}

func (x *StopRequest) ClearTimeout() {
	x.xxx_hidden_Timeout = nil
}

type StopRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Shutdown mode: smart, fast, immediate
	Mode string
	// Timeout
	Timeout *durationpb.Duration
}

func (b0 StopRequest_builder) Build() *StopRequest {
	m0 := &StopRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Mode = b.Mode
	x.xxx_hidden_Timeout = b.Timeout
	return m0
}

type StopResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_pgctldservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *StopResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type StopResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Status message
	Message string
}

func (b0 StopResponse_builder) Build() *StopResponse {
	m0 := &StopResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

// Restart PostgreSQL server
type RestartRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mode      string                 `protobuf:"bytes,1,opt,name=mode,proto3"`
	xxx_hidden_Timeout   *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3"`
	xxx_hidden_Port      int32                  `protobuf:"varint,3,opt,name=port,proto3"`
	xxx_hidden_ExtraArgs []string               `protobuf:"bytes,4,rep,name=extra_args,json=extraArgs,proto3"`
	xxx_hidden_AsStandby bool                   `protobuf:"varint,5,opt,name=as_standby,json=asStandby,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_pgctldservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartRequest) GetMode() string {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return ""
}

func (x *RestartRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Timeout
	}
	return nil
}

func (x *RestartRequest) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *RestartRequest) GetExtraArgs() []string {
	if x != nil {
		return x.xxx_hidden_ExtraArgs
	}
	return nil
}

func (x *RestartRequest) GetAsStandby() bool {
	if x != nil {
		return x.xxx_hidden_AsStandby
	}
	return false
}

func (x *RestartRequest) SetMode(v string) {
	x.xxx_hidden_Mode = v
}

func (x *RestartRequest) SetTimeout(v *durationpb.Duration) {
	x.xxx_hidden_Timeout = v
}

func (x *RestartRequest) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

func (x *RestartRequest) SetExtraArgs(v []string) {
	x.xxx_hidden_ExtraArgs = v
}

func (x *RestartRequest) SetAsStandby(v bool) {
	x.xxx_hidden_AsStandby = v
}

func (x *RestartRequest) HasTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timeout != nil
}

func (x *RestartRequest) ClearTimeout() {
	x.xxx_hidden_Timeout = nil
}

type RestartRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Shutdown mode for stop phase: smart, fast, immediate
	Mode string
	// Timeout for stop phase
	Timeout *durationpb.Duration
	// Override default port for start phase
	Port      int32
	ExtraArgs []string
	// If true, creates standby.signal before restart (for demotion to standby)
	AsStandby bool
}

func (b0 RestartRequest_builder) Build() *RestartRequest {
	m0 := &RestartRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Mode = b.Mode
	x.xxx_hidden_Timeout = b.Timeout
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_ExtraArgs = b.ExtraArgs
	x.xxx_hidden_AsStandby = b.AsStandby
	return m0
}

type RestartResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pid     int32                  `protobuf:"varint,1,opt,name=pid,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_pgctldservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RestartResponse) GetPid() int32 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *RestartResponse) SetPid(v int32) {
	x.xxx_hidden_Pid = v
}

func (x *RestartResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type RestartResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Process ID of restarted PostgreSQL server
	Pid int32
	// Status message
	Message string
}

func (b0 RestartResponse_builder) Build() *RestartResponse {
	m0 := &RestartResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pid = b.Pid
	x.xxx_hidden_Message = b.Message
	return m0
}

// Reload PostgreSQL configuration
type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_pgctldservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ReloadConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ReloadConfigRequest_builder) Build() *ReloadConfigRequest {
	m0 := &ReloadConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ReloadConfigResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_pgctldservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReloadConfigResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *ReloadConfigResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type ReloadConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Status message
	Message string
}

func (b0 ReloadConfigResponse_builder) Build() *ReloadConfigResponse {
	m0 := &ReloadConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

// Get PostgreSQL server status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pgctldservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StatusRequest_builder) Build() *StatusRequest {
	m0 := &StatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type StatusResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status  ServerStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=pgctldservice.ServerStatus"`
	xxx_hidden_Pid     int32                  `protobuf:"varint,2,opt,name=pid,proto3"`
	xxx_hidden_Version string                 `protobuf:"bytes,3,opt,name=version,proto3"`
	xxx_hidden_Uptime  *durationpb.Duration   `protobuf:"bytes,4,opt,name=uptime,proto3"`
	xxx_hidden_DataDir string                 `protobuf:"bytes,5,opt,name=data_dir,json=dataDir,proto3"`
	xxx_hidden_Port    int32                  `protobuf:"varint,6,opt,name=port,proto3"`
	xxx_hidden_Host    string                 `protobuf:"bytes,7,opt,name=host,proto3"`
	xxx_hidden_Ready   bool                   `protobuf:"varint,8,opt,name=ready,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,9,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pgctldservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusResponse) GetStatus() ServerStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ServerStatus_UNKNOWN
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *StatusResponse) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Uptime
	}
	return nil
}

func (x *StatusResponse) GetDataDir() string {
	if x != nil {
		return x.xxx_hidden_DataDir
	}
	return ""
}

func (x *StatusResponse) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *StatusResponse) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *StatusResponse) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *StatusResponse) SetStatus(v ServerStatus) {
	x.xxx_hidden_Status = v
}

func (x *StatusResponse) SetPid(v int32) {
	x.xxx_hidden_Pid = v
}

func (x *StatusResponse) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *StatusResponse) SetUptime(v *durationpb.Duration) {
	x.xxx_hidden_Uptime = v
}

func (x *StatusResponse) SetDataDir(v string) {
	x.xxx_hidden_DataDir = v
}

func (x *StatusResponse) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

func (x *StatusResponse) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *StatusResponse) SetReady(v bool) {
	x.xxx_hidden_Ready = v
}

func (x *StatusResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *StatusResponse) HasUptime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Uptime != nil
}

func (x *StatusResponse) ClearUptime() {
	x.xxx_hidden_Uptime = nil
}

type StatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Server status
	Status ServerStatus
	// Process ID (if running)
	Pid int32
	// Server version (if available)
	Version string
	// Uptime (if running)
	Uptime *durationpb.Duration
	// Data directory path
	DataDir string
	// Port number
	Port int32
	// Host address
	Host string
	// Is server ready to accept connections
	Ready bool
	// Additional status information
	Message string
}

func (b0 StatusResponse_builder) Build() *StatusResponse {
	m0 := &StatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Pid = b.Pid
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Uptime = b.Uptime
	x.xxx_hidden_DataDir = b.DataDir
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Ready = b.Ready
	x.xxx_hidden_Message = b.Message
	return m0
}

// Get server version information
type VersionRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Host     string                 `protobuf:"bytes,1,opt,name=host,proto3"`
	xxx_hidden_Port     int32                  `protobuf:"varint,2,opt,name=port,proto3"`
	xxx_hidden_Database string                 `protobuf:"bytes,3,opt,name=database,proto3"`
	xxx_hidden_User     string                 `protobuf:"bytes,4,opt,name=user,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_pgctldservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VersionRequest) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *VersionRequest) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *VersionRequest) GetDatabase() string {
	if x != nil {
		return x.xxx_hidden_Database
	}
	return ""
}

func (x *VersionRequest) GetUser() string {
	if x != nil {
		return x.xxx_hidden_User
	}
	return ""
}

func (x *VersionRequest) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *VersionRequest) SetPort(v int32) {
	x.xxx_hidden_Port = v
}

func (x *VersionRequest) SetDatabase(v string) {
	x.xxx_hidden_Database = v
}

func (x *VersionRequest) SetUser(v string) {
	x.xxx_hidden_User = v
}

type VersionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Override default connection parameters
	Host     string
	Port     int32
	Database string
	User     string
}

func (b0 VersionRequest_builder) Build() *VersionRequest {
	m0 := &VersionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_Database = b.Database
	x.xxx_hidden_User = b.User
	return m0
}

type VersionResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version string                 `protobuf:"bytes,1,opt,name=version,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pgctldservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *VersionResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *VersionResponse) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *VersionResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type VersionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// PostgreSQL version string
	Version string
	// Status message
	Message string
}

func (b0 VersionResponse_builder) Build() *VersionResponse {
	m0 := &VersionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Message = b.Message
	return m0
}

// Initialize data directory
type InitDataDirRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AuthLocal string                 `protobuf:"bytes,1,opt,name=auth_local,json=authLocal,proto3"`
	xxx_hidden_AuthHost  string                 `protobuf:"bytes,2,opt,name=auth_host,json=authHost,proto3"`
	xxx_hidden_ExtraArgs []string               `protobuf:"bytes,3,rep,name=extra_args,json=extraArgs,proto3"`
	xxx_hidden_PgPwfile  string                 `protobuf:"bytes,4,opt,name=pg_pwfile,json=pgPwfile,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InitDataDirRequest) Reset() {
	*x = InitDataDirRequest{}
	mi := &file_pgctldservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDataDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDataDirRequest) ProtoMessage() {}

func (x *InitDataDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitDataDirRequest) GetAuthLocal() string {
	if x != nil {
		return x.xxx_hidden_AuthLocal
	}
	return ""
}

func (x *InitDataDirRequest) GetAuthHost() string {
	if x != nil {
		return x.xxx_hidden_AuthHost
	}
	return ""
}

func (x *InitDataDirRequest) GetExtraArgs() []string {
	if x != nil {
		return x.xxx_hidden_ExtraArgs
	}
	return nil
}

func (x *InitDataDirRequest) GetPgPwfile() string {
	if x != nil {
		return x.xxx_hidden_PgPwfile
	}
	return ""
}

func (x *InitDataDirRequest) SetAuthLocal(v string) {
	x.xxx_hidden_AuthLocal = v
}

func (x *InitDataDirRequest) SetAuthHost(v string) {
	x.xxx_hidden_AuthHost = v
}

func (x *InitDataDirRequest) SetExtraArgs(v []string) {
	x.xxx_hidden_ExtraArgs = v
}

func (x *InitDataDirRequest) SetPgPwfile(v string) {
	x.xxx_hidden_PgPwfile = v
}

type InitDataDirRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Authentication method for local connections
	AuthLocal string
	// Authentication method for host connections
	AuthHost string
	// Additional initdb arguments
	ExtraArgs []string
	// Path to password file for PostgreSQL user authentication
	PgPwfile string
}

func (b0 InitDataDirRequest_builder) Build() *InitDataDirRequest {
	m0 := &InitDataDirRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AuthLocal = b.AuthLocal
	x.xxx_hidden_AuthHost = b.AuthHost
	x.xxx_hidden_ExtraArgs = b.ExtraArgs
	x.xxx_hidden_PgPwfile = b.PgPwfile
	return m0
}

type InitDataDirResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitDataDirResponse) Reset() {
	*x = InitDataDirResponse{}
	mi := &file_pgctldservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDataDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDataDirResponse) ProtoMessage() {}

func (x *InitDataDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitDataDirResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *InitDataDirResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type InitDataDirResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Status message
	Message string
}

func (b0 InitDataDirResponse_builder) Build() *InitDataDirResponse {
	m0 := &InitDataDirResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

// PgRewind rewinds a PostgreSQL data directory to an earlier point in the timeline
type PgRewindRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SourceServer string                 `protobuf:"bytes,1,opt,name=source_server,json=sourceServer,proto3"`
	xxx_hidden_DryRun       bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3"`
	xxx_hidden_ExtraArgs    []string               `protobuf:"bytes,3,rep,name=extra_args,json=extraArgs,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PgRewindRequest) Reset() {
	*x = PgRewindRequest{}
	mi := &file_pgctldservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgRewindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgRewindRequest) ProtoMessage() {}

func (x *PgRewindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PgRewindRequest) GetSourceServer() string {
	if x != nil {
		return x.xxx_hidden_SourceServer
	}
	return ""
}

func (x *PgRewindRequest) GetDryRun() bool {
	if x != nil {
		return x.xxx_hidden_DryRun
	}
	return false
}

func (x *PgRewindRequest) GetExtraArgs() []string {
	if x != nil {
		return x.xxx_hidden_ExtraArgs
	}
	return nil
}

func (x *PgRewindRequest) SetSourceServer(v string) {
	x.xxx_hidden_SourceServer = v
}

func (x *PgRewindRequest) SetDryRun(v bool) {
	x.xxx_hidden_DryRun = v
}

func (x *PgRewindRequest) SetExtraArgs(v []string) {
	x.xxx_hidden_ExtraArgs = v
}

type PgRewindRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Source server connection string (--source-server)
	// Format: "host=<hostname> port=<port> user=<user> dbname=<dbname>"
	SourceServer string
	// Perform a dry run without making changes (--dry-run)
	DryRun bool
	// Additional pg_rewind command line arguments
	ExtraArgs []string
}

func (b0 PgRewindRequest_builder) Build() *PgRewindRequest {
	m0 := &PgRewindRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SourceServer = b.SourceServer
	x.xxx_hidden_DryRun = b.DryRun
	x.xxx_hidden_ExtraArgs = b.ExtraArgs
	return m0
}

type PgRewindResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgRewindResponse) Reset() {
	*x = PgRewindResponse{}
	mi := &file_pgctldservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgRewindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgRewindResponse) ProtoMessage() {}

func (x *PgRewindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pgctldservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PgRewindResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PgRewindResponse_builder) Build() *PgRewindResponse {
	m0 := &PgRewindResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_pgctldservice_proto protoreflect.FileDescriptor

const file_pgctldservice_proto_rawDesc = "" +
	"\n" +
	"\x13pgctldservice.proto\x12\rpgctldservice\x1a\x1egoogle/protobuf/duration.proto\"A\n" +
	"\fStartRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x02 \x03(\tR\textraArgs\";\n" +
	"\rStartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\vStopRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xab\x01\n" +
	"\x0eRestartRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x04 \x03(\tR\textraArgs\x12\x1d\n" +
	"\n" +
	"as_standby\x18\x05 \x01(\bR\tasStandby\"=\n" +
	"\x0fRestartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13ReloadConfigRequest\"0\n" +
	"\x14ReloadConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\x97\x02\n" +
	"\x0eStatusResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.pgctldservice.ServerStatusR\x06status\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x121\n" +
	"\x06uptime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12\x19\n" +
	"\bdata_dir\x18\x05 \x01(\tR\adataDir\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x14\n" +
	"\x05ready\x18\b \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"h\n" +
	"\x0eVersionRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"E\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8c\x01\n" +
	"\x12InitDataDirRequest\x12\x1d\n" +
	"\n" +
	"auth_local\x18\x01 \x01(\tR\tauthLocal\x12\x1b\n" +
	"\tauth_host\x18\x02 \x01(\tR\bauthHost\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x03 \x03(\tR\textraArgs\x12\x1b\n" +
	"\tpg_pwfile\x18\x04 \x01(\tR\bpgPwfile\"/\n" +
	"\x13InitDataDirResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"n\n" +
	"\x0fPgRewindRequest\x12#\n" +
	"\rsource_server\x18\x01 \x01(\tR\fsourceServer\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x03 \x03(\tR\textraArgs\"\x12\n" +
	"\x10PgRewindResponse*f\n" +
	"\fServerStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\f\n" +
	"\bSTOPPING\x10\x04\x12\x13\n" +
	"\x0fNOT_INITIALIZED\x10\x052\xe4\x04\n" +
	"\x06PgCtld\x12B\n" +
	"\x05Start\x12\x1b.pgctldservice.StartRequest\x1a\x1c.pgctldservice.StartResponse\x12?\n" +
	"\x04Stop\x12\x1a.pgctldservice.StopRequest\x1a\x1b.pgctldservice.StopResponse\x12H\n" +
	"\aRestart\x12\x1d.pgctldservice.RestartRequest\x1a\x1e.pgctldservice.RestartResponse\x12W\n" +
	"\fReloadConfig\x12\".pgctldservice.ReloadConfigRequest\x1a#.pgctldservice.ReloadConfigResponse\x12E\n" +
	"\x06Status\x12\x1c.pgctldservice.StatusRequest\x1a\x1d.pgctldservice.StatusResponse\x12H\n" +
	"\aVersion\x12\x1d.pgctldservice.VersionRequest\x1a\x1e.pgctldservice.VersionResponse\x12T\n" +
	"\vInitDataDir\x12!.pgctldservice.InitDataDirRequest\x1a\".pgctldservice.InitDataDirResponse\x12K\n" +
	"\bPgRewind\x12\x1e.pgctldservice.PgRewindRequest\x1a\x1f.pgctldservice.PgRewindResponseB4Z2github.com/multigres/multigres/go/pb/pgctldserviceb\x06proto3"

var file_pgctldservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pgctldservice_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pgctldservice_proto_goTypes = []any{
	(ServerStatus)(0),            // 0: pgctldservice.ServerStatus
	(*StartRequest)(nil),         // 1: pgctldservice.StartRequest
	(*StartResponse)(nil),        // 2: pgctldservice.StartResponse
	(*StopRequest)(nil),          // 3: pgctldservice.StopRequest
	(*StopResponse)(nil),         // 4: pgctldservice.StopResponse
	(*RestartRequest)(nil),       // 5: pgctldservice.RestartRequest
	(*RestartResponse)(nil),      // 6: pgctldservice.RestartResponse
	(*ReloadConfigRequest)(nil),  // 7: pgctldservice.ReloadConfigRequest
	(*ReloadConfigResponse)(nil), // 8: pgctldservice.ReloadConfigResponse
	(*StatusRequest)(nil),        // 9: pgctldservice.StatusRequest
	(*StatusResponse)(nil),       // 10: pgctldservice.StatusResponse
	(*VersionRequest)(nil),       // 11: pgctldservice.VersionRequest
	(*VersionResponse)(nil),      // 12: pgctldservice.VersionResponse
	(*InitDataDirRequest)(nil),   // 13: pgctldservice.InitDataDirRequest
	(*InitDataDirResponse)(nil),  // 14: pgctldservice.InitDataDirResponse
	(*PgRewindRequest)(nil),      // 15: pgctldservice.PgRewindRequest
	(*PgRewindResponse)(nil),     // 16: pgctldservice.PgRewindResponse
	(*durationpb.Duration)(nil),  // 17: google.protobuf.Duration
}
var file_pgctldservice_proto_depIdxs = []int32{
	17, // 0: pgctldservice.StopRequest.timeout:type_name -> google.protobuf.Duration
	17, // 1: pgctldservice.RestartRequest.timeout:type_name -> google.protobuf.Duration
	0,  // 2: pgctldservice.StatusResponse.status:type_name -> pgctldservice.ServerStatus
	17, // 3: pgctldservice.StatusResponse.uptime:type_name -> google.protobuf.Duration
	1,  // 4: pgctldservice.PgCtld.Start:input_type -> pgctldservice.StartRequest
	3,  // 5: pgctldservice.PgCtld.Stop:input_type -> pgctldservice.StopRequest
	5,  // 6: pgctldservice.PgCtld.Restart:input_type -> pgctldservice.RestartRequest
	7,  // 7: pgctldservice.PgCtld.ReloadConfig:input_type -> pgctldservice.ReloadConfigRequest
	9,  // 8: pgctldservice.PgCtld.Status:input_type -> pgctldservice.StatusRequest
	11, // 9: pgctldservice.PgCtld.Version:input_type -> pgctldservice.VersionRequest
	13, // 10: pgctldservice.PgCtld.InitDataDir:input_type -> pgctldservice.InitDataDirRequest
	15, // 11: pgctldservice.PgCtld.PgRewind:input_type -> pgctldservice.PgRewindRequest
	2,  // 12: pgctldservice.PgCtld.Start:output_type -> pgctldservice.StartResponse
	4,  // 13: pgctldservice.PgCtld.Stop:output_type -> pgctldservice.StopResponse
	6,  // 14: pgctldservice.PgCtld.Restart:output_type -> pgctldservice.RestartResponse
	8,  // 15: pgctldservice.PgCtld.ReloadConfig:output_type -> pgctldservice.ReloadConfigResponse
	10, // 16: pgctldservice.PgCtld.Status:output_type -> pgctldservice.StatusResponse
	12, // 17: pgctldservice.PgCtld.Version:output_type -> pgctldservice.VersionResponse
	14, // 18: pgctldservice.PgCtld.InitDataDir:output_type -> pgctldservice.InitDataDirResponse
	16, // 19: pgctldservice.PgCtld.PgRewind:output_type -> pgctldservice.PgRewindResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pgctldservice_proto_init() }
func file_pgctldservice_proto_init() {
	if File_pgctldservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgctldservice_proto_rawDesc), len(file_pgctldservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pgctldservice_proto_goTypes,
		DependencyIndexes: file_pgctldservice_proto_depIdxs,
		EnumInfos:         file_pgctldservice_proto_enumTypes,
		MessageInfos:      file_pgctldservice_proto_msgTypes,
	}.Build()
	File_pgctldservice_proto = out.File
	file_pgctldservice_proto_goTypes = nil
	file_pgctldservice_proto_depIdxs = nil
}
