// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusdata.proto

package consensusdata

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostgresRole identifies the role of the PostgreSQL instance on a pooler node.
type PostgresRole int32

const (
	PostgresRole_POSTGRES_ROLE_UNSPECIFIED PostgresRole = 0
	PostgresRole_POSTGRES_ROLE_PRIMARY     PostgresRole = 1
	PostgresRole_POSTGRES_ROLE_REPLICA     PostgresRole = 2
)

// Enum value maps for PostgresRole.
var (
	PostgresRole_name = map[int32]string{
		0: "POSTGRES_ROLE_UNSPECIFIED",
		1: "POSTGRES_ROLE_PRIMARY",
		2: "POSTGRES_ROLE_REPLICA",
	}
	PostgresRole_value = map[string]int32{
		"POSTGRES_ROLE_UNSPECIFIED": 0,
		"POSTGRES_ROLE_PRIMARY":     1,
		"POSTGRES_ROLE_REPLICA":     2,
	}
)

func (x PostgresRole) Enum() *PostgresRole {
	p := new(PostgresRole)
	*p = x
	return p
}

func (x PostgresRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostgresRole) Descriptor() protoreflect.EnumDescriptor {
	return file_consensusdata_proto_enumTypes[0].Descriptor()
}

func (PostgresRole) Type() protoreflect.EnumType {
	return &file_consensusdata_proto_enumTypes[0]
}

func (x PostgresRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostgresRole.Descriptor instead.
func (PostgresRole) EnumDescriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{0}
}

// RuleNumber uniquely identifies a shard rule — the outcome of a coordinator
// writing a cluster state change to rule_history. Every change (promotion,
// cohort membership, durability policy) produces a new RuleNumber.
//
// Compared lexicographically: higher coordinator_term takes precedence; within
// the same coordinator_term, higher leader_subterm takes precedence. leader_subterm
// resets to 0 when coordinator_term increases, so subterms alone are not
// globally unique.
type RuleNumber struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorTerm int64                  `protobuf:"varint,1,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	LeaderSubterm   int64                  `protobuf:"varint,2,opt,name=leader_subterm,json=leaderSubterm,proto3" json:"leader_subterm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleNumber) Reset() {
	*x = RuleNumber{}
	mi := &file_consensusdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleNumber) ProtoMessage() {}

func (x *RuleNumber) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleNumber.ProtoReflect.Descriptor instead.
func (*RuleNumber) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{0}
}

func (x *RuleNumber) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *RuleNumber) GetLeaderSubterm() int64 {
	if x != nil {
		return x.LeaderSubterm
	}
	return 0
}

// ShardRule is the complete, authoritative description of shard state at a
// specific rule number. Primary identity, cohort membership, and durability
// policy are only meaningful together and relative to the rule that established
// them.
type ShardRule struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RuleNumber *RuleNumber            `protobuf:"bytes,1,opt,name=rule_number,json=ruleNumber,proto3" json:"rule_number,omitempty"`
	// The postgres primary for this rule, through which all transactions (including rules) are
	// written to the WAL.
	PrimaryId     *clustermetadata.ID   `protobuf:"bytes,2,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	CohortMembers []*clustermetadata.ID `protobuf:"bytes,3,rep,name=cohort_members,json=cohortMembers,proto3" json:"cohort_members,omitempty"`
	// What nodes need to acknowledge a write before it's considered durable.
	DurabilityPolicy *clustermetadata.DurabilityPolicy `protobuf:"bytes,4,opt,name=durability_policy,json=durabilityPolicy,proto3" json:"durability_policy,omitempty"`
	// Which coordinator or pooler facilitated applying the rule.
	CoordinatorId *clustermetadata.ID `protobuf:"bytes,5,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	// At what time the coordinator or pooler began trying to apply the rule,
	// from the coordinator's perspective.
	CreationTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRule) Reset() {
	*x = ShardRule{}
	mi := &file_consensusdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRule) ProtoMessage() {}

func (x *ShardRule) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRule.ProtoReflect.Descriptor instead.
func (*ShardRule) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{1}
}

func (x *ShardRule) GetRuleNumber() *RuleNumber {
	if x != nil {
		return x.RuleNumber
	}
	return nil
}

func (x *ShardRule) GetPrimaryId() *clustermetadata.ID {
	if x != nil {
		return x.PrimaryId
	}
	return nil
}

func (x *ShardRule) GetCohortMembers() []*clustermetadata.ID {
	if x != nil {
		return x.CohortMembers
	}
	return nil
}

func (x *ShardRule) GetDurabilityPolicy() *clustermetadata.DurabilityPolicy {
	if x != nil {
		return x.DurabilityPolicy
	}
	return nil
}

func (x *ShardRule) GetCoordinatorId() *clustermetadata.ID {
	if x != nil {
		return x.CoordinatorId
	}
	return nil
}

func (x *ShardRule) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

// PoolerPosition describes a pooler's committed position in logical and physical
// time. It captures the highest ShardRule this pooler has replicated (or written,
// for a primary) and the latest WAL position.
//
// Used in RecruitResponse so the coordinator can determine which pooler is most
// advanced when selecting a promotion candidate.
//
// Comparison: prefer the pooler with the higher rule (coordinator_term first,
// then leader_subterm). Break ties by LSN.
type PoolerPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The highest shard rule this pooler has committed to local WAL.
	Rule *ShardRule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	// The current real-time WAL head at the time of reading. Note that this is likely
	// beyond the LSN at which the rule was committed. For a primary: pg_current_wal_lsn().
	// For a standby: pg_last_wal_receive_lsn() (or pg_last_wal_replay_lsn() if receive is null).
	Lsn           string `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolerPosition) Reset() {
	*x = PoolerPosition{}
	mi := &file_consensusdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolerPosition) ProtoMessage() {}

func (x *PoolerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolerPosition.ProtoReflect.Descriptor instead.
func (*PoolerPosition) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{2}
}

func (x *PoolerPosition) GetRule() *ShardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *PoolerPosition) GetLsn() string {
	if x != nil {
		return x.Lsn
	}
	return ""
}

// WAL position for tracking replication state during candidate selection.
type WALPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For primary: current write position from pg_current_wal_lsn()
	// For standby: empty (use last_receive_lsn and last_replay_lsn instead)
	CurrentLsn string `protobuf:"bytes,1,opt,name=current_lsn,json=currentLsn,proto3" json:"current_lsn,omitempty"`
	// For standby: last WAL position received from pg_last_wal_receive_lsn()
	// For primary: empty
	LastReceiveLsn string `protobuf:"bytes,2,opt,name=last_receive_lsn,json=lastReceiveLsn,proto3" json:"last_receive_lsn,omitempty"`
	// For standby: last WAL position replayed from pg_last_wal_replay_lsn()
	// For primary: empty
	LastReplayLsn string `protobuf:"bytes,3,opt,name=last_replay_lsn,json=lastReplayLsn,proto3" json:"last_replay_lsn,omitempty"`
	// Timestamp when this position was recorded
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// PostgreSQL timeline ID from pg_control_checkpoint().
	// Retained for observability and as a secondary safety check during candidate selection.
	TimelineId int64 `protobuf:"varint,5,opt,name=timeline_id,json=timelineId,proto3" json:"timeline_id,omitempty"`
	// Term number from the most recent multigres.leadership_history record, read
	// after WAL replay stabilizes during revoke. Used as the primary criterion for
	// candidate selection: a node that has replicated a higher consensus term has
	// applied more of the agreed WAL history, regardless of LSN.
	// LSN is used as a tiebreaker only when both term and timeline are equal.
	// 0 if the leadership_history table is empty (e.g. pre-bootstrap).
	LeadershipTerm int64 `protobuf:"varint,6,opt,name=leadership_term,json=leadershipTerm,proto3" json:"leadership_term,omitempty"`
	// Cohort members from the most recent multigres.leadership_history record
	// (application-name strings, same encoding as the table's cohort_members JSONB
	// column). Empty if the table is empty.
	CohortMembers []string `protobuf:"bytes,7,rep,name=cohort_members,json=cohortMembers,proto3" json:"cohort_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALPosition) Reset() {
	*x = WALPosition{}
	mi := &file_consensusdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALPosition) ProtoMessage() {}

func (x *WALPosition) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALPosition.ProtoReflect.Descriptor instead.
func (*WALPosition) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{3}
}

func (x *WALPosition) GetCurrentLsn() string {
	if x != nil {
		return x.CurrentLsn
	}
	return ""
}

func (x *WALPosition) GetLastReceiveLsn() string {
	if x != nil {
		return x.LastReceiveLsn
	}
	return ""
}

func (x *WALPosition) GetLastReplayLsn() string {
	if x != nil {
		return x.LastReplayLsn
	}
	return ""
}

func (x *WALPosition) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WALPosition) GetTimelineId() int64 {
	if x != nil {
		return x.TimelineId
	}
	return 0
}

func (x *WALPosition) GetLeadershipTerm() int64 {
	if x != nil {
		return x.LeadershipTerm
	}
	return 0
}

func (x *WALPosition) GetCohortMembers() []string {
	if x != nil {
		return x.CohortMembers
	}
	return nil
}

// TermRevocation records that this pooler has revoked participation in all terms
// strictly below revoked_below_term. Two things are revoked:
//
//  1. Consensus participation: the pooler will refuse Recruit or other coordinator
//     requests for any term < revoked_below_term, and for revoked_below_term itself
//     from a different coordinator than accepted_coordinator_id.
//
//  2. Replication participation: a revoked primary must stop accepting writes; a
//     revoked replica must clear primary_conninfo. Replication participation resumes
//     once the pooler's highest known decision reaches or exceeds revoked_below_term
//     (i.e. the rule for that term has replicated through).
//
// Re-sending an identical recruitment is idempotent. A higher-term recruitment
// supersedes lower ones automatically.
//
// Persisted to local disk before responding; survives process restarts.
type TermRevocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All terms strictly below this value are revoked. The pooler has accepted
	// the coordinator's exclusive right to act at this term.
	RevokedBelowTerm int64 `protobuf:"varint,1,opt,name=revoked_below_term,json=revokedBelowTerm,proto3" json:"revoked_below_term,omitempty"`
	// The coordinator (multiorch instance) that recruited this revocation.
	// Retained for idempotency: the same coordinator at the same term is re-accepted;
	// a different coordinator at the same term is refused.
	AcceptedCoordinatorId *clustermetadata.ID `protobuf:"bytes,2,opt,name=accepted_coordinator_id,json=acceptedCoordinatorId,proto3" json:"accepted_coordinator_id,omitempty"`
	// When the coordinator created this term, set by the coordinator before
	// recruiting. All poolers that accept the same recruitment store the same value.
	CoordinatorInitiatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=coordinator_initiated_at,json=coordinatorInitiatedAt,proto3" json:"coordinator_initiated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TermRevocation) Reset() {
	*x = TermRevocation{}
	mi := &file_consensusdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermRevocation) ProtoMessage() {}

func (x *TermRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermRevocation.ProtoReflect.Descriptor instead.
func (*TermRevocation) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{4}
}

func (x *TermRevocation) GetRevokedBelowTerm() int64 {
	if x != nil {
		return x.RevokedBelowTerm
	}
	return 0
}

func (x *TermRevocation) GetAcceptedCoordinatorId() *clustermetadata.ID {
	if x != nil {
		return x.AcceptedCoordinatorId
	}
	return nil
}

func (x *TermRevocation) GetCoordinatorInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CoordinatorInitiatedAt
	}
	return nil
}

// RecruitmentPosition captures the WAL position of the proposal leader at
// the time of recruitment. Embedded in CoordinatorProposal so the proposal
// leader can validate it still holds the required state before committing
// to becoming primary.
type RecruitmentPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rule number the proposal leader must have committed to WAL.
	RuleNumber *RuleNumber `protobuf:"bytes,1,opt,name=rule_number,json=ruleNumber,proto3" json:"rule_number,omitempty"`
	// The minimum WAL position (LSN) the proposal leader must have replayed.
	Lsn           string `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecruitmentPosition) Reset() {
	*x = RecruitmentPosition{}
	mi := &file_consensusdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecruitmentPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitmentPosition) ProtoMessage() {}

func (x *RecruitmentPosition) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitmentPosition.ProtoReflect.Descriptor instead.
func (*RecruitmentPosition) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{5}
}

func (x *RecruitmentPosition) GetRuleNumber() *RuleNumber {
	if x != nil {
		return x.RuleNumber
	}
	return nil
}

func (x *RecruitmentPosition) GetLsn() string {
	if x != nil {
		return x.Lsn
	}
	return ""
}

// ProposalLeader bundles the identity and connection information for the pooler
// selected to become the new primary during a Propose() operation.
type ProposalLeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity of the selected primary.
	Id *clustermetadata.ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Hostname and postgres port. Replicas use these to configure
	// primary_conninfo when processing a Propose() RPC.
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	PostgresPort  int32  `protobuf:"varint,3,opt,name=postgres_port,json=postgresPort,proto3" json:"postgres_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalLeader) Reset() {
	*x = ProposalLeader{}
	mi := &file_consensusdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalLeader) ProtoMessage() {}

func (x *ProposalLeader) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalLeader.ProtoReflect.Descriptor instead.
func (*ProposalLeader) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{6}
}

func (x *ProposalLeader) GetId() *clustermetadata.ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ProposalLeader) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProposalLeader) GetPostgresPort() int32 {
	if x != nil {
		return x.PostgresPort
	}
	return 0
}

// CoordinatorProposal is the authority proof a coordinator sends to all poolers
// during Propose operations. It combines the term revocation (proof of
// recruitment authority), the selected proposal leader, the shard rule to apply,
// and the recruitment position (minimum WAL state required at the proposal leader).
//
// All poolers receive this in a Propose() RPC. Each pooler self-identifies
// by comparing proposal_leader.id to its own ID:
//   - If proposal_leader.id == self: validate recruitment_position against local
//     state, commit to becoming primary, configure sync replication, write rule history
//   - Otherwise: configure replication to proposal_leader.host/postgres_port and
//     resume streaming
//
// Not persisted to disk; held in memory only. A new coordinator can rediscover
// an in-flight proposal by inspecting the in_progress_proposal field of
// ConsensusStatus across recruited nodes.
type CoordinatorProposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Proof of recruitment authority. Must match the TermRevocation this pooler
	// accepted during Recruit().
	TermRevocation *TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	// The pooler selected to become the new primary, with connection information
	// for replicas to configure replication.
	ProposalLeader *ProposalLeader `protobuf:"bytes,2,opt,name=proposal_leader,json=proposalLeader,proto3" json:"proposal_leader,omitempty"`
	// The shard rule to apply under this proposal.
	ProposedRule *ShardRule `protobuf:"bytes,3,opt,name=proposed_rule,json=proposedRule,proto3" json:"proposed_rule,omitempty"`
	// The WAL position the coordinator observed at the proposal leader during
	// recruitment. The proposal leader validates it has not regressed before
	// committing to primary. Replicas use this field to identify the proposal
	// leader's expected rule for replication setup.
	RecruitmentPosition *RecruitmentPosition `protobuf:"bytes,4,opt,name=recruitment_position,json=recruitmentPosition,proto3" json:"recruitment_position,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CoordinatorProposal) Reset() {
	*x = CoordinatorProposal{}
	mi := &file_consensusdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorProposal) ProtoMessage() {}

func (x *CoordinatorProposal) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorProposal.ProtoReflect.Descriptor instead.
func (*CoordinatorProposal) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{7}
}

func (x *CoordinatorProposal) GetTermRevocation() *TermRevocation {
	if x != nil {
		return x.TermRevocation
	}
	return nil
}

func (x *CoordinatorProposal) GetProposalLeader() *ProposalLeader {
	if x != nil {
		return x.ProposalLeader
	}
	return nil
}

func (x *CoordinatorProposal) GetProposedRule() *ShardRule {
	if x != nil {
		return x.ProposedRule
	}
	return nil
}

func (x *CoordinatorProposal) GetRecruitmentPosition() *RecruitmentPosition {
	if x != nil {
		return x.RecruitmentPosition
	}
	return nil
}

// ConsensusStatus is a pooler's complete view of its position in the distributed
// system. It combines layers with different durability and precision guarantees:
//
//  1. term_revocation (disk-backed, authoritative)
//     Written to local disk before responding; survives process restarts.
//     Records the highest coordinator term accepted and the coordinator's identity.
//
//  2. current_position (postgres-WAL-backed, authoritative)
//     The highest ShardRule committed to local WAL (from rule_history) and the
//     current LSN. Authoritative because postgres WAL is durable and ordered.
//
//  3. in_progress_proposal (in-memory only)
//     Set when the pooler accepts a Propose() call. Lets a new coordinator
//     rediscover an in-flight proposal after a coordinator crash. Cleared when a
//     newer proposal or Inform() arrives.
//
//  4. highest_known_decision (in-memory only)
//     Set when the pooler receives an Inform() call with a committed shard rule.
//     May be ahead of current_position if the rule hasn't been applied to WAL yet.
type ConsensusStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// term_revocation records the highest coordinator term this pooler has revoked for.
	TermRevocation *TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	// current_position is the highest rule this pooler has committed to local WAL
	// and the latest WAL position.
	CurrentPosition *PoolerPosition `protobuf:"bytes,2,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	// id identifies the pooler that produced this status. Makes ConsensusStatus
	// self-describing when passed around without a surrounding envelope.
	Id *clustermetadata.ID `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// in_progress_proposal is the most recent CoordinatorProposal this pooler has
	// accepted via Propose(). In-memory only; cleared on restart or when superseded.
	InProgressProposal *CoordinatorProposal `protobuf:"bytes,5,opt,name=in_progress_proposal,json=inProgressProposal,proto3" json:"in_progress_proposal,omitempty"`
	// highest_known_decision is the most recent committed shard rule this pooler
	// is aware of, set by Inform(). In-memory only; may be ahead of current_position.
	HighestKnownDecision *ShardRule `protobuf:"bytes,6,opt,name=highest_known_decision,json=highestKnownDecision,proto3" json:"highest_known_decision,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConsensusStatus) Reset() {
	*x = ConsensusStatus{}
	mi := &file_consensusdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusStatus) ProtoMessage() {}

func (x *ConsensusStatus) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusStatus.ProtoReflect.Descriptor instead.
func (*ConsensusStatus) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{8}
}

func (x *ConsensusStatus) GetTermRevocation() *TermRevocation {
	if x != nil {
		return x.TermRevocation
	}
	return nil
}

func (x *ConsensusStatus) GetCurrentPosition() *PoolerPosition {
	if x != nil {
		return x.CurrentPosition
	}
	return nil
}

func (x *ConsensusStatus) GetId() *clustermetadata.ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ConsensusStatus) GetInProgressProposal() *CoordinatorProposal {
	if x != nil {
		return x.InProgressProposal
	}
	return nil
}

func (x *ConsensusStatus) GetHighestKnownDecision() *ShardRule {
	if x != nil {
		return x.HighestKnownDecision
	}
	return nil
}

// StatusRequest queries the current consensus status of a pooler.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shard ID to query status for
	ShardId       string `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_consensusdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{9}
}

func (x *StatusRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

// StatusResponse is returned by the Status RPC.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pooler ID
	PoolerId string `protobuf:"bytes,1,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// Current WAL position
	WalPosition *WALPosition `protobuf:"bytes,4,opt,name=wal_position,json=walPosition,proto3" json:"wal_position,omitempty"`
	// Whether Postgres is healthy and reachable
	IsHealthy bool `protobuf:"varint,5,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	// Whether this pooler is eligible to be a leader
	IsEligible bool `protobuf:"varint,6,opt,name=is_eligible,json=isEligible,proto3" json:"is_eligible,omitempty"`
	// Cell identifier
	Cell string `protobuf:"bytes,7,opt,name=cell,proto3" json:"cell,omitempty"`
	// Current role of the PostgreSQL instance on this node.
	Role PostgresRole `protobuf:"varint,9,opt,name=role,proto3,enum=consensusdata.PostgresRole" json:"role,omitempty"`
	// Timeline information for divergence detection
	TimelineInfo *TimelineInfo `protobuf:"bytes,10,opt,name=timeline_info,json=timelineInfo,proto3" json:"timeline_info,omitempty"`
	// The pooler's current consensus status: its term revocation, committed
	// rule position, in-progress proposal, and highest known decision.
	// Authoritative view of where this pooler stands in the distributed system.
	ConsensusStatus *ConsensusStatus `protobuf:"bytes,12,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	// Best-effort operational fitness signals for this node. These signals are
	// in-memory and may be absent after a process restart. Coordinators treat
	// absence as "unknown," not "unfit."
	AvailabilityStatus *clustermetadata.AvailabilityStatus `protobuf:"bytes,13,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_consensusdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetPoolerId() string {
	if x != nil {
		return x.PoolerId
	}
	return ""
}

func (x *StatusResponse) GetWalPosition() *WALPosition {
	if x != nil {
		return x.WalPosition
	}
	return nil
}

func (x *StatusResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *StatusResponse) GetIsEligible() bool {
	if x != nil {
		return x.IsEligible
	}
	return false
}

func (x *StatusResponse) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *StatusResponse) GetRole() PostgresRole {
	if x != nil {
		return x.Role
	}
	return PostgresRole_POSTGRES_ROLE_UNSPECIFIED
}

func (x *StatusResponse) GetTimelineInfo() *TimelineInfo {
	if x != nil {
		return x.TimelineInfo
	}
	return nil
}

func (x *StatusResponse) GetConsensusStatus() *ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

func (x *StatusResponse) GetAvailabilityStatus() *clustermetadata.AvailabilityStatus {
	if x != nil {
		return x.AvailabilityStatus
	}
	return nil
}

// TimelineInfo captures PostgreSQL timeline information for divergence detection.
type TimelineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimelineId    int64                  `protobuf:"varint,1,opt,name=timeline_id,json=timelineId,proto3" json:"timeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineInfo) Reset() {
	*x = TimelineInfo{}
	mi := &file_consensusdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineInfo) ProtoMessage() {}

func (x *TimelineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineInfo.ProtoReflect.Descriptor instead.
func (*TimelineInfo) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{11}
}

func (x *TimelineInfo) GetTimelineId() int64 {
	if x != nil {
		return x.TimelineId
	}
	return 0
}

// RecruitRequest is sent by the coordinator to all poolers during leader appointment.
// The pooler accepts the term revocation if its revoked_below_term is >= its current
// revoked_below_term, then executes revocation (demotes primary or pauses standby
// replication) to freeze WAL positions for candidate selection.
type RecruitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The term revocation to apply.
	TermRevocation *TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecruitRequest) Reset() {
	*x = RecruitRequest{}
	mi := &file_consensusdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecruitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitRequest) ProtoMessage() {}

func (x *RecruitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitRequest.ProtoReflect.Descriptor instead.
func (*RecruitRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{12}
}

func (x *RecruitRequest) GetTermRevocation() *TermRevocation {
	if x != nil {
		return x.TermRevocation
	}
	return nil
}

// RecruitResponse is returned after successful recruitment.
// Contains the pooler's consensus status after revocation, including the
// frozen WAL position used for candidate selection.
type RecruitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The pooler's consensus status after recruitment.
	// current_position reflects the frozen WAL position post-revocation.
	ConsensusStatus *ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecruitResponse) Reset() {
	*x = RecruitResponse{}
	mi := &file_consensusdata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecruitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecruitResponse) ProtoMessage() {}

func (x *RecruitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecruitResponse.ProtoReflect.Descriptor instead.
func (*RecruitResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{13}
}

func (x *RecruitResponse) GetConsensusStatus() *ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

// ProposeRequest is sent to all poolers after recruitment to establish a new primary.
// Each pooler self-identifies based on proposal.proposal_leader_id:
//   - If proposal_leader_id == self: validate recruitment_position, promote to primary,
//     configure sync replication, write rule history
//   - Otherwise: set primary_conninfo to the proposal leader and resume replication
type ProposeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coordinator's proposal, containing the term revocation, proposal
	// leader ID, proposed rule, and minimum WAL position for the leader.
	Proposal      *CoordinatorProposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeRequest) Reset() {
	*x = ProposeRequest{}
	mi := &file_consensusdata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRequest) ProtoMessage() {}

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{14}
}

func (x *ProposeRequest) GetProposal() *CoordinatorProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

// ProposeResponse is returned after the pooler has processed the proposal.
type ProposeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The pooler's consensus status after applying the proposal.
	ConsensusStatus *ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposeResponse) Reset() {
	*x = ProposeResponse{}
	mi := &file_consensusdata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeResponse) ProtoMessage() {}

func (x *ProposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeResponse.ProtoReflect.Descriptor instead.
func (*ProposeResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{15}
}

func (x *ProposeResponse) GetConsensusStatus() *ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

// InformRequest is sent to all poolers to notify them of a committed decision.
// No authority proof is required since this represents an already-committed fact.
// Sets highest_known_decision in the pooler's ConsensusStatus.
type InformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The committed shard rule.
	Rule          *ShardRule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformRequest) Reset() {
	*x = InformRequest{}
	mi := &file_consensusdata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformRequest) ProtoMessage() {}

func (x *InformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformRequest.ProtoReflect.Descriptor instead.
func (*InformRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{16}
}

func (x *InformRequest) GetRule() *ShardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// InformResponse is returned after the pooler acknowledges the informed rule.
type InformResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The pooler's consensus status after acknowledging the rule.
	ConsensusStatus *ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InformResponse) Reset() {
	*x = InformResponse{}
	mi := &file_consensusdata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformResponse) ProtoMessage() {}

func (x *InformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformResponse.ProtoReflect.Descriptor instead.
func (*InformResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{17}
}

func (x *InformResponse) GetConsensusStatus() *ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

var File_consensusdata_proto protoreflect.FileDescriptor

const file_consensusdata_proto_rawDesc = "" +
	"\n" +
	"\x13consensusdata.proto\x12\rconsensusdata\x1a\x15clustermetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\n" +
	"RuleNumber\x12)\n" +
	"\x10coordinator_term\x18\x01 \x01(\x03R\x0fcoordinatorTerm\x12%\n" +
	"\x0eleader_subterm\x18\x02 \x01(\x03R\rleaderSubterm\"\x84\x03\n" +
	"\tShardRule\x12:\n" +
	"\vrule_number\x18\x01 \x01(\v2\x19.consensusdata.RuleNumberR\n" +
	"ruleNumber\x122\n" +
	"\n" +
	"primary_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\tprimaryId\x12:\n" +
	"\x0ecohort_members\x18\x03 \x03(\v2\x13.clustermetadata.IDR\rcohortMembers\x12N\n" +
	"\x11durability_policy\x18\x04 \x01(\v2!.clustermetadata.DurabilityPolicyR\x10durabilityPolicy\x12:\n" +
	"\x0ecoordinator_id\x18\x05 \x01(\v2\x13.clustermetadata.IDR\rcoordinatorId\x12?\n" +
	"\rcreation_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\"P\n" +
	"\x0ePoolerPosition\x12,\n" +
	"\x04rule\x18\x01 \x01(\v2\x18.consensusdata.ShardRuleR\x04rule\x12\x10\n" +
	"\x03lsn\x18\x02 \x01(\tR\x03lsn\"\xab\x02\n" +
	"\vWALPosition\x12\x1f\n" +
	"\vcurrent_lsn\x18\x01 \x01(\tR\n" +
	"currentLsn\x12(\n" +
	"\x10last_receive_lsn\x18\x02 \x01(\tR\x0elastReceiveLsn\x12&\n" +
	"\x0flast_replay_lsn\x18\x03 \x01(\tR\rlastReplayLsn\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vtimeline_id\x18\x05 \x01(\x03R\n" +
	"timelineId\x12'\n" +
	"\x0fleadership_term\x18\x06 \x01(\x03R\x0eleadershipTerm\x12%\n" +
	"\x0ecohort_members\x18\a \x03(\tR\rcohortMembers\"\xe1\x01\n" +
	"\x0eTermRevocation\x12,\n" +
	"\x12revoked_below_term\x18\x01 \x01(\x03R\x10revokedBelowTerm\x12K\n" +
	"\x17accepted_coordinator_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\x15acceptedCoordinatorId\x12T\n" +
	"\x18coordinator_initiated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x16coordinatorInitiatedAt\"c\n" +
	"\x13RecruitmentPosition\x12:\n" +
	"\vrule_number\x18\x01 \x01(\v2\x19.consensusdata.RuleNumberR\n" +
	"ruleNumber\x12\x10\n" +
	"\x03lsn\x18\x02 \x01(\tR\x03lsn\"n\n" +
	"\x0eProposalLeader\x12#\n" +
	"\x02id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12#\n" +
	"\rpostgres_port\x18\x03 \x01(\x05R\fpostgresPort\"\xbb\x02\n" +
	"\x13CoordinatorProposal\x12F\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1d.consensusdata.TermRevocationR\x0etermRevocation\x12F\n" +
	"\x0fproposal_leader\x18\x02 \x01(\v2\x1d.consensusdata.ProposalLeaderR\x0eproposalLeader\x12=\n" +
	"\rproposed_rule\x18\x03 \x01(\v2\x18.consensusdata.ShardRuleR\fproposedRule\x12U\n" +
	"\x14recruitment_position\x18\x04 \x01(\v2\".consensusdata.RecruitmentPositionR\x13recruitmentPosition\"\xee\x02\n" +
	"\x0fConsensusStatus\x12F\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1d.consensusdata.TermRevocationR\x0etermRevocation\x12H\n" +
	"\x10current_position\x18\x02 \x01(\v2\x1d.consensusdata.PoolerPositionR\x0fcurrentPosition\x12#\n" +
	"\x02id\x18\x04 \x01(\v2\x13.clustermetadata.IDR\x02id\x12T\n" +
	"\x14in_progress_proposal\x18\x05 \x01(\v2\".consensusdata.CoordinatorProposalR\x12inProgressProposal\x12N\n" +
	"\x16highest_known_decision\x18\x06 \x01(\v2\x18.consensusdata.ShardRuleR\x14highestKnownDecision\"*\n" +
	"\rStatusRequest\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\"\xd4\x03\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tpooler_id\x18\x01 \x01(\tR\bpoolerId\x12=\n" +
	"\fwal_position\x18\x04 \x01(\v2\x1a.consensusdata.WALPositionR\vwalPosition\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x05 \x01(\bR\tisHealthy\x12\x1f\n" +
	"\vis_eligible\x18\x06 \x01(\bR\n" +
	"isEligible\x12\x12\n" +
	"\x04cell\x18\a \x01(\tR\x04cell\x12/\n" +
	"\x04role\x18\t \x01(\x0e2\x1b.consensusdata.PostgresRoleR\x04role\x12@\n" +
	"\rtimeline_info\x18\n" +
	" \x01(\v2\x1b.consensusdata.TimelineInfoR\ftimelineInfo\x12I\n" +
	"\x10consensus_status\x18\f \x01(\v2\x1e.consensusdata.ConsensusStatusR\x0fconsensusStatus\x12T\n" +
	"\x13availability_status\x18\r \x01(\v2#.clustermetadata.AvailabilityStatusR\x12availabilityStatus\"/\n" +
	"\fTimelineInfo\x12\x1f\n" +
	"\vtimeline_id\x18\x01 \x01(\x03R\n" +
	"timelineId\"X\n" +
	"\x0eRecruitRequest\x12F\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1d.consensusdata.TermRevocationR\x0etermRevocation\"\\\n" +
	"\x0fRecruitResponse\x12I\n" +
	"\x10consensus_status\x18\x01 \x01(\v2\x1e.consensusdata.ConsensusStatusR\x0fconsensusStatus\"P\n" +
	"\x0eProposeRequest\x12>\n" +
	"\bproposal\x18\x01 \x01(\v2\".consensusdata.CoordinatorProposalR\bproposal\"\\\n" +
	"\x0fProposeResponse\x12I\n" +
	"\x10consensus_status\x18\x01 \x01(\v2\x1e.consensusdata.ConsensusStatusR\x0fconsensusStatus\"=\n" +
	"\rInformRequest\x12,\n" +
	"\x04rule\x18\x01 \x01(\v2\x18.consensusdata.ShardRuleR\x04rule\"[\n" +
	"\x0eInformResponse\x12I\n" +
	"\x10consensus_status\x18\x01 \x01(\v2\x1e.consensusdata.ConsensusStatusR\x0fconsensusStatus*c\n" +
	"\fPostgresRole\x12\x1d\n" +
	"\x19POSTGRES_ROLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15POSTGRES_ROLE_PRIMARY\x10\x01\x12\x19\n" +
	"\x15POSTGRES_ROLE_REPLICA\x10\x02B4Z2github.com/multigres/multigres/go/pb/consensusdatab\x06proto3"

var (
	file_consensusdata_proto_rawDescOnce sync.Once
	file_consensusdata_proto_rawDescData []byte
)

func file_consensusdata_proto_rawDescGZIP() []byte {
	file_consensusdata_proto_rawDescOnce.Do(func() {
		file_consensusdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)))
	})
	return file_consensusdata_proto_rawDescData
}

var file_consensusdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_consensusdata_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_consensusdata_proto_goTypes = []any{
	(PostgresRole)(0),                          // 0: consensusdata.PostgresRole
	(*RuleNumber)(nil),                         // 1: consensusdata.RuleNumber
	(*ShardRule)(nil),                          // 2: consensusdata.ShardRule
	(*PoolerPosition)(nil),                     // 3: consensusdata.PoolerPosition
	(*WALPosition)(nil),                        // 4: consensusdata.WALPosition
	(*TermRevocation)(nil),                     // 5: consensusdata.TermRevocation
	(*RecruitmentPosition)(nil),                // 6: consensusdata.RecruitmentPosition
	(*ProposalLeader)(nil),                     // 7: consensusdata.ProposalLeader
	(*CoordinatorProposal)(nil),                // 8: consensusdata.CoordinatorProposal
	(*ConsensusStatus)(nil),                    // 9: consensusdata.ConsensusStatus
	(*StatusRequest)(nil),                      // 10: consensusdata.StatusRequest
	(*StatusResponse)(nil),                     // 11: consensusdata.StatusResponse
	(*TimelineInfo)(nil),                       // 12: consensusdata.TimelineInfo
	(*RecruitRequest)(nil),                     // 13: consensusdata.RecruitRequest
	(*RecruitResponse)(nil),                    // 14: consensusdata.RecruitResponse
	(*ProposeRequest)(nil),                     // 15: consensusdata.ProposeRequest
	(*ProposeResponse)(nil),                    // 16: consensusdata.ProposeResponse
	(*InformRequest)(nil),                      // 17: consensusdata.InformRequest
	(*InformResponse)(nil),                     // 18: consensusdata.InformResponse
	(*clustermetadata.ID)(nil),                 // 19: clustermetadata.ID
	(*clustermetadata.DurabilityPolicy)(nil),   // 20: clustermetadata.DurabilityPolicy
	(*timestamppb.Timestamp)(nil),              // 21: google.protobuf.Timestamp
	(*clustermetadata.AvailabilityStatus)(nil), // 22: clustermetadata.AvailabilityStatus
}
var file_consensusdata_proto_depIdxs = []int32{
	1,  // 0: consensusdata.ShardRule.rule_number:type_name -> consensusdata.RuleNumber
	19, // 1: consensusdata.ShardRule.primary_id:type_name -> clustermetadata.ID
	19, // 2: consensusdata.ShardRule.cohort_members:type_name -> clustermetadata.ID
	20, // 3: consensusdata.ShardRule.durability_policy:type_name -> clustermetadata.DurabilityPolicy
	19, // 4: consensusdata.ShardRule.coordinator_id:type_name -> clustermetadata.ID
	21, // 5: consensusdata.ShardRule.creation_time:type_name -> google.protobuf.Timestamp
	2,  // 6: consensusdata.PoolerPosition.rule:type_name -> consensusdata.ShardRule
	21, // 7: consensusdata.WALPosition.timestamp:type_name -> google.protobuf.Timestamp
	19, // 8: consensusdata.TermRevocation.accepted_coordinator_id:type_name -> clustermetadata.ID
	21, // 9: consensusdata.TermRevocation.coordinator_initiated_at:type_name -> google.protobuf.Timestamp
	1,  // 10: consensusdata.RecruitmentPosition.rule_number:type_name -> consensusdata.RuleNumber
	19, // 11: consensusdata.ProposalLeader.id:type_name -> clustermetadata.ID
	5,  // 12: consensusdata.CoordinatorProposal.term_revocation:type_name -> consensusdata.TermRevocation
	7,  // 13: consensusdata.CoordinatorProposal.proposal_leader:type_name -> consensusdata.ProposalLeader
	2,  // 14: consensusdata.CoordinatorProposal.proposed_rule:type_name -> consensusdata.ShardRule
	6,  // 15: consensusdata.CoordinatorProposal.recruitment_position:type_name -> consensusdata.RecruitmentPosition
	5,  // 16: consensusdata.ConsensusStatus.term_revocation:type_name -> consensusdata.TermRevocation
	3,  // 17: consensusdata.ConsensusStatus.current_position:type_name -> consensusdata.PoolerPosition
	19, // 18: consensusdata.ConsensusStatus.id:type_name -> clustermetadata.ID
	8,  // 19: consensusdata.ConsensusStatus.in_progress_proposal:type_name -> consensusdata.CoordinatorProposal
	2,  // 20: consensusdata.ConsensusStatus.highest_known_decision:type_name -> consensusdata.ShardRule
	4,  // 21: consensusdata.StatusResponse.wal_position:type_name -> consensusdata.WALPosition
	0,  // 22: consensusdata.StatusResponse.role:type_name -> consensusdata.PostgresRole
	12, // 23: consensusdata.StatusResponse.timeline_info:type_name -> consensusdata.TimelineInfo
	9,  // 24: consensusdata.StatusResponse.consensus_status:type_name -> consensusdata.ConsensusStatus
	22, // 25: consensusdata.StatusResponse.availability_status:type_name -> clustermetadata.AvailabilityStatus
	5,  // 26: consensusdata.RecruitRequest.term_revocation:type_name -> consensusdata.TermRevocation
	9,  // 27: consensusdata.RecruitResponse.consensus_status:type_name -> consensusdata.ConsensusStatus
	8,  // 28: consensusdata.ProposeRequest.proposal:type_name -> consensusdata.CoordinatorProposal
	9,  // 29: consensusdata.ProposeResponse.consensus_status:type_name -> consensusdata.ConsensusStatus
	2,  // 30: consensusdata.InformRequest.rule:type_name -> consensusdata.ShardRule
	9,  // 31: consensusdata.InformResponse.consensus_status:type_name -> consensusdata.ConsensusStatus
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_consensusdata_proto_init() }
func file_consensusdata_proto_init() {
	if File_consensusdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensusdata_proto_goTypes,
		DependencyIndexes: file_consensusdata_proto_depIdxs,
		EnumInfos:         file_consensusdata_proto_enumTypes,
		MessageInfos:      file_consensusdata_proto_msgTypes,
	}.Build()
	File_consensusdata_proto = out.File
	file_consensusdata_proto_goTypes = nil
	file_consensusdata_proto_depIdxs = nil
}
