// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: consensusdata.proto

//go:build protoopaque

package consensusdata

import (
	reflect "reflect"
	unsafe "unsafe"

	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WAL position for tracking replication state
type WALPosition struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CurrentLsn     string                 `protobuf:"bytes,1,opt,name=current_lsn,json=currentLsn,proto3"`
	xxx_hidden_LastReceiveLsn string                 `protobuf:"bytes,2,opt,name=last_receive_lsn,json=lastReceiveLsn,proto3"`
	xxx_hidden_LastReplayLsn  string                 `protobuf:"bytes,3,opt,name=last_replay_lsn,json=lastReplayLsn,proto3"`
	xxx_hidden_Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WALPosition) Reset() {
	*x = WALPosition{}
	mi := &file_consensusdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALPosition) ProtoMessage() {}

func (x *WALPosition) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WALPosition) GetCurrentLsn() string {
	if x != nil {
		return x.xxx_hidden_CurrentLsn
	}
	return ""
}

func (x *WALPosition) GetLastReceiveLsn() string {
	if x != nil {
		return x.xxx_hidden_LastReceiveLsn
	}
	return ""
}

func (x *WALPosition) GetLastReplayLsn() string {
	if x != nil {
		return x.xxx_hidden_LastReplayLsn
	}
	return ""
}

func (x *WALPosition) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *WALPosition) SetCurrentLsn(v string) {
	x.xxx_hidden_CurrentLsn = v
}

func (x *WALPosition) SetLastReceiveLsn(v string) {
	x.xxx_hidden_LastReceiveLsn = v
}

func (x *WALPosition) SetLastReplayLsn(v string) {
	x.xxx_hidden_LastReplayLsn = v
}

func (x *WALPosition) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *WALPosition) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *WALPosition) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type WALPosition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// For primary: current write position from pg_current_wal_lsn()
	// For standby: empty (use last_receive_lsn and last_replay_lsn instead)
	CurrentLsn string
	// For standby: last WAL position received from pg_last_wal_receive_lsn()
	// For primary: empty
	LastReceiveLsn string
	// For standby: last WAL position replayed from pg_last_wal_replay_lsn()
	// For primary: empty
	LastReplayLsn string
	// Timestamp when this position was recorded
	Timestamp *timestamppb.Timestamp
}

func (b0 WALPosition_builder) Build() *WALPosition {
	m0 := &WALPosition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CurrentLsn = b.CurrentLsn
	x.xxx_hidden_LastReceiveLsn = b.LastReceiveLsn
	x.xxx_hidden_LastReplayLsn = b.LastReplayLsn
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

// BeginTerm is sent by coordinators during leader appointments
type BeginTermRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Term          int64                  `protobuf:"varint,1,opt,name=term,proto3"`
	xxx_hidden_CandidateId   *clustermetadata.ID    `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3"`
	xxx_hidden_ShardId       string                 `protobuf:"bytes,3,opt,name=shard_id,json=shardId,proto3"`
	xxx_hidden_PolicyVersion int64                  `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BeginTermRequest) Reset() {
	*x = BeginTermRequest{}
	mi := &file_consensusdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTermRequest) ProtoMessage() {}

func (x *BeginTermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BeginTermRequest) GetTerm() int64 {
	if x != nil {
		return x.xxx_hidden_Term
	}
	return 0
}

func (x *BeginTermRequest) GetCandidateId() *clustermetadata.ID {
	if x != nil {
		return x.xxx_hidden_CandidateId
	}
	return nil
}

func (x *BeginTermRequest) GetShardId() string {
	if x != nil {
		return x.xxx_hidden_ShardId
	}
	return ""
}

func (x *BeginTermRequest) GetPolicyVersion() int64 {
	if x != nil {
		return x.xxx_hidden_PolicyVersion
	}
	return 0
}

func (x *BeginTermRequest) SetTerm(v int64) {
	x.xxx_hidden_Term = v
}

func (x *BeginTermRequest) SetCandidateId(v *clustermetadata.ID) {
	x.xxx_hidden_CandidateId = v
}

func (x *BeginTermRequest) SetShardId(v string) {
	x.xxx_hidden_ShardId = v
}

func (x *BeginTermRequest) SetPolicyVersion(v int64) {
	x.xxx_hidden_PolicyVersion = v
}

func (x *BeginTermRequest) HasCandidateId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CandidateId != nil
}

func (x *BeginTermRequest) ClearCandidateId() {
	x.xxx_hidden_CandidateId = nil
}

type BeginTermRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Term of the candidate
	Term int64
	// ID of the candidate for appointment
	CandidateId *clustermetadata.ID
	// Shard ID for this appointment
	ShardId string
	// Version of the durability policy
	PolicyVersion int64
}

func (b0 BeginTermRequest_builder) Build() *BeginTermRequest {
	m0 := &BeginTermRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Term = b.Term
	x.xxx_hidden_CandidateId = b.CandidateId
	x.xxx_hidden_ShardId = b.ShardId
	x.xxx_hidden_PolicyVersion = b.PolicyVersion
	return m0
}

type BeginTermResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Term     int64                  `protobuf:"varint,1,opt,name=term,proto3"`
	xxx_hidden_Accepted bool                   `protobuf:"varint,2,opt,name=accepted,proto3"`
	xxx_hidden_PoolerId string                 `protobuf:"bytes,3,opt,name=pooler_id,json=poolerId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BeginTermResponse) Reset() {
	*x = BeginTermResponse{}
	mi := &file_consensusdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTermResponse) ProtoMessage() {}

func (x *BeginTermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BeginTermResponse) GetTerm() int64 {
	if x != nil {
		return x.xxx_hidden_Term
	}
	return 0
}

func (x *BeginTermResponse) GetAccepted() bool {
	if x != nil {
		return x.xxx_hidden_Accepted
	}
	return false
}

func (x *BeginTermResponse) GetPoolerId() string {
	if x != nil {
		return x.xxx_hidden_PoolerId
	}
	return ""
}

func (x *BeginTermResponse) SetTerm(v int64) {
	x.xxx_hidden_Term = v
}

func (x *BeginTermResponse) SetAccepted(v bool) {
	x.xxx_hidden_Accepted = v
}

func (x *BeginTermResponse) SetPoolerId(v string) {
	x.xxx_hidden_PoolerId = v
}

type BeginTermResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current term, for candidate to update itself
	Term int64
	// True if the term was accepted
	Accepted bool
	// ID of the responding pooler
	PoolerId string
}

func (b0 BeginTermResponse_builder) Build() *BeginTermResponse {
	m0 := &BeginTermResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Term = b.Term
	x.xxx_hidden_Accepted = b.Accepted
	x.xxx_hidden_PoolerId = b.PoolerId
	return m0
}

// Status returns the current status of a node
type StatusRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Term    int64                  `protobuf:"varint,1,opt,name=term,proto3"`
	xxx_hidden_ShardId string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_consensusdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusRequest) GetTerm() int64 {
	if x != nil {
		return x.xxx_hidden_Term
	}
	return 0
}

func (x *StatusRequest) GetShardId() string {
	if x != nil {
		return x.xxx_hidden_ShardId
	}
	return ""
}

func (x *StatusRequest) SetTerm(v int64) {
	x.xxx_hidden_Term = v
}

func (x *StatusRequest) SetShardId(v string) {
	x.xxx_hidden_ShardId = v
}

type StatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional term to include in response
	Term int64
	// Shard ID to query status for
	ShardId string
}

func (b0 StatusRequest_builder) Build() *StatusRequest {
	m0 := &StatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Term = b.Term
	x.xxx_hidden_ShardId = b.ShardId
	return m0
}

type StatusResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PoolerId    string                 `protobuf:"bytes,1,opt,name=pooler_id,json=poolerId,proto3"`
	xxx_hidden_CurrentTerm int64                  `protobuf:"varint,2,opt,name=current_term,json=currentTerm,proto3"`
	xxx_hidden_WalPosition *WALPosition           `protobuf:"bytes,4,opt,name=wal_position,json=walPosition,proto3"`
	xxx_hidden_IsHealthy   bool                   `protobuf:"varint,5,opt,name=is_healthy,json=isHealthy,proto3"`
	xxx_hidden_IsEligible  bool                   `protobuf:"varint,6,opt,name=is_eligible,json=isEligible,proto3"`
	xxx_hidden_Cell        string                 `protobuf:"bytes,7,opt,name=cell,proto3"`
	xxx_hidden_Role        string                 `protobuf:"bytes,9,opt,name=role,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_consensusdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusResponse) GetPoolerId() string {
	if x != nil {
		return x.xxx_hidden_PoolerId
	}
	return ""
}

func (x *StatusResponse) GetCurrentTerm() int64 {
	if x != nil {
		return x.xxx_hidden_CurrentTerm
	}
	return 0
}

func (x *StatusResponse) GetWalPosition() *WALPosition {
	if x != nil {
		return x.xxx_hidden_WalPosition
	}
	return nil
}

func (x *StatusResponse) GetIsHealthy() bool {
	if x != nil {
		return x.xxx_hidden_IsHealthy
	}
	return false
}

func (x *StatusResponse) GetIsEligible() bool {
	if x != nil {
		return x.xxx_hidden_IsEligible
	}
	return false
}

func (x *StatusResponse) GetCell() string {
	if x != nil {
		return x.xxx_hidden_Cell
	}
	return ""
}

func (x *StatusResponse) GetRole() string {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return ""
}

func (x *StatusResponse) SetPoolerId(v string) {
	x.xxx_hidden_PoolerId = v
}

func (x *StatusResponse) SetCurrentTerm(v int64) {
	x.xxx_hidden_CurrentTerm = v
}

func (x *StatusResponse) SetWalPosition(v *WALPosition) {
	x.xxx_hidden_WalPosition = v
}

func (x *StatusResponse) SetIsHealthy(v bool) {
	x.xxx_hidden_IsHealthy = v
}

func (x *StatusResponse) SetIsEligible(v bool) {
	x.xxx_hidden_IsEligible = v
}

func (x *StatusResponse) SetCell(v string) {
	x.xxx_hidden_Cell = v
}

func (x *StatusResponse) SetRole(v string) {
	x.xxx_hidden_Role = v
}

func (x *StatusResponse) HasWalPosition() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WalPosition != nil
}

func (x *StatusResponse) ClearWalPosition() {
	x.xxx_hidden_WalPosition = nil
}

type StatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Pooler ID
	PoolerId string
	// Current term from local file
	CurrentTerm int64
	// Current WAL position
	WalPosition *WALPosition
	// Whether Postgres is healthy and reachable
	IsHealthy bool
	// Whether this pooler is eligible to be a leader
	IsEligible bool
	// Cell identifier
	Cell string
	// Current role (primary/replica)
	Role string
}

func (b0 StatusResponse_builder) Build() *StatusResponse {
	m0 := &StatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PoolerId = b.PoolerId
	x.xxx_hidden_CurrentTerm = b.CurrentTerm
	x.xxx_hidden_WalPosition = b.WalPosition
	x.xxx_hidden_IsHealthy = b.IsHealthy
	x.xxx_hidden_IsEligible = b.IsEligible
	x.xxx_hidden_Cell = b.Cell
	x.xxx_hidden_Role = b.Role
	return m0
}

// GetLeadershipView returns leadership information from the heartbeat table
type LeadershipViewRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ShardId string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeadershipViewRequest) Reset() {
	*x = LeadershipViewRequest{}
	mi := &file_consensusdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipViewRequest) ProtoMessage() {}

func (x *LeadershipViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LeadershipViewRequest) GetShardId() string {
	if x != nil {
		return x.xxx_hidden_ShardId
	}
	return ""
}

func (x *LeadershipViewRequest) SetShardId(v string) {
	x.xxx_hidden_ShardId = v
}

type LeadershipViewRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Shard ID to query
	ShardId string
}

func (b0 LeadershipViewRequest_builder) Build() *LeadershipViewRequest {
	m0 := &LeadershipViewRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ShardId = b.ShardId
	return m0
}

type LeadershipViewResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeaderId         string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3"`
	xxx_hidden_LastHeartbeat    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3"`
	xxx_hidden_ReplicationLagNs int64                  `protobuf:"varint,5,opt,name=replication_lag_ns,json=replicationLagNs,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *LeadershipViewResponse) Reset() {
	*x = LeadershipViewResponse{}
	mi := &file_consensusdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipViewResponse) ProtoMessage() {}

func (x *LeadershipViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LeadershipViewResponse) GetLeaderId() string {
	if x != nil {
		return x.xxx_hidden_LeaderId
	}
	return ""
}

func (x *LeadershipViewResponse) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastHeartbeat
	}
	return nil
}

func (x *LeadershipViewResponse) GetReplicationLagNs() int64 {
	if x != nil {
		return x.xxx_hidden_ReplicationLagNs
	}
	return 0
}

func (x *LeadershipViewResponse) SetLeaderId(v string) {
	x.xxx_hidden_LeaderId = v
}

func (x *LeadershipViewResponse) SetLastHeartbeat(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastHeartbeat = v
}

func (x *LeadershipViewResponse) SetReplicationLagNs(v int64) {
	x.xxx_hidden_ReplicationLagNs = v
}

func (x *LeadershipViewResponse) HasLastHeartbeat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastHeartbeat != nil
}

func (x *LeadershipViewResponse) ClearLastHeartbeat() {
	x.xxx_hidden_LastHeartbeat = nil
}

type LeadershipViewResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the current leader
	LeaderId string
	// Last heartbeat timestamp
	LastHeartbeat *timestamppb.Timestamp
	// Calculated replication lag in nanoseconds
	ReplicationLagNs int64
}

func (b0 LeadershipViewResponse_builder) Build() *LeadershipViewResponse {
	m0 := &LeadershipViewResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeaderId = b.LeaderId
	x.xxx_hidden_LastHeartbeat = b.LastHeartbeat
	x.xxx_hidden_ReplicationLagNs = b.ReplicationLagNs
	return m0
}

// CanReachPrimary checks if this node can reach the primary
type CanReachPrimaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PrimaryHost string                 `protobuf:"bytes,1,opt,name=primary_host,json=primaryHost,proto3"`
	xxx_hidden_PrimaryPort int32                  `protobuf:"varint,2,opt,name=primary_port,json=primaryPort,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CanReachPrimaryRequest) Reset() {
	*x = CanReachPrimaryRequest{}
	mi := &file_consensusdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanReachPrimaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanReachPrimaryRequest) ProtoMessage() {}

func (x *CanReachPrimaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CanReachPrimaryRequest) GetPrimaryHost() string {
	if x != nil {
		return x.xxx_hidden_PrimaryHost
	}
	return ""
}

func (x *CanReachPrimaryRequest) GetPrimaryPort() int32 {
	if x != nil {
		return x.xxx_hidden_PrimaryPort
	}
	return 0
}

func (x *CanReachPrimaryRequest) SetPrimaryHost(v string) {
	x.xxx_hidden_PrimaryHost = v
}

func (x *CanReachPrimaryRequest) SetPrimaryPort(v int32) {
	x.xxx_hidden_PrimaryPort = v
}

type CanReachPrimaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Primary host
	PrimaryHost string
	// Primary port
	PrimaryPort int32
}

func (b0 CanReachPrimaryRequest_builder) Build() *CanReachPrimaryRequest {
	m0 := &CanReachPrimaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PrimaryHost = b.PrimaryHost
	x.xxx_hidden_PrimaryPort = b.PrimaryPort
	return m0
}

type CanReachPrimaryResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Reachable    bool                   `protobuf:"varint,1,opt,name=reachable,proto3"`
	xxx_hidden_ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CanReachPrimaryResponse) Reset() {
	*x = CanReachPrimaryResponse{}
	mi := &file_consensusdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanReachPrimaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanReachPrimaryResponse) ProtoMessage() {}

func (x *CanReachPrimaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CanReachPrimaryResponse) GetReachable() bool {
	if x != nil {
		return x.xxx_hidden_Reachable
	}
	return false
}

func (x *CanReachPrimaryResponse) GetErrorMessage() string {
	if x != nil {
		return x.xxx_hidden_ErrorMessage
	}
	return ""
}

func (x *CanReachPrimaryResponse) SetReachable(v bool) {
	x.xxx_hidden_Reachable = v
}

func (x *CanReachPrimaryResponse) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = v
}

type CanReachPrimaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether primary is reachable
	Reachable bool
	// Error message if not reachable
	ErrorMessage string
}

func (b0 CanReachPrimaryResponse_builder) Build() *CanReachPrimaryResponse {
	m0 := &CanReachPrimaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Reachable = b.Reachable
	x.xxx_hidden_ErrorMessage = b.ErrorMessage
	return m0
}

var File_consensusdata_proto protoreflect.FileDescriptor

const file_consensusdata_proto_rawDesc = "" +
	"\n" +
	"\x13consensusdata.proto\x12\rconsensusdata\x1a\x15clustermetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n" +
	"\vWALPosition\x12\x1f\n" +
	"\vcurrent_lsn\x18\x01 \x01(\tR\n" +
	"currentLsn\x12(\n" +
	"\x10last_receive_lsn\x18\x02 \x01(\tR\x0elastReceiveLsn\x12&\n" +
	"\x0flast_replay_lsn\x18\x03 \x01(\tR\rlastReplayLsn\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa0\x01\n" +
	"\x10BeginTermRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x126\n" +
	"\fcandidate_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\vcandidateId\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\tR\ashardId\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x03R\rpolicyVersion\"`\n" +
	"\x11BeginTermResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1b\n" +
	"\tpooler_id\x18\x03 \x01(\tR\bpoolerId\">\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\"\xf7\x01\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tpooler_id\x18\x01 \x01(\tR\bpoolerId\x12!\n" +
	"\fcurrent_term\x18\x02 \x01(\x03R\vcurrentTerm\x12=\n" +
	"\fwal_position\x18\x04 \x01(\v2\x1a.consensusdata.WALPositionR\vwalPosition\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x05 \x01(\bR\tisHealthy\x12\x1f\n" +
	"\vis_eligible\x18\x06 \x01(\bR\n" +
	"isEligible\x12\x12\n" +
	"\x04cell\x18\a \x01(\tR\x04cell\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\"2\n" +
	"\x15LeadershipViewRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"\xa6\x01\n" +
	"\x16LeadershipViewResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12,\n" +
	"\x12replication_lag_ns\x18\x05 \x01(\x03R\x10replicationLagNs\"^\n" +
	"\x16CanReachPrimaryRequest\x12!\n" +
	"\fprimary_host\x18\x01 \x01(\tR\vprimaryHost\x12!\n" +
	"\fprimary_port\x18\x02 \x01(\x05R\vprimaryPort\"\\\n" +
	"\x17CanReachPrimaryResponse\x12\x1c\n" +
	"\treachable\x18\x01 \x01(\bR\treachable\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB4Z2github.com/multigres/multigres/go/pb/consensusdatab\x06proto3"

var file_consensusdata_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_consensusdata_proto_goTypes = []any{
	(*WALPosition)(nil),             // 0: consensusdata.WALPosition
	(*BeginTermRequest)(nil),        // 1: consensusdata.BeginTermRequest
	(*BeginTermResponse)(nil),       // 2: consensusdata.BeginTermResponse
	(*StatusRequest)(nil),           // 3: consensusdata.StatusRequest
	(*StatusResponse)(nil),          // 4: consensusdata.StatusResponse
	(*LeadershipViewRequest)(nil),   // 5: consensusdata.LeadershipViewRequest
	(*LeadershipViewResponse)(nil),  // 6: consensusdata.LeadershipViewResponse
	(*CanReachPrimaryRequest)(nil),  // 7: consensusdata.CanReachPrimaryRequest
	(*CanReachPrimaryResponse)(nil), // 8: consensusdata.CanReachPrimaryResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
	(*clustermetadata.ID)(nil),      // 10: clustermetadata.ID
}
var file_consensusdata_proto_depIdxs = []int32{
	9,  // 0: consensusdata.WALPosition.timestamp:type_name -> google.protobuf.Timestamp
	10, // 1: consensusdata.BeginTermRequest.candidate_id:type_name -> clustermetadata.ID
	0,  // 2: consensusdata.StatusResponse.wal_position:type_name -> consensusdata.WALPosition
	9,  // 3: consensusdata.LeadershipViewResponse.last_heartbeat:type_name -> google.protobuf.Timestamp
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_consensusdata_proto_init() }
func file_consensusdata_proto_init() {
	if File_consensusdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensusdata_proto_goTypes,
		DependencyIndexes: file_consensusdata_proto_depIdxs,
		MessageInfos:      file_consensusdata_proto_msgTypes,
	}.Build()
	File_consensusdata_proto = out.File
	file_consensusdata_proto_goTypes = nil
	file_consensusdata_proto_depIdxs = nil
}
